### ISSUE TITLE
shiny example is blank

### ISSUE THREAD

**Issue by jrowen** [jrowen/rHandsontable#1]
The table is not appearing on the `shiny` example.

**Comment by majidJamili** [comment]
I try to run this code, the code is being executed with no error but I get my shiny app blank
library(shiny)
library(rhandsontable)

ui = shinyUI(fluidPage(
  
  titlePanel("Handsontable"),
  
  sidebarLayout(
    sidebarPanel(
      helpText("Handsontable demo output. Column add/delete does work ",
               "for tables with defined column properties, including type.")
     
    ),
    mainPanel(
      rHandsontableOutput("hot")
    )
  )
))

server = function(input, output) {
  output$hot <- renderRHandsontable({
    if(is.null(input$hot)){ #return(NULL)
    
      DF = data.frame(val = 1:10, bool = TRUE, big = LETTERS[1:10],
                      small = letters[1:10],
                      dt = seq(from = Sys.Date(), by = "days", length.out = 10),
                      stringsAsFactors = FALSE)
  
    }else{
      DF = hot_to_r(input$hot)
      
    }
    
    col_highlight = 2
    row_highlight = c(5, 7)
#  
    rhandsontable(DF, col_highlight = col_highlight, 
                  row_highlight = row_highlight,
                  width = 150, height = 200) %>%
      hot_cols(renderer = "
               function(instance, td, row, col, prop, value, cellProperties) {
                                          Handsontable.renderers.TextRenderer.apply(this, arguments);
                                          
                                          tbl = this.HTMLWidgets.widgets[0]
                                          
                                          hcols = tbl.params.col_highlight
                                          hcols = hcols instanceof Array ? hcols : [hcols] 
                                          hrows = tbl.params.row_highlight
                                          hrows = hrows instanceof Array ? hrows : [hrows] 
                                          
                                          if (hcols.includes(col) && hrows.includes(row)) {
                                          td.style.background = 'red';
                                          }
                                          else if (hcols.includes(col)) {
                                          td.style.background = 'lightgreen';
                                          }
                                          else if (hrows.includes(row)) {
                                          td.style.background = 'pink';
                                          }
                                          
                                          return td;
  }") 
  })
}

shinyApp(ui = ui, server = server)
