### ISSUE TITLE
hot_to_r function broken in R 3.3.0

### ISSUE THREAD

**Issue by lvandersypen** [jrowen/rhandsontable#100]
A commit that you made to fix issue #77 (https://github.com/jrowen/rhandsontable/commit/495e6aa65f65b887cf7d580bf19e8840d0d81dc2) has broken the hot_to_r function when using the latest version of R (3.3.0).  You can replicate the error by running the code at the bottom and then making a change to the data in the table.  The app will abort and you will receive the error below.  It is caused by using `rColClasses = unlist(params$rColClasses)[colHeaders]`, as that returns NAs, instead of the column classes.  Bizarrely, it doesn't cause an error in earlier versions of R (it is fine with 3.1.3), but we have now updated R to version 3.3.0 on our server and it has completely broken one of our apps.

_Error
Warning: Error in as: no method or default for coercing “character” to “NA”
Stack trace (innermost first):
    59: as
    58: colClasses
    57: <Anonymous>
    56: do.call
    55: hot_to_r
    54: observerFunc [C:\Users\.../server.R#15]
     1: shiny::runApp_

    library(rhandsontable)

    ui( 
      fluidPage(title = "Test", 
                column(12, wellPanel(width="100%",rHandsontableOutput("output_table"))
                )
      )
    )

    server(function(input, output, session) {
  
      a <- c("abc", "def")
      b <- c(1, 2)
  
      df <- data.frame(cbind(a, b), stringsAsFactors = FALSE)
      df$b <- as.numeric(df$b)
  
      values <- reactiveValues()
  
      values$df <- df
  
      observe({
        if (!is.null(input$output_table)) {
          values$df <- hot_to_r(input$output_table)
        }
    
      })
  
      output$output_table <- renderRHandsontable({rhandsontable(values$df, contextMenu = FALSE, rowHeaders = NULL,)})
  
    })

    shinyApp(ui = ui, server = server)

**Comment by jrowen** [comment]
I tried this on 3.3.1 and didn't run into an error.  Do you have a way to test with the newer version of R too?

**Comment by lvandersypen** [comment]
I updated to 3.3.1 on my PC and no longer experience the issue.  Therefore, I've requested that our server also be updated as soon as possible.  Many thanks for your prompt assistance.

**Comment by mathieu1** [comment]
The provided example works fine for me on 3.3.1, but I do experience this exact problem with a more complex dataframe. I'll try to get a minimal breaking example asap.

**Comment by lvandersypen** [comment]
I've just realised that my testing on Friday was with rhandsontable 0.3.1.  I still get the same error with rhandsontable 0.3.2, both on my PC and the server.

**Comment by jrowen** [comment]
If you can share a minimal example that generates errors in 3.3.1, I'll take another look.  I don't currently have a way to test on earlier versions of R.

**Comment by lvandersypen** [comment]
My original code above generates an error in R 3.3.1, but you need to be using the latest version of rhandsontable (0.3.2).

**Comment by lvandersypen** [comment]
I have modified my copy of rhandsontable 0.3.2 by reverting the commit that you made to fix issue #77 (495e6aa), and no longer get any error.

`unlist(params$rColClasses)[colHeaders]` returns NAs
`unlist(params$rColClasses)` correctly returns the column classes.  "character" and "numeric" in the case of my test code above.

Please can this code be changed back in the published package.

**Comment by jrowen** [comment]
Reverting the change causes the earlier bug to re-appear (the code below doesn't work).
```
library(rhandsontable)
library(shiny)

server <- function(input, output) {
  output$table <- renderRHandsontable({
    tbl = input$table
    if(!is.null(tbl)){
      df <- hot_to_r(tbl)
      print(df)
    } else {
      df = data.frame(LETTERS[1:5], matrix(1:25, ncol = 5), letters[1:5])
      colnames(df) <- c(" ", 1:5, "Test") 
    }
    rhandsontable(df, rowHeaders = NULL)
  })
}


ui <- shinyUI(
  fluidPage(
    titlePanel("Basic DataTable"),
    fluidRow(
      rHandsontableOutput("table")
    )
  )
)

shinyApp(ui = ui, server = server)
```
Can you send me your session info?  Also, can you try using the dev version of the library and see if that fixes your issue?

**Comment by mathieu1** [comment]
Ok, so my issue is that I set `colHeaders` to display nicer column names on the front-end. However `hot_to_r` assumes that column names and `colHeaders` are the same, and so breaks whenever there are discrepancies. To observe the problem, replace the line
```
    rhandsontable(df, rowHeaders = NULL)
```
with
```
    rhandsontable(df, rowHeaders = NULL, colHeaders = c(" ", 1:5, "Nicer column name"))
```
In the code above. (R 3.3.1, rhandsontable 0.3.2)

**Comment by lvandersypen** [comment]
You are spot on!  I also use `colHeaders` in my web app to display nicer column names in the table, but as you say they then don't match the `rColClasses` column names, so return "NA" for the column type which breaks the hot_to_r function.

Jonathan, is there an easy fix to the `toR` code in `misc.R` for this?

**Comment by jrowen** [comment]
Let me know if this doesn't resolve the issue.  Thanks for reporting.

**Comment by lvandersypen** [comment]
Your changes are more elaborate than the ones that I was going to suggest, which I had tested fix my issue, but also still work with your sample code above, as follows:-

Original `misc.R` code:-

    rClass = params$rClass
    colHeaders = unlist(params$colHeaders)
    rowHeaders = unlist(params$rowHeaders)
    rColClasses = unlist(params$rColClasses)[colHeaders]

My suggested `misc.R` code:-

    rClass = params$rClass
    colHeaders = unlist(params$colHeaders)
    rowHeaders = unlist(params$rowHeaders)
    rColnames = unlist(params$rColnames)
    rColClasses = unlist(params$rColClasses)[rColnames]

However, your changes have fixed my issue, but the version of your package that I installed from GitHub causes a much more severe problem, with parts of my table disappearing and reappearing as I navigate through or make changes to it.

I assume that this is caused by another change that has occurred since the package was last published in CRAN.  I will try to create a simple example and open a separate issue for this.

**Comment by venurapereratlc** [comment]
I am still having this issue, When i try to insert data into the table and pull it back out I get 

Error in as(d[[i]], colClasses[i]) : 
  no method or default for coercing “logical” to “NA”

Here is the code I am using to render the table
```

 output$uploadData <- renderRHandsontable({
    if (is.null(values$data.orig)) {
      query <-
        paste(
          "select * from vw_FACT_SITE_DATATABLE where Site_Name = '",
          input$siteID,
          "'",
          sep = ""
        )
      
      tn <- runQuery(dsn, query)
      
      names(tn) <- gsub("_", " ", names(tn))
      
      names(tn) <- gsub("perc", "%", names(tn))
      
      
      DF <<- tn
      
      values$data$orig <- tn
    }
    df <- values$data$orig[1, 6:ncol(values$data$orig)]
    
    print(df)
    
    df <- df[-1,]
    
    rhandsontable(df, readOnly = FALSE, selectCallback = FALSE) %>%
      hot_table(
        highlightCol = TRUE,
        highlightRow = TRUE,
        allowInvalid = TRUE
      )
    
  })

```

Any help would be appreciated . Is the problem down to the allowInvalid? If i don't allow this I seem unable to past rows from excel.

**Comment by jrowen** [comment]
Please try out the latest dev version and let me know if you are still running into problems.

**Comment by BazilD** [comment]
Hi jrowen, I hope you're well! Sorry for opening up a new thread! I am trying to update a rhandsontable with another rhandsontable using observe event and reactive values and i am getting the above error!
 my code is as follows:

library(shiny)
library(rhandsontable)

channel <- c("TV","Radio","Digital")
start.date <- as.Date("2017-01-01")
end.date <- as.Date("2017-01-07")
date.range <- as.POSIXct((seq(start.date,end.date,by="day")), origin = "1970-01-01")
date.range <- as.data.frame(date.range)
colnames(date.range) <- c("date")
date.range[channel] <- 0
table1 <- date.range
table2 <- date.range
#Define the tables.

ui <- fluidPage(
  br(),
  fluidRow(
    column(4, rHandsontableOutput("table1output")),
    column(4, rHandsontableOutput("table2output"))
  ))

server <- function(input,output,session){
  table <- reactiveValues()
  table$table1 <- table1
  table$table2 <- table2
  #define reactive values as table1 and table2

  output$table1output <- renderRHandsontable({rhandsontable(table$table1)})
  output$table2output <- renderRHandsontable({rhandsontable(table$table2)})
  #rhandsontable outputs

  observeEvent(input$table1output,{
    df <- hot_to_r(input$table1output)
    df <- as.data.frame(df)
    table$table2 <- df
  })
  #if a user updates table1 table2 should also update.

  observeEvent(input$table2output,{
    df <- hot_to_r(input$table2output)
    df <- as.data.frame(df)
    table$table1 <- df
  })
  #if a user updates table2 table1 should also update.

}

shinyApp(ui = ui, server = server)

Whenever I run the code i get the following errors:

Warning: Error in as: no method or default for coercing “character” to “NA” 
I can't for the life of me get this to work! Any help would be very much appreciated!

Cheers,

**Comment by bklingen** [comment]
This must have something to do with your date column. If you leave out the date column, everything works as expected, see below. I.e., you need to research how rhandsontable handles date formats.

```{r}
library(shiny)
library(rhandsontable)

#channel <- c("TV","Radio","Digital")
#start.date <- as.Date("2017-01-01")
#end.date <- as.Date("2017-01-07")
#date.range <- as.POSIXct((seq(start.date,end.date,by="day")), origin = "1970-01-01")
#date.range <- as.data.frame(date.range)
#colnames(date.range) <- c("date")
#date.range[channel] <- 0
table1 <- data.frame(1:7, 1, 7:1)
table2 <- data.frame(1:7, 1, 7:1)
#Define the tables.

ui <- fluidPage(
  br(),
  fluidRow(
    column(4, rHandsontableOutput("table1output")),
    column(4, rHandsontableOutput("table2output"))
  ))

server <- function(input,output,session){
  table <- reactiveValues()
  table$table1 <- table1
  table$table2 <- table2
  #define reactive values as table1 and table2
  
  output$table1output <- renderRHandsontable({rhandsontable(table$table1)})
  output$table2output <- renderRHandsontable({rhandsontable(table$table2)})
  #rhandsontable outputs
  
  observeEvent(input$table1output,{
    df <- hot_to_r(input$table1output)
    df <- as.data.frame(df)
    table$table2 <- df
  })
  #if a user updates table1 table2 should also update.
  
  observeEvent(input$table2output,{
    df <- hot_to_r(input$table2output)
    df <- as.data.frame(df)
    table$table1 <- df
  })
  #if a user updates table2 table1 should also update.
  
}

shinyApp(ui = ui, server = server)
```

**Comment by BazilD** [comment]
Thanks so much, changing the date format has worked perfectly! Cheers!
