### ISSUE TITLE
Small error in help menu for hot_col

### ISSUE THREAD

**Issue by petemorrison** [jrowen/rhandsontable#102]
Hi,

Much appreciate the work you've put into rhandsontable. 

Anyway, one of the links in the help menu for hot_col {rhandsontable} for date format is broken.

It says
"character defining the date format. See https://github.com/moment/momentMoment.js for details."

Something small, just noticed it when I was working my way through your documentation.

Thank you,

Pete M

**Comment by jrowen** [comment]
Thanks for reporting.
