### ISSUE TITLE
Parts of table disappear and reappear using rhandsontable 0.3.2.1

### ISSUE THREAD

**Issue by lvandersypen** [jrowen/rhandsontable#103]
There is an issue with the current dev version of the package (0.3.2.1), where parts of the table are invisible until you start to navigate around it.  Some parts of the table will also disappear when changes are made to the data in other parts of it.

You can replicate the problem by running the code below.  If you then scroll across to the right you can see that only columns up to 29 are visible.  If you then click in column 29 a further 7 columns appear (up to 36).  You have to click in several more columns to get the full table to appear.  However, if you then make a change to the data in one of the columns, you'll notice that some of the columns on the left will disappear (you will need to scroll back to see this).  This issue doesn't occur in 0.3.2, so has been caused by one of the changes in the dev version (0.3.2.1).

```
library(rhandsontable)
library(shiny)

server <- function(input, output, session) {
  output$table <- renderRHandsontable({
    tbl = input$table
    if(!is.null(tbl)){
      df <- hot_to_r(tbl)
      print(df)
    } else {
      df = data.frame(LETTERS[1:5], matrix(1:250, ncol = 50), letters[1:5])
      colnames(df) <- c(" ", 1:50, "Test") 
    }
    rhandsontable(df, rowHeaders = NULL)
  })
}


ui <- shinyUI(
  fluidPage(
    title = "Test", 
    column(12, 
           wellPanel(width="100%", rHandsontableOutput("table")
           )
    )
  )
)

shinyApp(ui = ui, server = server)
```

**Comment by jrowen** [comment]
Are you running this app in a browser window or via RStudio?  I can reproduce this behavior with the RStudio viewer and window, but everything looks fine if I view the app via an external browser.

**Comment by lvandersypen** [comment]
I'm running it in Chrome, but via RStudio (see screenshot below).  I can't test using the server, as that still has version 0.3.2 of rhandsontable.

![image](https://cloud.githubusercontent.com/assets/20973432/17704001/7dff16dc-63cb-11e6-902e-3bc32510f561.png)

**Comment by venurapereratlc** [comment]
I am still having this same issue, have you resolved it?

**Comment by jrowen** [comment]
I think I know the cause and hope to have a fix in the next few days.
