### ISSUE TITLE
Faster inputs on cells

### ISSUE THREAD

**Issue by RCesarSilva** [jrowen/rhandsontable#107]
@jrowen The issue is more of an performance enhancement rather than an error.
When clicking to add data to a table that receives multiple inputs there is a delay (~1 s) between the click and the actual input. Also, when pressing "Enter" to confirm the input there is also a small delay.

NOTE: the input is inside an "IF" statement which is inside an "Observe". The structure of the code in itself could be hindering the performance of the input.

**Comment by jrowen** [comment]
if you can post a minimal example, I'll take a look.

**Comment by jrowen** [comment]
Could be related to #98.  Please re-open once you have an example we can debug.
