### ISSUE TITLE
Table interactions interfere with d3.js interactions

### ISSUE THREAD

**Issue by willglanville** [jrowen/rhandsontable#108]
Hello - 

I've built a shiny app which includes a d3 visualisation which relies on interactions such as "mouseenter".

One of the data inputs on the page uses rHandsOnTable. When the rHandsOnTable is interacted with, it disables the interactions on the d3 visualisation.

Has anybody experienced a similar issue or able to suggest a workaround?

Thanks,

Will

**Comment by jrowen** [comment]
if you can post a minimal example, I'll take a look.

**Comment by jrowen** [comment]
Please re-open once you have an example we can debug.
