### ISSUE TITLE
Formatting a column using hot_col renderer breaks auto column width

### ISSUE THREAD

**Issue by lvandersypen** [jrowen/rhandsontable#109]
I want to use custom background colours for some columns, but when I do this using the ```renderer``` parameter in ```hot_col``` the auto column width stops working, the text is wrapped and the column width gets fixed.

You can replicate the issue by running the code below.  As you can see, column "A" is correctly shown in full across the screen, which is what I want, and if you change the text in that column it dynamically changes the width.  However, columns "B" and "C" are wrapped, which is incorrect, and if you change the text in those columns the width doesn't change at all.

```R
library(rhandsontable)
library(shiny)

server <- function(input, output, session) {
  output$table <- renderRHandsontable({
    tbl = input$table
    if(!is.null(tbl)){
      df <- hot_to_r(tbl)
    } else {
      df = data.frame(matrix(rep(c("This is some long text.This is some long text.This is some long text.This is some long text.This is some long text."),3), ncol = 3), stringsAsFactors = FALSE)
      colnames(df) <- c(LETTERS[1:3])
    }
    rhandsontable(df, rowHeaders = NULL) %>%
      hot_col("B", renderer = "function(instance, td, row, col, prop, value, cellProperties) {
              Handsontable.renderers.TextRenderer.apply(this, arguments);
              td.style.background = 'lightgreen';
      }") %>%
      hot_col("C", renderer = "function(instance, td, row, col, prop, value, cellProperties) {
              Handsontable.TextCell.renderer.apply(this, arguments);
              td.style.background = 'lightblue';
      }")
  })
}


ui <- shinyUI(
  fluidPage(
    title = "Test", 
    column(12, 
           wellPanel(width="100%", rHandsontableOutput("table")
           )
    )
  )
)

shinyApp(ui = ui, server = server)
```

**Comment by lvandersypen** [comment]
I should also add that I tried adding ```td.style.width = 'auto';``` to the ```renderer``` parameter, but the columns still remained of fixed width.

**Comment by jrowen** [comment]
I just pushed an update to the dev version that should fix this.  Please let me know if it's still an issue.  Thanks for reporting.

**Comment by lvandersypen** [comment]
This has resolved my issue. :simple_smile: Thanks.

**Comment by jrowen** [comment]
Great.  We'll try to get this on CRAN soon.
