### ISSUE TITLE
 FR: hot_validate_numeric: one per each columns or settable for a range of cols?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [jrowen/rhandsontable#11]
I have been experimenting with  hot_validate_numeric and it seems to me that needs to be specified once for each column.

In other words a vector of col names or col indexes does not seem to work as in
```R
rhandsontable(df_, readOnly = FALSE, rowHeaders= NULL, useTypes= TRUE) %>%
  hot_table(highlightCol = TRUE, highlightRow = TRUE) %>%
  hot_validate_numeric(hot = ncols, min = 0, max = 100, allowInvalid = FALSE)
```

As this is not very idiomatic in R (e.g. the imperative to vectorise!), would it be possible to introduce this feature?

**Comment by jrowen** [comment]
Another good catch.  I'll add a fix to the jsonlite branch.
