### ISSUE TITLE
0.3.3 breaking change

### ISSUE THREAD

**Issue by juancentro** [jrowen/rhandsontable#110]
Hi, could you explain more of the 0.3.3 breaking change? I just installed it and it broke my shiny app on startup. It seems that the table wasnt correctly initialized. I want to understand more so I can solve the issue and be compatible with the latest release.

Thanks!

**Comment by jrowen** [comment]
The widget should now initialize the input right when the page loads.
Previously, the input would not initialize until the table was changed.
The new behavior should be closer to a typical shiny input and eliminate
the need to use reactiveValues to store the table data.

**Comment by juancentro** [comment]
Yes, I remember having to put some workarounds to the fact that the table
wasnt quite ok until I made some change (ie, it didnt react to other inputs
for example). Ok, I will try to have the new release working in a new
branch. So basically we should avoid storing the table in a reactiveValues
now?

**Comment by jrowen** [comment]
The reactiveValues step should no longer be necessary.

**Comment by jrowen** [comment]
Please re-open if you still have questions.
