### ISSUE TITLE
Assigning table values from an uploaded file. To plot these new values you must first click into the table.

### ISSUE THREAD

**Issue by pelhambarron** [jrowen/rhandsontable#111]
Hi,

I am experiencing an issue whereby if I upload a data file and assign values from it to the entries in a handsontable, it seems that I must click into the table and hit enter before it recognizes those new values as the table entries. Is there a way so that clicking into the table is not necessary?
Example code here:
http://stackoverflow.com/questions/39454157/how-can-i-update-plot-from-rhandsontable-with-uploaded-data-without-clicking-in

Thanks

**Comment by bklingen** [comment]
I experience the same behavior in a related short app (see below). You can provide custom column names and the rhandsontable in the ui displays them immediately. However, I need to click in the table and press return to get the corresponding printout showing the updated table. 
It seems that hot_to_r is somehow lagging behind, i.e., e.g., is not reactive to changes in the columnames.

ui.r:

```r
library("shiny")
library("rhandsontable")
shinyUI(
fluidPage(
  sidebarLayout(
    sidebarPanel(
      textInput("colnames", "Enter Column Names (separated by comma)", value="", placeholder = "A, B"),
      h5(tags$b("Enter counts for table:")),
      rHandsontableOutput("hot")
    ),
    mainPanel(
      tableOutput("printhot")
    ) 
  )
)
)
```

server.r:

```r
shinyServer(function(input, output, session) {
  output$hot <- renderRHandsontable({
    coln <- unlist(strsplit(input$colnames,","))
    if(length(coln)<1) {
      coln=c("A","B")
      DF <- matrix(0,2,2)
    } else DF <- matrix(0,2,ncol=length(coln))
    colnames(DF) <- coln
    mytab <- rhandsontable(DF)
  })

  output$printhot <-renderTable({
  if(is.null(input$hot)) return("NA") else return(hot_to_r(input$hot))
  })
})
```

**Comment by jrowen** [comment]
The table is built as a shiny output, but we try to mimic input behavior by a using table events to call `Shiny.onInputChange`.  In this case, the `input$hot` will not change until a table change is detected (you can see the current logic [here](https://github.com/jrowen/rhandsontable/blob/master/inst/htmlwidgets/rhandsontable.js#L83-L110)).  This is a great example of where we can look to improve the logic, though.

**Comment by pelhambarron** [comment]
Thanks for clarifying. As the package stands now, I was able to resolve my issue using reactive observers.
@bklingen I'm sure this could be readily adapted for your app as well. http://stackoverflow.com/a/39512660/6822831

**Comment by jrowen** [comment]
I just pushed a new branch to test some different approaches.  Feel free to give it a try and let me know how it works out.
```
devtools::install_github("jrowen/rhandsontable", ref = "input_enh")
```

**Comment by bklingen** [comment]
I can confirm that using this new branch the app I posted above works as expected (i.e., the table displayed in the output matches that in the ui). Thanks!

![image](https://cloud.githubusercontent.com/assets/4784206/18568639/20ad4004-7b6c-11e6-80ee-796f4dd0fecc.png)

**Comment by pelhambarron** [comment]
Yep, the new branch solved my problem. Thanks!

**Comment by jrowen** [comment]
Please re-open if you're still running into issues.
