### ISSUE TITLE
"ERROR: invalid 'row.names' length" when adding and then deleting rows

### ISSUE THREAD

**Issue by FosseyFund** [jrowen/rhandsontable#112]
Hi, 

When I right-click to insert 3 new rows (or more) consecutively between the 2nd and 3rd row of my handsontable, and then remove those three rows alltogether, my Shiny app returns **error: invalid 'row.names' length**.
Now if I insert three new rows between the 3rd and 4th row and then remove them, it works fine. But if I insert 4 rows instead of 3 and remove them it'll crash again.
Seems to be a row indexing problem...
See sample code below.
Thanks !

```
library(shiny)
library(rhandsontable)

ui = shinyUI(fluidPage(

  titlePanel("Handsontable"),

  sidebarLayout(
    sidebarPanel(
      helpText("Handsontable demo. Try to add 3 empty rows consecutively between rows 1 and 2. Then select these 3 added rows and remove them. Error message: 'invalid 'row.names' length'")
    ),
    mainPanel(
      rHandsontableOutput("hot")
    )
  )
))

server = function(input, output) {
  output$hot <- renderRHandsontable({
    if (is.null(input$hot)) {
      DF = data.frame(val = as.character(1:10),  nm = LETTERS[1:10],
                      stringsAsFactors = F)
    } else {
      DF = hot_to_r(input$hot)
    }
    rhandsontable(DF, useTypes = FALSE) %>%
    hot_col(col = 1, readOnly = FALSE)
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by GilesPercy** [comment]
This is related to the updating of rownames on adding or deleting rows.

If you look in misc.R at the toR function there are a few lines of code that look suspect. On line 53

inds = seq(changes$ind + 1, 1, length.out = changes$ct)
rowHeaders = rowHeaders[-inds]

The second argument of seq is to=1 which doesn't make much sense to me if we have changes$ind = 0 because then we just get a sequence of 1s. Similarly the sequence in the column headers looks incorrect. One workaround is to copy thie toR function into your code and comment out line line 99 which causes the error since rownames get out of sync. If you don't use row headers then things appear to work.

It looks like these changes are related to broken row name functionality in the previous version where row names were replaced by numbers. Just fixing the sequences doesn't cure the problem though because repeated attempts to remove rows cause the row numbering to get messed up and I haven't figured out why.

It would be good to get a fix to this because it currently means you cannot use the CRAN version to edit and change the size of data frames. 

Keep up the great work
GP

**Comment by jrowen** [comment]
Can you try the latest dev version?  I'm not receiving an error when using.

**Comment by FosseyFund** [comment]
Yes, I still get the error when I use v3.3.1 instead of the CRAN version. I did some further testing though, and I realized that:
- if you run the above script from Rstudio and then click "open in browser" from the Rstudio shiny window, you will NOT get the error. Weird...
- if you run the script from R directly (and not from Rstudio), then you will get the error.
Hope this helps...

**Comment by GilesPercy** [comment]
I tried with the latest dev version and the latest R and shiny.

The above example crashes for me if you delete the top half of the rows in the table by selecting then using the context menu. Deleting over half the rows from the first row seems to trigger the indexing problem. Single rows work ok.

Regards  GP

**Comment by jrowen** [comment]
I made a slight update to the row name logic but am still unable to reproduce the crash.  If you are still running into issues, please send me your session details.  Thanks.
```
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux stretch/sid

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rhandsontable_0.3.3.1 shiny_0.13.2         

loaded via a namespace (and not attached):
 [1] htmlwidgets_0.6 magrittr_1.5    R6_2.1.2        tools_3.3.1     htmltools_0.3.5 yaml_2.1.13     Rcpp_0.12.6    
 [8] jsonlite_1.0    digest_0.6.9    xtable_1.8-2    httpuv_1.3.3    mime_0.5 
```

**Comment by GilesPercy** [comment]
The dev version now works for me when I add and delete rows.
Thanks GP

**Comment by FosseyFund** [comment]
I see you use linux. I'm a Mac (el capitan) user, maybe that why you were not able to reprodiuce the error. 
Anyway, the development version works now for me as well. Thanks much!

**Comment by jrowen** [comment]
Please re-open if this issue persists.

**Comment by SushmithaMiriyam** [comment]
Hi,

The issue still persists. Below is my sessionInfo and simple code where I try to read rhandsontable using hot_to_t and display it. It gives me the error: invalid 'row.names' length", when I insert new row from the context menu and edit 2 or three rows. Please let me know if its possible to reopen the issue. thanks in advance.
Session Info:
`R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rhandsontable_0.3.4   splitstackshape_1.4.2 data.table_1.10.4     DT_0.2               
 [5] tidyr_0.6.2           dplyr_0.5.0           rvaultclient_1.0      shiny_1.0.3          
 [9] RPostgreSQL_0.4-1     DBI_0.5-1            

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10.2  digest_0.6.12   assertthat_0.1  mime_0.5        R6_2.2.1        jsonlite_1.4   
 [7] xtable_1.8-2    magrittr_1.5    stringi_1.1.5   lazyeval_0.2.0  tools_3.3.1     htmlwidgets_0.8
[13] yaml_2.1.14     httpuv_1.3.3    htmltools_0.3.6 tibble_1.3.0   `

Sample code:
`
library(rhandsontable)
library(DT)
library(shiny)

ui <- fluidPage(
  br(),
  rHandsontableOutput('demTb'),
  br(),
  actionButton("submit","click to see the output"),
  br(),
  dataTableOutput('dtable')
)

server <- function(session, input, output) {
  output$demTb <- renderRHandsontable({
    rhandsontable(head(mtcars,10),selectCallback = TRUE, 
                  fillHandle = list(direction='vertical', autoInsertRow=FALSE))
  })
  
  editedtable<-eventReactive(input$submit,{
    datatable<-hot_to_r(input$demTb)
    
  })
  
  observeEvent(input$submit,{
    output$dtable <- renderDataTable({
      datatable(editedtable())
    })
  })
}


shinyApp(ui, server)`

**Comment by StevenLShafer** [comment]
This issue still exists for me. I can generate "Warning: Error in .rowNamesDF<-: invalid 'row.names' length" when I start deleting many rows.
