### ISSUE TITLE
input$hot not updating quick enough

### ISSUE THREAD

**Issue by daniel-matthews** [jrowen/rhandsontable#113]
Hi,

I'm aware that this is something of a known issue but I would be extremely grateful if you could provide a bit more clarity. I have an rhandsontable that takes data from an excel file loaded in via the fundSelect input. It then goes on to do some calculations that rely on other reactive inputs. I have been trying to copy the example from another issue to solve the fact that I cannot set input$hot to NULL when I load up a new excel file. The code fires more than once when reloading.. sending it down both paths of my if statement. The second time `hot_to_r(input$hot)` fires it reloads the previous data, not the new data that has just been processed. 

```
output$hot <- renderRHandsontable({

if (!is.null(input$hot) && portfolio_active == input$fundSelect  ) {
      showNotification("Recalculating",duration = 30)
      rhandson_existing_data <<- hot_to_r(input$hot)
      existingColnames <- colnames(rhandson_existing_data)
      excelInput <- values[["inEx"]] #Reactive
      excelInputnames <- colnames(excelInput)
      excelInputUnchangedNames <- excelInputnames[!excelInputnames %in%  existingColnames]
      excelInputUnchanged <<- excelInput[, excelInputUnchangedNames]
      DF <- cbind(excelInputUnchanged, rhandson_existing_data)
      write.csv(DF, "test.csv")
      showNotification("Data Exists",duration = 30)
} else {
      DF <<- values[["inEx"]] #Reactive
      portfolio_active <<- input$fundSelect
      showNotification("Loading Fresh Data",duration = 30)
}

#There is some code here that manipulates DF once loaded. This bit makes use of one other reactive value in a calculation, and sets two others for use elsewhere

#function to do all the rhandson formatting, nothing reactive in it. 
RendertableDM(tabletoRender)  
 
})
```

**Comment by jrowen** [comment]
I think this is related to #111.  If you're up for it, give the dev branch a try and let me know it things work better.
```
devtools::install_github("jrowen/rhandsontable", ref = "input_enh")
```

**Comment by daniel-matthews** [comment]
The problem appears to be resolved. Thanks
