### ISSUE TITLE
Converting data.tables to rhandsontable does not work if additional s3 classes are present

### ISSUE THREAD

**Issue by s-fleck** [jrowen/rhandsontable#115]
There is a small error that occurs when you have `data.table`s with additional s3 classes (it does not occur for `data.frame`s)

```
x <- data.table::data.table(a = 'a','b','c')

# Works...
rhandsontable(x)

# Does not work
class(x) <- union('foobar', class(x))
rhandsontable(x)

# Works again
y <- as.data.table(x)
rhandsontable(x)
```

Error message:

```
Error in dimnames.data.table(x) : 
  data.table inherits from data.frame (from v1.5) but this data.table does not. Has it been created manually (e.g. by using 'structure' rather than 'data.table') or saved to disk using a prior version of data.table? The correct class is c('data.table','data.frame').
```

I think think adding something like `if('data.table' %in% class(data)) as.data.table(data)` will get rid of this problem. This is more of a workaround than a fix though.

**Comment by jrowen** [comment]
It looks like the error is coming from the `rownames` function.  I could add a class check to confirm that the input is either `matrix`, `data.frame` or `c('data.table','data.frame')`.  Would this work for your use case?

**Comment by jrowen** [comment]
We implemented a quick fix for this issue.  Thanks for reporting.
