### ISSUE TITLE
providing background color for selected rows instead of columns

### ISSUE THREAD

**Issue by bklingen** [jrowen/rhandsontable#116]
Using

```
hot_col(c(1,3), renderer = "function(instance, td, row, col, prop, value, cellProperties) {
  Handsontable.TextCell.renderer.apply(this, arguments);
  td.style.background = 'lightblue';
}")
```

one can define the background color for selected columns, here columns 1 and 3.

Is it possible to do the same for selected rows?

The following would highlight only the 4th row (counting seems to start at zero):

```
hot_cols(renderer = "function(instance, td, row, col, prop, value, cellProperties) {
  Handsontable.TextCell.renderer.apply(this, arguments);
  if(row==3) td.style.background = 'lightblue';
 }")
```

E.g., 

![image](https://cloud.githubusercontent.com/assets/4784206/18730029/326d3d98-8022-11e6-97cd-e78289befd9a.png)

But I'm looking for highlighting selected rows, where similar to above, I can provide a whole vector of row indices. So, something like:

```
hot_row(c(1,3), renderer = "function(instance, td, row, col, prop, value, cellProperties) {
  Handsontable.TextCell.renderer.apply(this, arguments);
  td.style.background = 'lightblue';
}")
```

with the vector of row indices coming from somewhere else in the code.

**Comment by jrowen** [comment]
This should be possible using a for loop to go thorough the vector,
updating columns.  When you're dealing with javascript, you're correct,
indexing will start at 0.

**Comment by bklingen** [comment]
Thank you! I clearly lack the understanding to pull this off.
This works:

    rhandsontable(data.frame(ID=1:5,var1=rnorm(5), var2=letters[1:5])) %>%
      hot_cols(renderer = "function(instance, td, row, col, prop, value, cellProperties) {
      Handsontable.TextCell.renderer.apply(this, arguments);
        if (row==1 || row==3 || row==4) td.style.background = 'lightblue';
      }
    ")

![image](https://cloud.githubusercontent.com/assets/4784206/18735022/49a02a18-8048-11e6-9683-d27862c5b754.png)

Neither of the following two work,  selecting the wrong rows:

    rhandsontable(data.frame(ID=1:5,var1=rnorm(5), var2=letters[1:5])) %>%
      hot_cols(renderer = "function(instance, td, row, col, prop, value, cellProperties) {
      Handsontable.TextCell.renderer.apply(this, arguments);
        for (i in [1, 3, 4]) { if (row==i) td.style.background = 'lightblue';}
      }
    ")


    rhandsontable(data.frame(ID=1:5,var1=rnorm(5), var2=letters[1:5])) %>%
      hot_cols(renderer = "function(instance, td, row, col, prop, value, cellProperties) {
      Handsontable.TextCell.renderer.apply(this, arguments);
        if (row in [1, 3, 4]) td.style.background = 'lightblue';
      }
    ")


![image](https://cloud.githubusercontent.com/assets/4784206/18735031/6a4cd220-8048-11e6-8b8f-7d320271bd10.png)

Ideally, I want something like the below, but it is clear that this will not work because the renderer function can't see myindex:

    myindex <- c(1, 3, 4)
    rhandsontable(data.frame(ID=1:5,var1=rnorm(5), var2=letters[1:5])) %>%
      hot_cols(renderer = "function(instance, td, row, col, prop, value, cellProperties) {
      Handsontable.TextCell.renderer.apply(this, arguments);
        if (row in myindex) td.style.background = 'lightblue';}
      }
    ")

It might be a good idea to post on Stackoverflow to see if someone can help.

**Comment by jrowen** [comment]
How do you want to populate your index?  Via R or JavaScript logic?

**Comment by jrowen** [comment]
I made a small update that should allow the logic below to work.
```
myindex <- c(1, 3, 4)
rhandsontable(data.frame(ID=1:5,var1=rnorm(5), var2=letters[1:5]), myindex = myindex) %>%
  hot_cols(renderer = "function(instance, td, row, col, prop, value, cellProperties) {
    Handsontable.TextCell.renderer.apply(this, arguments);
    tbl = this.HTMLWidgets.widgets[0]
    if (tbl.params.myindex.includes(row)) td.style.background = 'lightblue';
  }
")
```
If you plan to use this logic in a shiny app or with more than one widget on the page, you'll want to use more specific logic for finding the widget.

**Comment by jrowen** [comment]
I also added some new documentation (only works for the dev version right now): http://jrowen.github.io/rhandsontable/#custom_renderer_using_r

I think this could be a pretty useful feature, so thanks for persisting with the issue.

**Comment by bklingen** [comment]
Thanks for the update. I tried your code with the dev version from the documentation in R and it works fine. (In R Studio, you have to view the output in a separate browser window, the Viewer will not display it.)

I tried to wrap this in a basic shiny app, but I'm not sure where to put the widget search function (the code that starts with HTMLWidgets.widgets.filter(function(widget)): 

ui.r:

    library("shiny")
    library("rhandsontable") #dev version 0.3.3.1

    shinyUI(
      fluidPage(
        numericInput("rowhighlight", "Select Row to Highlight", value=1),
        rHandsontableOutput("hot")
     )
    )

server.r:

    mydata <- data.frame(ID=1:5, Var1=rnorm(5), Var2=letters[1:5])
    shinyServer(function(input, output, session) {
      output$hot <- renderRHandsontable({
         rhandsontable(mydata, row_highlight = input$rowhighlight) %>%
         hot_cols(renderer = "
         function(instance, td, row, col, prop, value, cellProperties) {
             Handsontable.TextCell.renderer.apply(this, arguments);
             
             tbl = this.HTMLWidgets.widgets[0]
             
             hrows = tbl.params.row_highlight
             hrows = hrows instanceof Array ? hrows : [hrows] 

             if (hrows.includes(row)) {
             td.style.background = 'lightblue';
             }
             
             return td;
        }")
      })
    })

**Comment by jrowen** [comment]
You would need to replace the `tbl = this.HTMLWidgets.widgets[0]` line.  It may work as is if you only have one htmlwidget in your app.

**Comment by bklingen** [comment]
Unfortunately, it doesn't work: I ran the following server.r, with the same ui.r as above:

server.r:

```{r}
mydata <- data.frame(ID=1:5, Var1=rnorm(5), Var2=letters[1:5])
shinyServer(function(input, output, session) {
  output$hot <- renderRHandsontable({
    rhandsontable(mydata, row_highlight = input$rowhighlight) %>%
      hot_cols(renderer = "
               function(instance, td, row, col, prop, value, cellProperties) {
               Handsontable.TextCell.renderer.apply(this, arguments);
               
               HTMLWidgets.widgets.filter(function(widget) {return widget.name === 'hot'})[0];
               
               hrows = tbl.params.row_highlight
               hrows = hrows instanceof Array ? hrows : [hrows] 
               
               if (hrows.includes(row)) {
               td.style.background = 'lightblue';
               }
               
               return td;
               }")
  })
})
```
 
The app doesn't throw an error message, but a table is never displayed.

**Comment by theyuish** [comment]
Running the same issue as @bklingen... Was trying to have a conditional colour for whole row based on if a date is less than system date? Any alternative?

**Comment by jrowen** [comment]
Here's a shiny example that should get you started.

```
library(rhandsontable)
library(shiny)

app <- shinyApp(
  ui = fluidPage(
    numericInput("myindex", "Highlight", min = 0, max = 9, value = 1),
    rHandsontableOutput("hot", width = 350)
  ),
  server = function(input, output) {
    data = reactive({
      if (!is.null(input$hot)) {
        DF = hot_to_r(input$hot)
      } else {
        DF = data.frame(val = 1:10, bool = TRUE, nm = LETTERS[1:10],
                        dt = seq(from = Sys.Date(), by = "days", length.out = 10),
                        stringsAsFactors = F)
      }
      DF
    })

    output$hot <- renderRHandsontable({
      DF = data()
      myindex = input$myindex
      if (!is.null(DF)) {
        rhandsontable(DF, myindex = myindex) %>%
          hot_cols(renderer = "function(instance, td, row, col, prop, value, cellProperties) {
            Handsontable.TextCell.renderer.apply(this, arguments);
            if (instance.params && instance.params.myindex == row) td.style.background = 'lightblue';
          }
        ")
      }
    })
  }
)

runApp(app)
```

**Comment by bklingen** [comment]
Thank you, this works beautifully for selecting a single row. I even figured out how to select multiple rows, but am not sure if this is the most efficient code:

![image](https://cloud.githubusercontent.com/assets/4784206/20034713/3dda1828-a39e-11e6-84c9-ec5207d28c9a.png)

```{r}
library(rhandsontable)
library(shiny)

app <- shinyApp(
ui = fluidPage(
  sliderInput("myindex", "Highlight", min = 1, max = 10, value = c(3,5)),
  rHandsontableOutput("hot", width = 350)
),
server = function(input, output) {
  data = reactive({
    if (!is.null(input$hot)) {
      DF = hot_to_r(input$hot)
    } else {
      DF = data.frame(val = 1:10, bool = TRUE, nm = LETTERS[1:10],
                      dt = seq(from = Sys.Date(), by = "days", length.out = 10),
                      stringsAsFactors = F)
    }
    DF
  })
    
  output$hot <- renderRHandsontable({
    DF = data()
    myindex = seq(input$myindex[1], input$myindex[2]) - 1
    if (!is.null(DF)) {
      rhandsontable(DF, myindex = myindex) %>%
        hot_cols(renderer = "function(instance, td, row, col, prop, value, cellProperties) {
          Handsontable.TextCell.renderer.apply(this, arguments);
          if (instance.params) {
            hrows = instance.params.myindex
            hrows = hrows instanceof Array ? hrows : [hrows] 
          }
          if (instance.params && hrows.includes(row)) td.style.background = 'lightblue';
        }
        ")
    }
  })
}
)

runApp(app)
```

**Comment by jrowen** [comment]
I'm glad this is now working.  Please re-open if you run into any additional issues.

**Comment by gracezhou0501** [comment]
@jrowen 
Your shiny example commented on Nov.2, 2016 seems not working with new version R 3.4.3 (Kite-Eating Tree). Could you please give me some hints? Appreciate!

**Comment by bklingen** [comment]
In all the examples given in #116, you need to replace ``Handsontable.TextCell.renderer.apply(this, arguments);`` with ``Handsontable.renderers.TextRenderer.apply(this, arguments);`` per a change in the underlying handsontable package.

**Comment by gracezhou0501** [comment]
Hello @bklingen ,
Thank you very much! It works now! ^_^

**Comment by DillonHammill** [comment]
@jrowen, would it be possible to allow this when `useTypes = FALSE`? I need this so that the user can add columns, but for some reason it interferes with custom colour rendering for rows...
