### ISSUE TITLE
Problem with rhandsontable_datafile example... some code missing I think.

### ISSUE THREAD

**Issue by marinosr** [jrowen/rhandsontable#117]
Hi all,

First of all, great looking package! Very excited to get it up and running.

I was trying to run the  rhandsontable_datafile example (from the github master) , but I kept getting an error:

> Error: could not find function "setHot"

Reading online, I stumbled upon what may have been an older version of the file, and there was two lines of code at the top of shinyServer in that file that are missing from the current version:

```
  values = list()
  setHot = function(x) values[["hot"]] <<- x
```

I put these lines in and the example works now. Just thought you'd like to know about the issue. I'm not good enough at using github to edit the code myself and make a pull request.

**Comment by marinosr** [comment]
... and actually this example won't work for me when that above code is inserted to write out changes to the CSV. I get the table to load now and I can make changes, but the changes are never saved. There's no error message returned in the R console.

**Comment by marinosr** [comment]
... but if I try to use the save button functionality, I get this error returned: 

> > Warning: Error in data.frame: arguments imply differing number of rows: 1, 0
> Stack trace (innermost first):
>     72: data.frame
>     71: eval
>     70: eval
>     69: as.data.frame.list
>     68: as.data.frame
>     67: data.frame
>     66: eval
>     65: eval
>     64: as.data.frame.list
>     63: as.data.frame
>     62: data.frame
>     61: write.table
>     60: eval
>     59: eval
>     58: eval.parent
>     57: write.csv
>     56: observerFunc [/home/marinosr/rhandsontable/inst/examples/rhandsontable_datafile/server.R#14]
>      1: runApp

**Comment by jrowen** [comment]
I removed the `setHot` call, sorry about that.

**Comment by jrowen** [comment]
Please re-open if you're still running into issues.

**Comment by sulaxd** [comment]
It's still can't save. Because the "hot" from `hot = isolate(input$hot)` is a list.

> Listening on http://127.0.0.1:4324
Warning: Error in data.frame: arguments imply differing number of rows: 1, 0
Stack trace (innermost first):
    82: data.frame
    81: eval
    80: eval
    79: as.data.frame.list
    78: as.data.frame
    77: data.frame
    76: eval
    75: eval
    74: as.data.frame.list
    73: as.data.frame
    72: data.frame
    71: eval
    70: eval
    69: as.data.frame.list
    68: as.data.frame
    67: data.frame
    66: eval
    65: eval
    64: as.data.frame.list
    63: as.data.frame
    62: data.frame
    61: write.table
    60: eval
    59: eval
    58: eval.parent
    57: write.csv
    56: observerFunc [/Users/Andrew/Downloads/rhandsontable/inst/examples/rhandsontable_datafile/server.R#12]
     1: runApp
ERROR: [on_request_read] connection reset by peer
