### ISSUE TITLE
Rendering custom HTML in header

### ISSUE THREAD

**Issue by fkotey** [jrowen/rhandsontable#119]
I want to know if it is possible to render custom HTML in header of rhandsontable. I want to replicate the example changing cell type from a dropdown menu in cell header which can be found [here](https://docs.handsontable.com/0.26.1/demo-custom-renderers.html).

**Comment by jrowen** [comment]
This should be possible.
```
DF = data.frame(val = 1:10,
                bool = TRUE)

func = "function (col) {
  switch (col) {
    case 0:
      return '<b>Bold</b> and <em>Beautiful</em>';

    case 1:
      return '<em>Beautiful</em> and <b>Bold</b>';
  }
}"
rhandsontable(DF, colHeaders = htmlwidgets::JS(func))
```

**Comment by jrowen** [comment]
Please re-open if you still have questions
