### ISSUE TITLE
How to use minSpareRows option

### ISSUE THREAD

**Issue by jpmarindiaz** [jrowen/rhandsontable#12]
Hi 
I'd love to use the minSpareRows: 1 option as in the first example in http://handsontable.com/ but haven't figured out how to do it with rhandsontable.
How can I get it to work?
Best

```
var
  data = [
    ['', 'Maserati', 'Mazda', 'Mercedes', 'Mini', 'Mitsubishi'],
    ['2009', 0, 2941, 4303, 354, 5814],
    ['2010', 3, 2905, 2867, 412, 5284],
    ['2011', 4, 2517, 4822, 552, 6127],
    ['2012', 2, 2422, 5399, 776, 4151]
  ],
  container = document.getElementById('example'),
  hot;

hot = new Handsontable(container, {
  data: data,
  minSpareRows: 1,
  colHeaders: true,
  contextMenu: true
});
```

**Comment by jrowen** [comment]
I just pushed an update that should allow you to pass additional parameters to the table constructor.  Something like this should now work.  
```
rhandsontable(DF) %>%
  hot_table(minSpareRows = 1)
```

**Comment by jpmarindiaz** [comment]
Great! thanks so much

**Comment by jpmarindiaz** [comment]
@jrowen the examples for shiny apps do not seem to be working anymore.
I am running https://github.com/jrowen/rhandsontable/blob/master/inst/examples/shiny.R
But the hot table is not rendered.
Any ideas?

**Comment by jrowen** [comment]
Check your shiny version, as things seem to be working for me with >=0.11.1.9003.  The update to jsonlite requires a later version of shiny, so you will need to install the dev version of shiny if it's not already available.  I've also added a Suggests section to the DESCRIPTION file with version info for shiny.

If the plot still doesn't render, right click and choose Inspect.  The Javascript console will likely list an error that will help with debugging the issue.

**Comment by jpmarindiaz** [comment]
Yep, using shiny version 0.11.1.9004, it is working now. Thanks!

**Comment by jpmarindiaz** [comment]
When I try to use the new option `minSpareRows = 1` in a shiny app I get the following error.
```
Error in seq_len(nrow(out)) : 
  argument must be coercible to non-negative integer
```

I tried it with your shiny example:

```
library(shiny)
library(rhandsontable)

ui = shinyUI(fluidPage(
  
  titlePanel("Handsontable"),
  
  sidebarLayout(
    sidebarPanel(
      helpText("Handsontable demo output. Column add/delete does work ",
               "for tables with defined column properties, including type."),
      radioButtons("useType", "Use Data Types", c("TRUE", "FALSE"))
    ),
    mainPanel(
      rHandsontableOutput("hot")
    )
  )
))

server = function(input, output) {
  output$hot <- renderRHandsontable({
    if (is.null(input$hot)) {
      DF = data.frame(val = 1:10, bool = TRUE, nm = LETTERS[1:10],
                      dt = seq(from = Sys.Date(), by = "days", length.out = 10),
                      stringsAsFactors = F)
    } else {
      DF = hot_to_r(input$hot)
    }
    h <- rhandsontable(DF, useTypes = as.logical(input$useType))
    h <- hot_table(h, minSpareRows = 1)
    h
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by jrowen** [comment]
I believe this is related to #12.  The `minSpareRows` parameter appends new rows at the end of the table, which fires a table change and sends data back to shiny along with the code for a row change event.  This test highlighted so additional work that we'll have to do to accommodate the htmlwidgets move to jsonlite.  Thanks for re-opening.

**Comment by jrowen** [comment]
Adding `minSpareRows` in shiny can create an endless update loop.  The spare rows generate a row change event that causes shiny to react as if the input has changed, run the server logic and send the dataset back to the client.  The current implementation reloads the table each time it is send to the client, so handonstable will see the dataset with a blank ending row as new and try to append another spare row to the end.

One possible solution would be to add a check to your shiny script to not return data to the client if it matches a previously cached dataset.

**Comment by jrowen** [comment]
I'm going to close this, as you should now be able to use the `minSpareRows` parameter.  One warning, the current shiny examples will go into an endless loop if this parameter is added without additional changes (see earlier comment).

**Comment by mattbk** [comment]
> One possible solution would be to add a check to your shiny script to not return data to the client if it matches a previously cached dataset.

Is there an example of how to do this?

**Comment by jrowen** [comment]
You might be able to use `reactiveValues` to store the dataset after each update.  There have been some recent updates to the package (not on CRAN yet), so I'd suggest first testing with the dev version before implementing an caching logic.
