### ISSUE TITLE
Dropdown menu dont show correctly with cells in the bottom of the table

### ISSUE THREAD

**Issue by KrysD** [jrowen/rhandsontable#120]
Is it possible to specify a maximum height for the dropdown menu of cells ? 

Because when you have many possibilities in the dropdown menu it's dosent render on the bottom of the table. 
I put two picture (from the cran html page examples) to show you the problem. The first is when you want to choose from the cell at the top of table and the second is at the bottom of the table
![table1cell](https://cloud.githubusercontent.com/assets/13766508/19189368/f5162162-8c97-11e6-8710-75c6e68b1896.PNG)
![tableprob](https://cloud.githubusercontent.com/assets/13766508/19189371/f7a4a746-8c97-11e6-9198-86434c21cb5a.PNG)

You can see that the dropdown menu is not render after the same position.

**Comment by jrowen** [comment]
This is likely an issue with the z-index on the dropdown and may be [an issue](https://github.com/handsontable/handsontable/issues/3435) with handsontable.  I'll see if there's anything we can do in rhandsontable too.

**Comment by KrysD** [comment]
Ok thx.
I manage to 'solve' the problem by adding a responsive table height depending on the number of choices in the dropdown menu, but if i have widgets just under the table it's not realy beautiful .

**Comment by jrowen** [comment]
You could also try using `overflow = "visible"` with an appropriate height and setting.

**Comment by jrowen** [comment]
Please re-open if you're still running into an issue.
