### ISSUE TITLE
Mismatching of lines in the table and row number duplicate (rhandsontable)

### ISSUE THREAD

**Issue by demydd** [jrowen/rhandsontable#121]
Hi
I have found some side effects: mismatching of lines and row number duplication (see the image attached). Row number duplication see in the row 20.

![image](https://cloud.githubusercontent.com/assets/12771841/19967674/0a76bbaa-a1da-11e6-8c94-21b42f8bbec5.png)

**Comment by jrowen** [comment]
Could you please verify you're using the latest version?  Of you're still running into an issue, could  you please provide a minimally reproducable example?  Thanks.

**Comment by demydd** [comment]
I have updated the package from 0.3.3 to 0.3.4 version. 
Everything is ok - you can close the issue.
