### ISSUE TITLE
Controlling the format of cell with regex and disable adding row by drag down

### ISSUE THREAD

**Issue by william-denault** [jrowen/rhandsontable#123]
Dear  Jrowen

I like a lot your package however i only know R as a comuting language, so i think that my question could be solved with js. But i would like to know if there is simple possibilities to manage it in R
I have currently two issues:

1)The first one is to disable the the possibility to generate new by dragging down the cells in a Shiny (cf png file).
Because in the hot_context_menu by allowRowEdit=FALSE you cannot generate row by right clicking but you can still do it by dragging down the cells.

library(rhandsontable)

server <- function(input, output) {
  output$mytable <- renderRHandsontable({
    data = mtcars[mtcars$mpg> as.numeric(input$minMPG),]
    rhandsontable(data)%>%
    hot_context_menu(allowRowEdit = FALSE, allowColEdit = FALSE)
  })
}

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      numericInput("minMPG","minimum mpg",20)
    ),
    mainPanel(rHandsontableOutput("mytable"))
  )
)

shinyApp(ui = ui, server = server)

![capture](https://cloud.githubusercontent.com/assets/22315814/20010433/5eefd6b6-a2a8-11e6-9ab0-adbc1b83134b.PNG)

Is there anyway to block that option in shiny ?
nb: there is no problem with generation of new column, you can try to drag but no new column are generated.

2) The second issue is to control the cell format by using something similar to regex :
My idea here is to avoid people who will enter number in the table to write it with ","
I am figuring two possibilities
    a) automatically transform the "," into "." (and not having the switch from 2,00 to 200)
    b) Delete any number with a "," entered in the format cell

Do you have anny idea on how to manage it ?

Lastly even if you set the format as "0.00" and you enter 2.000001 the stored value is 2.000001 and not 2.00 do you know how to avoid that.

I am use tho use thing like that to control the formating :

 function(x) {
  grepl("^[0-9]+[.]([0-9]{1,2})?$", x, perl = TRUE)
}

DF <- data.frame(C1=as.numeric(rep(NA,3)), C2=as.numeric(rep(NA,3)),C3= as.numeric(rep(NA,3)),
                 stringsAsFactors = FALSE) 
rhandsontable(DF)%>%
  hot_col("C1",format="*.00")

Regards
W

**Comment by jrowen** [comment]
Try adding the parameter below to your `rhandsontable` call.
```
fillHandle = list(direction='vertical', autoInsertRow=FALSE)
```
See also http://docs.handsontable.com/0.29.0/demo-drag-down.html.

**Comment by william-denault** [comment]
Hello 

thank you for hyour proposal.
However I don't get in which argument of which function should i put the fillHandle, to block the Drag down.
I tried that but obviously it doesn't work:
DF <- data.frame(C1=as.numeric(rep(NA,3)), C2=as.numeric(rep(NA,3)),C3= as.numeric(rep(NA,3)),
 stringsAsFactors = FALSE)
 rhandsontable(DF)%>%
fillHandle = list(direction='vertical', autoInsertRow=FALSE)


I also would like to know how to block the "coma problem" which generate new decimal.
Indeed currently 2,1=21 and normally it should be 2,1=2.1
It a real problem when you are dealing with no consistent writing type.

**Comment by jrowen** [comment]
See the example below
```
rhandsontable(data.frame(A=1:10, B=rnorm(10)), 
              fillHandle = list(direction='vertical', autoInsertRow=FALSE))
```
To do regex filtering, you'll need to either build a shiny app that validates the data returned from rhandsontable or [build a custom renderer](http://jrowen.github.io/rhandsontable/#custom_renderer).

**Comment by jrowen** [comment]
Closing, but please let me know if you still have questions.
