### ISSUE TITLE
Copying and pasting into rhandsontable

### ISSUE THREAD

**Issue by bklingen** [jrowen/rhandsontable#124]
For a regular rhandsontable

rhandsontable(data.frame(Var1=1:5))

![image](https://cloud.githubusercontent.com/assets/4784206/20157542/9b0beabe-a6a3-11e6-92ab-5d83b9822c6d.png)

one can copy a column of values (with the column longer than the initial rhandsontable),

10
9
8
7
6
5
7

and paste it into the table effortlessly (i.e., by clicking in the first cell and pasting the values in):

![image](https://cloud.githubusercontent.com/assets/4784206/20157569/c2029e38-a6a3-11e6-896d-37404c97bbb1.png)

However, doing the same within shiny doesn't work:

```{r}
library(shiny)
library(rhandsontable)
myApp <- shinyApp(
ui = fluidPage(
  rHandsontableOutput("hot")
),
server = function(input, output, session) {
  output$hot <- renderRHandsontable({
    if (!is.null(input$hot)) {
      DF <- hot_to_r(input$hot)
    } else {
      DF <- data.frame(Var1=1:5)
    }
    mytab <- rhandsontable(DF, colHeaders=TRUE, rowHeaders=TRUE)
    return(mytab)
  })
}
)
runApp(myApp)
```

After pasting the values in, the following error is given:

Warning: Error in row.names<-.data.frame: invalid 'row.names' length
Stack trace (innermost first):
    84: row.names<-.data.frame
    83: row.names<-
    82: rownames<-
    81: <Anonymous>
    80: do.call
    79: hot_to_r
    78: func [#8]
    77: origRenderFunc
    76: output$hot
     1: runApp

Now, as long as the number of values pasted in is not larger than the existing numbers of rows in the rhandsontable, everything works fine. For instance, just copying and pasting the first three values works fine:

![image](https://cloud.githubusercontent.com/assets/4784206/20157785/efb0d8e4-a6a4-11e6-8600-e50db8f5c2c0.png)

I think copy and pasting (of any length column) used to work in earlier versions, but I may be wrong. It does not seem to work in versions 0.3.3 and 0.3.4.

**Comment by bklingen** [comment]
Just saw that this relates to an earlier issue, now closed: #19 Copy column larger than table

**Comment by bklingen** [comment]
With the latest push, this issue has been fixed!. Thanks! (see also #126)

**Comment by jrowen** [comment]
Great.  Thanks.
