### ISSUE TITLE
Content of new rows is returned as all NA

### ISSUE THREAD

**Issue by dansmith01** [jrowen/rhandsontable#125]
Here is some code to reproduce the issue I'm seeing:

```
library(shiny)
library(rhandsontable)

ui <- fluidPage(
  rHandsontableOutput("in.table"),
  actionButton("Update", "Update"),
  tableOutput("out.table")
)

server <- function(input, output) {
   
  output$in.table <- renderRHandsontable({
    rhandsontable(data.frame("UserID" = 1:5, "Name" = LETTERS[1:5]))
  })
  
  output$out.table <- renderTable({
    req(input$Update)
    isolate(hot_to_r(input$in.table))
  })
}

shinyApp(ui = ui, server = server)
```

Insert a new row and type in some text, then hit "Update". The data frame returned by `hot_to_r` sees the new row, but not the new content (it is all `NA`s). But then, insert another new row and hit "Update". Now the first new row appears correctly, but the second new row is all `NA`s.

rhandsontable was installed today using `devtools::install_github("jrowen/rhandsontable")`

**Comment by jrowen** [comment]
It looks like the first update of a new row is not being returned to shiny.

**Comment by AkhilNairAmey** [comment]
@dansmith01 do'u have a work around to this by any chance?

**Comment by jrowen** [comment]
I just pushed an update to the dev version that may fix this.  Please let me know how it works.  Thanks.

**Comment by AkhilNairAmey** [comment]
Perfect thanks!

**Comment by dansmith01** [comment]
Yep, all good! Thanks @jrowen
