### ISSUE TITLE
cell format changing with renderer?

### ISSUE THREAD

**Issue by bklingen** [jrowen/rhandsontable#128]
I wish to display an empty table where users can input some numerical values. One way to display blank cells is this ...

```{r}
myinit <- data.frame(rep(NA_integer_, 10), rep(NA_integer_,10))
rhandsontable(myinit, colHeaders=TRUE, rowHeaders=TRUE, height=260) %>%
  hot_cols(type="numeric")
```

![image](https://cloud.githubusercontent.com/assets/4784206/20471109/d1974b00-af7c-11e6-83e2-63a749c85186.png)

.. and one can then fill the tables with numbers.

However, when using a ``renderer`` function to render the background lighblue, all of a sudden the table is no longer displaying blank cells, but "NA's". **Is there a way so that the table will still display blank (empty) cells?**

```{r}
myinit <- data.frame(rep(NA_integer_, 10), rep(NA_integer_,10))
rhandsontable(myinit, colHeaders=TRUE, rowHeaders=TRUE, height=260) %>%
  hot_cols(type="numeric",
                renderer = "function(instance, td, row, col, prop, value, cellProperties) {
                  Handsontable.TextCell.renderer.apply(this, arguments);
                  td.style.background = 'lightblue'
                 }"
              )
```

![image](https://cloud.githubusercontent.com/assets/4784206/20471214/d16e454c-af7d-11e6-836f-67c5f889c936.png)

**Comment by jrowen** [comment]
Take a look at the [`customRenderer`](https://github.com/jrowen/rhandsontable/blob/master/inst/htmlwidgets/rhandsontable.js#L347-L359) function.  You need to add special handling for NA values.

**Comment by bklingen** [comment]
Thank you. But why would the behavior change from not showing NA values (desired) to showing NA values when just changing the background color?
Additionally, I tried to include some code from the costumRenderer function by including ``if(value==='NA') value='';`` , but to no avail:

```{r}
myinit <- data.frame(rep(NA_integer_, 10), rep(NA_integer_,10))
rhandsontable(myinit, colHeaders=TRUE, rowHeaders=TRUE, height=260) %>%
  hot_cols(type="numeric",
                renderer = "function(instance, td, row, col, prop, value, cellProperties) {
                  Handsontable.TextCell.renderer.apply(this, arguments);
                  td.style.background = 'lightblue';
                  if(value==='NA') value='';  
                 }"
    )
```

The same happens if you specify myinit as a dataframe of NA characters:
```
myinit <- data.frame(rep("NA", 10), rep("NA",10), stringsAsFactors = FALSE)
rhandsontable(myinit, colHeaders=TRUE, rowHeaders=TRUE, height=260) %>%
  hot_cols(type="numeric",
                renderer = "function(instance, td, row, col, prop, value, cellProperties) {
                  Handsontable.TextCell.renderer.apply(this, arguments);
                  td.style.background = 'lightblue';
                  if(value==='NA') value='';  
                 }"
    )
```

**Comment by bklingen** [comment]
Here is an even shorter example: Without invoking ``renderer`` NA values are displayed as blank cells:
```{r}
DF_na = data.frame(integer = c(NA, 2:4), 
                   character = c(NA, LETTERS[2:4]),
                   stringsAsFactors = FALSE)

rhandsontable(DF_na)
```

![image](https://cloud.githubusercontent.com/assets/4784206/20655442/763f68b8-b4f0-11e6-9a67-1668fc30353c.png)

But including a ``renderer`` function seems to override the costumRenderer and NA values are displayed as NA:
```{r}
DF_na = data.frame(integer = c(NA, 2:4), 
                   character = c(NA, LETTERS[2:4]),
                   stringsAsFactors = FALSE)

rhandsontable(DF_na) %>%
  hot_cols(renderer = "function(instance, td, row, col, prop, value, cellProperties) {
           Handsontable.TextCell.renderer.apply(this, arguments);
           td.style.background = 'lightblue'
           }")
```

![image](https://cloud.githubusercontent.com/assets/4784206/20655483/d04946b2-b4f0-11e6-8219-86295a33855a.png)


 Is there any way to have them still show as empty cells even if one uses a ``renderer`` function?

**Comment by jrowen** [comment]
The customRenderer function is used if a renderer function is not specified, and this custom function converts NA to empty strings.  You'll need to implement similar logic if you want the same behavior in your renderer function.

**Comment by bklingen** [comment]
Thank you for the clarification! I think I figured out what I did wrong when re-using parts of the ``costumRenderer`` function: I forgot to change the capitalized 'TD' it uses in its argument to the 'td' that is used in the renderer examples: So this works now: 

```{r}
DF_na = data.frame(integer = c('NA', 2:4), 
                   character = c('NA', LETTERS[2:4]),
                   stringsAsFactors = FALSE)

rhandsontable(DF_na) %>%
  hot_cols(renderer = "function(instance, td, row, col, prop, value, cellProperties) {
           Handsontable.TextCell.renderer.apply(this, arguments);
           td.style.background = 'lightblue';
           if (value =='NA') {
             value = '';
             Handsontable.renderers.getRenderer('text')(instance, td, row, col, prop, value, cellProperties);
           }
           }")
```
![image](https://cloud.githubusercontent.com/assets/4784206/20672236/854f3d70-b54e-11e6-9c56-8bca15ad262c.png)
