### ISSUE TITLE
Cannot remove rows in rstudio viewer using CRAN version 3.4

### ISSUE THREAD

**Issue by GilesPercy** [jrowen/rhandsontable#129]
I try rhandsontable(trees) and I cannot remove rows in the rstudio viewer. 

It seems like it is not updating the display properly. If I do an undo I get confusing output. Can anyone else see this?

My session info is below
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rhandsontable_0.3.4

loaded via a namespace (and not attached):
[1] htmlwidgets_0.7 magrittr_1.5    htmltools_0.3.5 tools_3.3.1     yaml_2.1.13     Rcpp_0.12.7     jsonlite_1.1    digest_0.6.10

**Comment by bklingen** [comment]
Yes, I seem unable to delete rows, too.

**Comment by jrowen** [comment]
AS @bklingen notes, table interactivity has really been built for use in a shiny app.  If you view the plot in a browser, it's likely things will work better, but without shiny, there is no data persistence and changes are lost.

**Comment by GilesPercy** [comment]
OK, but I still get problems in shiny removing rows. A simple example is below. Remove the first row of the table and save. Note the rowHeader information is incorrect. If I then remove the first row again and save then the server crashes and I get a row.names error in hot_to_r.

Thanks GP

library(shiny)
library(rhandsontable)

ui <- fluidPage(
    rHandsontableOutput("in.table"),
    actionButton("Save", "Save")
)

server <- function(input, output) {
    
    output$in.table <- renderRHandsontable({
        rhandsontable(data.frame("UserID" = 1:5, "Name" = LETTERS[1:5]))
    })
    
    observeEvent(input$Save, {
        df <- hot_to_r(input$in.table)
        print(input$in.table$params$rowHeaders)
    })
    
}

shinyApp(ui = ui, server = server)

**Comment by jrowen** [comment]
Closing, but please let me know if you still have questions.
