### ISSUE TITLE
data.frame with all NAs is not editable

### ISSUE THREAD

**Issue by hherrada** [jrowen/rhandsontable#131]
When the complete table has NAs the user is not able to edit the table. I'm quite enjoying the package. Thanks!

**Comment by jrowen** [comment]
If you can post a minimally, reproducible example, I'll take a closer look.  Thanks.

**Comment by hherrada** [comment]
```
ui <- shinyUI(rHandsontableOutput("hot"))

server <- function(input, output) {
  output$hot <- renderRHandsontable(rhandsontable(matrix(ncol = 10, nrow = 2)))
}

shinyApp(ui = ui, server = server)
```

Thanks!

**Comment by jrowen** [comment]
The problem is that the blank table is assumed to have logical data types but that's getting lost when the table in initially rendered.  If you add a new row, you'll see that the check boxes work file.

If there's an actual use case here, we could try to determine the column type based on the NA type (see `?NA`).  Let me know.

**Comment by hherrada** [comment]
This actually works so there's no need to do anything. Thanks!

```
ui <- shinyUI(rHandsontableOutput("hot"))

server <- function(input, output) {
  output$hot <- renderRHandsontable(
    {rhandsontable(matrix(ncol = 10, nrow = 2)) %>%
        hot_cols(type = 'numeric')
    })
}

shinyApp(ui = ui, server = server)
```

**Comment by bklingen** [comment]
If you want the column types to be numeric, a good tip might be to start with an initial matrix of R type ``NA_integer``:

    myinit <- data.frame(Var1=rep(NA_integer_, 5), Var2=rep(NA_integer_, 5))

    ui <- shinyUI(rHandsontableOutput("hot"))

    server <- function(input, output) {
      output$hot <- renderRHandsontable(
        {rhandsontable(myinit) %>%
            hot_cols(type = 'numeric')
        })
    }

    shinyApp(ui = ui, server = server)
