### ISSUE TITLE
Refresh/render when hidden

### ISSUE THREAD

**Issue by hherrada** [jrowen/rhandsontable#132]
Hello, in my shiny app there are two different tabs. One controls the execution of a calculation that depends on the inputs from the hot table in the other tab. In certain cases the hot table might be programatically modified in the first tab. A problem arises when the calculation needs the latest hot table since this is not available until I click on the second tab and force the table to render. Only then I can go back to tab one and run the calc.

I thought the following settings would allow me to fix this, but they didn't [link](https://github.com/rstudio/shiny/issues/1409).

The problem with the server settings above is that the hot output id is not part of my shiny app's list of output objects. Is there a reason why?
```
outputOptions(output, "hotoutputId", suspendWhenHidden = FALSE)

Error in .subset2(x, "impl")$outputOptions(name, ...) : 
  hotoutputId is not in list of output objects

```
Thank you,
Hector

**Comment by jrowen** [comment]
Do you see any errors in the Javascript console when running your shiny app?  You could try adding `debug = 2` to your `rhandsontable` call to see when the tables are being updated.

**Comment by hherrada** [comment]
I don't see errors and I've debugged the app. The table refreshes when I click on the tab where the hot is located. I've solved my issue though by creating a reactive variable. This reactive variable will always be up to date. 

Thank you!
