### ISSUE TITLE
row names in exported csv file

### ISSUE THREAD

**Issue by hherrada** [jrowen/rhandsontable#134]
Hi, the example on how to export a csv file includes column names. I am not very familiar with javascript so was wondering if someone could help me out. What would I need to do to include row names as well?

Thank you

http://jrowen.github.io/rhandsontable/#customizing

**Comment by stla** [comment]
Hello hherrada,

 I can't help, I've never seen the function `csvString` before. This is not really an issue with the `rhandsontable` package. You rather should ask this question on stackoverflow.

**Comment by jrowen** [comment]
Closing, but please let me know if you still have questions.
