### ISSUE TITLE
Abnormal double reaction in Shiny

### ISSUE THREAD

**Issue by stla** [jrowen/rhandsontable#137]
Hello @jrowen, 

 Try to run the app below (which simply renders a handsontable), and to edit a cell. Then, in the console, the message `"hot2r has changed"` appears twice:
```
hot2r has changed
hot2r has changed
```

This is not normal. The value of `hot2r()` should not change twice and it does not change twice. You can uncomment the commented lines to save the consecutive values, and you will see that there are some duplicates.

```
library(shiny)
library(rhandsontable)

ui = shinyUI(fluidPage(
  sidebarLayout(
    sidebarPanel(),
    mainPanel(
      rHandsontableOutput("hot", width = 350)
    )
  )
))

server = shinyServer(function(input, output, session) {

  values = reactiveValues()
  values[["save"]] <- list()
  
  hot2r <- reactive({
    if(!is.null(input$hot)){
      hot_to_r(input$hot)
    }
  })
  
  observeEvent(hot2r(), {
    cat("hot2r has changed\n")
    #toSave <- c(isolate(values[["save"]]), list(hot2r()))
    #values[["save"]] <- toSave
    #saveRDS(toSave, file="aaa.rds")
  })
  
  data = reactive({
    if (!is.null(input$hot)) {
      DF = hot_to_r(input$hot)
    } else {
      if (is.null(values[["DF"]]))
        DF = mtcars[1:3,1:2]
      else
        DF = values[["DF"]]
    }
    values[["DF"]] = DF
    DF
  })
  
  output$hot <- renderRHandsontable({
    DF = data()
    if (!is.null(DF))
      rhandsontable(DF, stretchH = "all")
  })
})

runApp(list(ui=ui, server=server))

```

**Comment by bklingen** [comment]
You can see this "double execution" in a simpler app, where I simply ask to print out the current df to the consolle through ``print(df)``:

```{r}
df0 <- data.frame(Var1=2:4, Var2=9:7)  

ui <- fluidPage(
  rHandsontableOutput("hot")
)

server <- function(input, output) {
  output$hot <- renderRHandsontable({
    if(is.null(input$hot)) {
      df <- df0
    } else df <- hot_to_r(input$hot)
    print(df)
    rhandsontable(df)
  })
}

shinyApp(ui = ui, server = server)
```

On startup and then every time you change a value in the table, the code in ``output$hot`` seems to be executed twice, i.e., the the current table is printed twice to the console.

**Comment by stla** [comment]
In your app, `df` is printed each time `input$hot` changes, whiile in my mine, it is only printed each time `hot_to_r(input$hot)` changes. That's the strange point.

**Comment by happyshows** [comment]
I'm also observing the 'double reaction'. Not sure what's going on.

**Comment by jrowen** [comment]
You can try using `options(shiny.reactlog=TRUE)` to trace the inputs that are changing the table.

**Comment by aleksandra-m-k** [comment]
Hi, any news on that?

**Comment by jrowen** [comment]
I think this is related to https://github.com/jrowen/rhandsontable/issues/188.  I don't think the noted calls are needed anymore, so we'll see if removal causes any issues.

**Comment by jrowen** [comment]
We've made some updates that should hopefully resolve this issue.  Thanks for reporting and the feedback.

**Comment by bklingen** [comment]
As a consequence of these changes in the new release, input$hot seems to stay NULL although it is not. In the following app, I would expect the table to print (as it did in the old version), but now it only prints once a cell is edited. (The line commented out provides a workaround in this case but I find it unintuitive that input$hot is NULL although the rhandsontable shows the data.) However, this may be that input$hot and output$hot are not in sync.

```{r}
df0 <- data.frame(Var1=2:4, Var2=9:7)  

ui <- fluidPage(
  fluidRow(
    column(6,rHandsontableOutput("hot")),
    column(6,tableOutput("table"))
  )
)

server <- function(input, output) {
  output$hot <- renderRHandsontable({
     if(is.null(input$hot)) {
       df <- df0
     } else df <- hot_to_r(input$hot)
    rhandsontable(df)
  })
  output$table <- renderTable(hot_to_r(req(input$hot)))
  #output$table <- renderTable(if(is.null(input$hot)) return(df0) else return(hot_to_r((input$hot))))
}

shinyApp(ui = ui, server = server)
```

**Comment by jrowen** [comment]
Thanks for reporting this.  We created a new issue and rolled back part of
the js changes.
