### ISSUE TITLE
width of row headers too small

### ISSUE THREAD

**Issue by stla** [jrowen/rhandsontable#139]
Hello,

When doing `rhandsontable(mtcars)`, the width of the row headers column is too small (see "Cadillac").

![rplot01](https://cloud.githubusercontent.com/assets/4466543/21563334/9675eb48-ce81-11e6-8907-41914fa1008f.png)

**Comment by jrowen** [comment]
Please take a look at
http://jrowen.github.io/rhandsontable/#row_header_width

**Comment by stla** [comment]
Very good, thank you. Sorry for not having studying enough the doc.
