### ISSUE TITLE
Add row and column not working after htmlwidgets switch to jsonlite

### ISSUE THREAD

**Issue by jrowen** [jrowen/rhandsontable#14]
@yihui I'm wondering if you might have a suggestion here.  It appears that the switch to jsonlite is breaking the row and column add functionality in shiny.

If you run the basic shiny example and add a row, you'll see that the new row is returned to shiny as NULL values (see toR function), and then the unlist function drops the new row.  It seems that these NULL values must be converted to NA to be stored in a data.frame, and when the data.frame is returned to the widget, these NA values then need to be converted to NULL so they display as empty cells in the widget.

This logic appears to handle the NA conversion, but then I'm left with NA values in the widget.
```
out = lapply(out, function(x) lapply(x, function(x) ifelse(is.null(x), NA, x)))
```

The column add is creating a character vector.

**Comment by yihui** [comment]
Sorry about that. I will take a look tomorrow. `unlist()` does sound like a bad idea in this particular case.
