### ISSUE TITLE
A jQuery warning

### ISSUE THREAD

**Issue by stla** [jrowen/rhandsontable#140]
Hello, 
I get this warning with a Shiny app :
`Synchronous XMLHttpRequest on the main thread jquery.min.js:4 is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`
I don't know whether this causes a consequent effect. 
Some stackoverflows post about this warning:
- http://stackoverflow.com/questions/28322636/synchronous-xmlhttprequest-warning-and-script
- http://stackoverflow.com/questions/27736186/jquery-has-deprecated-synchronous-xmlhttprequest

**Comment by jrowen** [comment]
This package doesn't do any web requests, so you'd need to trace the warning back to find the source.

**Comment by stla** [comment]
Ah ok, so this is because I use some custom JS in my shiny app. Therefore, this issue has to do with `handsontable` and/or `jQuery`, but has nothing to do with `rhandsontable`.

=> I close. Thanks.

**Comment by stla** [comment]
Or this is due to `select(... , selectize=TRUE)`, that I use in my app - https://github.com/rstudio/shiny/issues/789
