### ISSUE TITLE
Hide NA values when double-clicking to edit cell

### ISSUE THREAD

**Issue by codingarmadillo** [jrowen/rhandsontable#141]
When a cell contains NA (as when you add a new row), if you double-click on the cell on it to edit, "NA" is displayed in the edit field. Is it possible to display the empty string in this case?

I know that you can single click to edit, but, users often double-click.

**Comment by jrowen** [comment]
The data coming from R is NA, and the custom table render changes it to an
empty string when displayed.  You might be able to customize the editor (
https://docs.handsontable.com/pro/1.8.2/tutorial-cell-editor.html), or
alternately, pass empty strings to the table and handle data conversions
within your app.

**Comment by jrowen** [comment]
Closing, but please let me know if you still have questions.
