### ISSUE TITLE
Inserting columns destroys data

### ISSUE THREAD

**Issue by nhpackard** [jrowen/rhandsontable#142]
Hi @jrowen, 
Great package! Thanks!!

Seems like when I insert a column to left, right-clicking on the "nm" column, I get a new column to the left, but nm and dt are instantly changed to NA's.

Also, column insertion seems to work only when 'use data types' is set to FALSE.  Is this correct?  Seems to contradict the text above.

**Comment by jrowen** [comment]
Can you post app code you're using to test?

**Comment by jrowen** [comment]
Closing, but please let me know if you still have questions.
