### ISSUE TITLE
dateFormat

### ISSUE THREAD

**Issue by quantransform** [jrowen/rhandsontable#145]
I have tried the following code but the date format does not seem to work initially, You can click and select date and the date format will then be changed to the right format (but the rest will remain in "MM/DD/YYYY"). Any idea how to solve this? Thank you a lot.

`
data = data.frame(matrix(data = NA, nrow = 5, ncol = 1))
colnames(data) = "Date"
data$Date = Sys.Date() + seq(0, 4)

rhandsontable(data) %>%
  hot_col("Date", formatDate = "DD/MM/YYYY")
`

**Comment by jrowen** [comment]
This seems to be an issue with handsontable (see https://github.com/handsontable/dev-handsontable/issues/134).  The formatting will be applied after clicking in the cell.

This might be a temporary fix
```
data = data.frame(matrix(data = NA, nrow = 5, ncol = 1))
colnames(data) = "Date"
data$Date = Sys.Date() + seq(0, 4)
data$Date = as.character(data$Date, format = "%d/%m/%Y")

rhandsontable(data) %>%
  hot_col("Date", dateFormat = "DD/MM/YYYY", type = "date")
```

**Comment by jrowen** [comment]
This appears to be fixed in the latest version of the library.

**Comment by marciz** [comment]
Hi, @jrowen 
I still cant get it working with custom date formats

```
library(shiny)
library(rhandsontable)

dt_date <- data.frame(
  date1 = rep(Sys.Date(), 3),
  date2 = Sys.Date()
)

ui <- fluidPage(
  rHandsontableOutput("hot"),
  tableOutput("table")
)

server <- function(input, output) {
  output$hot <- renderRHandsontable({
    if(is.null(input$hot))
      dt <- dt_date
    else 
      dt <- hot_to_r(input$hot)
    rhandsontable(dt) %>%
      hot_col(col = "date2", dateFormat = 'MM-DD-YYYY')
  })
  output$table <- renderTable(hot_to_r(req(input$hot)))
}

shinyApp(ui = ui, server = server)
```

Also `hot_to_r` is not working for date2. To get this working for specific date format I had to change `rhandsontable`, `toR` and `colClasses` functions (date format defined in those functions). 
For the solution I guess there should be a way to get date format from `hot_col` and to pass to those functions

**Comment by rfaelens** [comment]
+1
To use a custom date format, you currently need to

1. Convert the data-frame date column to a character
2. Specify the dateFormat in the hot_col specification
3. Convert back from the character string after reading input$table using hot_to_r
