### ISSUE TITLE
Using rendered disables previous numeric formating

### ISSUE THREAD

**Issue by KiprasKancys** [jrowen/rhandsontable#146]
I am using renderer to change some column background colours. But I noticed that my previous numeric formatting is gone. I tried it on your own examples and noticed the same thing.
Here without render
```R
rhandsontable(MAT, readOnly = TRUE, width = 750, height = 300) %>%
    hot_col("B", format = "0.0")
```

![paveikslas](https://cloud.githubusercontent.com/assets/14861371/22141671/cbb9b7d2-defb-11e6-800a-c01d55b33e16.png)
But once I add renderer formating is gone.
```R
rhandsontable(MAT, readOnly = TRUE, width = 750, height = 300) %>%
    hot_col("B", format = "0.0") %>% 
    hot_cols(renderer = 
        "function (instance, td, row, col, prop, value, cellProperties) {
            Handsontable.renderers.TextRenderer.apply(this, arguments); 
            if (row == col) { td.style.background = 'lightgrey'; } 
            else if (col > row) { td.style.background = 'grey'; td.style.color = 'grey'; } 
            else if (value < -0.75) { td.style.background = 'pink'; } 
            else if (value > 0.75) { td.style.background = 'lightgreen'; } }")
```

![paveikslas](https://cloud.githubusercontent.com/assets/14861371/22141676/d6510b6e-defb-11e6-9086-fc945be8f559.png)

**Comment by jrowen** [comment]
Try using `NumericRenderer` instead.  [Fixed now](http://jrowen.github.io/rhandsontable/#conditional_formatting).  Thanks for reporting.
