### ISSUE TITLE
export to csv

### ISSUE THREAD

**Issue by kferris10** [jrowen/rhandsontable#15]
Did you take down the export to csv branch?

**Comment by jrowen** [comment]
The branch was merged into master.

**Comment by kferris10** [comment]
My bad.  Thanks

**Comment by jrowen** [comment]
I made some changes to the context menu options that impact this functionality, and I'd appreciate your feedback.  In a nutshell, I removed the option to enable the csv export on the context menu, but I enabled the option for a user to define his or her own export option.  You can find an example [here](https://github.com/jrowen/rhandsontable/blob/context_menu/inst/examples/context_menu.R).

You can install using
```
devtools::install_github("jrowen/rhandsontable", ref = "context_menu")
```

**Comment by kferris10** [comment]
It looks slick.  Is it working though?  I can't seem to get anything to download.  [Example](http://rpubs.com/kferris10/107594)

**Comment by jrowen** [comment]
A couple copy-paste JS errors on my part.  See the corrected [example](https://github.com/jrowen/rhandsontable/blob/context_menu/inst/examples/context_menu.R).  Thanks for taking a look--all feedback welcome.

**Comment by kferris10** [comment]
When downloading, is there any way to specify the csv file extension automatically?  So that the user doesn't have to save as `temp.csv`?

![image](https://cloud.githubusercontent.com/assets/6612411/10052154/5ce8b60e-61f3-11e5-9e5c-ca2af053b813.png)

**Comment by jrowen** [comment]
If you look at [this](https://github.com/jrowen/rhandsontable/blob/master/inst/examples/context_menu.R) example, you'll see that the file name is specified in the JS code.  You can change this logic to create the file naming logic meets your needs.

**Comment by kferris10** [comment]
Cool.

Not related to this issue, but some people at work thought this was great today.  Thanks!

**Comment by jrowen** [comment]
Glad to hear you're finding the library useful.  Issues, feature suggestions and pull requests are always welcome.

**Comment by wilhelminayao** [comment]
Is "export to CSV" function available on shiny apps? I tried the code in the corrected example but it does not work. Any solutions? Thank you.

**Comment by jrowen** [comment]
Take a look at http://jrowen.github.io/rhandsontable/#customizing.

**Comment by zhanxw** [comment]
@wilhelminayao  Please refer to https://github.com/jrowen/rhandsontable/blob/master/inst/examples/context_menu.R

In the Javascript part, replace 'instance' with 'this', and replace 'filename' with a real file name you want to use.
