### ISSUE TITLE
edit reactive shiny objects in rhandsontable, send to db

### ISSUE THREAD

**Issue by annieodonnell** [jrowen/rhandsontable#150]
Great package! I can see how this will really support me with things I've wanted to do for a while.

Do you have an idea about this issue I am experiencing, I have a large amount of data in a database that I can call using reactive functions in shiny. I would like to present the selected data using `rhandsontable`, update as necessary and send the data back to the database.

I am running into difficulty when trying to select a reactive object inside another reactive object. I know how to do this with data in memory, as per [this example](http://stackoverflow.com/questions/32292547/shiny-switching-between-reactive-data-sets-with-rhandsontable), I need to access this data from a database as it's too large to fit into memory.

See reproducible example below, I would just like to select the different choice options and set the `t4` values to `F`, but the table does not update when I select new reactive data from the drop down menu.

`library(shiny)`
`library(rhandsontable)`
`library(dplyr)`
`library(magrittr)`
`library(RSQLite)`
`library(DBI)`

`dat <- data.frame("id" = 1:10,
              "choice" = rep(c("option 1", "option 2"), each = 5),
              "t1" = sample(1:100, 10),
              "t2" = sample(1:100, 10),
              "t3" = sample(1:100, 10),
              "t4" = rep("T", 10))`

\# define database
`test_db <- src_sqlite("test_db.sqlite3", create = T)`

\# copy to database:
`test_sqlite <- copy_to(test_db, dat, temporary = FALSE, indexes = list(
  c("choice"),"t1", "t2", "t3", "t4"))`

\# test data is loaded:
`dbGetQuery(test_db$con, paste0("SELECT * FROM dat"))`

\# build shiny app:

`shinyApp(`
  `shinyUI(`
    `fluidRow(`
  `selectInput("select", label = h3("Select box"), `
              `choices = list("option 1", "option 2"),` 
              `selected = "option 1"),`
 `rHandsontableOutput("hot"),`
  `actionButton("to_db", label = "Send to Database"),`
  `verbatimTextOutput("to_db_text")`
`)),`

`shinyServer(function(input, output, session) {`

\# define data to select 
`select_dat <- eventReactive(input$select, {
  dbGetQuery(test_db$con, paste0("SELECT * FROM dat WHERE choice = '", input$select, "'"))
  })`

\# debugging
`observe({print(input$select)})`
`observe({print(select_dat())})`

`values = reactiveValues()`

`data = reactive({`
 `if (!is.null(input$hot)) {`
    `DF = hot_to_r(input$hot)`
 `} else {`
    `if (is.null(values[["DF"]]))`
       `DF = select_dat()`
    `else`
      `DF = values[["DF"]]`
  `}`
  `values[["DF"]] = DF`
  `DF`
`})`

`output$hot <- renderRHandsontable({`
  `DF = data()`
  `if (!is.null(DF))`
 `rhandsontable(DF, stretchH = "all", selectCallback = TRUE,  readOnly = T) %>%
    hot_col("t4", readOnly = F, type = "dropdown", source = c("T","F"))
})`

\#    debugging    
`observe({print(data())})` 

`ntext <- eventReactive(input$to_db, {`
  `ids <- data() %>% filter(t4 == "F") %>% dplyr::select(id) %>% extract2(1)`
   `sql_str <- paste0("UPDATE dat SET t4 = 'F' WHERE id IN (", paste(ids, collapse=","),")")`
   `dbExecute(test_db$con, sql_str)`

`})`

`observe({print(ntext())})`

`})`
`)`

I've added some debugging to print the outputs to the screen when different options are selected - you'll notice that the `choice` selected, i.e. `option1` to `option2` does not change in the `rhandsontable` but it does appear to update when printing `data()` to screen. Any help would be greatly appreciated.

Many thanks,

Annie

**Comment by jrowen** [comment]
I'd suggest taking another look at the `data` reactive function.  I'm not sure you need to use `reactiveValues` to store your data.

**Comment by jrowen** [comment]
Closing, but please let me know if you still have questions.
