### ISSUE TITLE
Cell comments example not working

### ISSUE THREAD

**Issue by happyshows** [jrowen/rhandsontable#155]
http://jrowen.github.io/rhandsontable/#cell_comments

**Comment by happyshows** [comment]
![image](https://cloud.githubusercontent.com/assets/3208181/23717017/ce64995e-03f7-11e7-9169-87e79a1cc7f9.png)

**Comment by jrowen** [comment]
I just pushed an update that should fix this.  Thanks for reporting.

**Comment by happyshows** [comment]
can you double check, still not seeing the red flag yet...

**Comment by jrowen** [comment]
Did you test on the dev version?  I haven't updated the doc pages yet.

**Comment by jrowen** [comment]
Closing, but please let me know if you still have questions.
