### ISSUE TITLE
Example code for input$hot_select

### ISSUE THREAD

**Issue by TomWeishaar** [jrowen/rhandsontable#156]
I'm trying to figure out how to use input$hot_select, but I can't find any example code anywhere and what I've tried so far always returns NULL.

It would also be helpful if the example used two dataframes open on the same page. Thanks for what looks like a very useful project!

Tom

**Comment by jrowen** [comment]
You should be able to add `selectCallback = TRUE` to your `rhandsontable` call and then the _select input will be active.  If you also add `debug = 2` to the `rhandsontable` call, you can use the JavaScript console to see when the event fires.

I agree, the project could use more _select and _comment documentation.  PRs are always welcome.

**Comment by TomWeishaar** [comment]
Thanks - I'm getting the reaction from _select now. I'll pull together some examples.

**Comment by jrowen** [comment]
That would be great.  The doc pages are built from
https://github.com/jrowen/rhandsontable/blob/master/docs/index.Rmd, so feel
free to submit a PR with examples at your leisure.
