### ISSUE TITLE
How to add Search box on top of Rhandsontable output

### ISSUE THREAD

**Issue by AmarendarAndhe** [jrowen/rhandsontable#157]
Hi Jrowen,

Is there way i can add search box on top right corner of rHandsontable output or i can put column filter on top of each column of rHandsontable output, these features are available in DT::datatable but i am not able find in rHandsontable. please help me on the same... Thanks

**Comment by jrowen** [comment]
I don't believe this feature is implemented.  You can learn more at https://docs.handsontable.com/0.31.1/demo-searching.html.

**Comment by jrowen** [comment]
Closing, but please let me know if you still have questions.
