### ISSUE TITLE
customBorders

### ISSUE THREAD

**Issue by theyuish** [jrowen/rhandsontable#159]
When I wrote a Shiny App and tried to update Borders by reactive value, I realised that the border can't be update. I found some discussion on this as below:

https://github.com/handsontable/handsontable/issues/2002

I assume there is no way to fix this on R?

Thank you.

**Comment by jrowen** [comment]
This library is just an interface into `handsontable`, so any issues with that library will also exist in `rhandsontable`.

**Comment by jrowen** [comment]
Closing, but please let me know if you still have questions.
