### ISSUE TITLE
hot_to_r not functioning when removing column from table

### ISSUE THREAD

**Issue by moman822** [jrowen/rhandsontable#160]
In a Shiny environment, I am finding that the `hot_to_r()`  function is not able to convert `input$hot` to an R object if the user has removed a column. See the following example:
```

library(rhandsontable)

shinyApp(
  
  shinyUI(fluidPage(
    titlePanel("Try to remove a column"),
    
    
    
    rHandsontableOutput("hot")
  )),
  
  shinyServer(function(input, output, session) {
    
    samp <- reactiveValues()
    samp$df <- mtcars
    
    output$hot = renderRHandsontable({
      if (!is.null(input$hot)) {
        DF = hot_to_r(input$hot)
      } else {
        DF = samp$df
      }
      
      rhandsontable(DF, useTypes = FALSE) %>%
        hot_table(highlightCol = TRUE, highlightRow = TRUE)
    })
    
  })
)
```

If I attempt to remove a column as is, I receive the following error:
`ERROR: 'names' attribute [12] must be the same length as the vector [10]`
in the shiny app output

and this in the console:

```
Warning: Error in colnames<-: 'names' attribute [12] must be the same length as the vector [10]
Stack trace (innermost first):
    86: colnames<-
    85: <Anonymous>
    84: do.call
    83: hot_to_r
    82: func [~/.active-rstudio-document#20]
    81: origRenderFunc
    80: output$hot
     5: <Anonymous>
     4: do.call
     3: print.shiny.appobj
     2: print
     1: source
```

Thoughts?

Great package by the way. Thanks!

Edit: I have the most recent development version installed.

**Comment by jrowen** [comment]
Have you tried the dev version?  We fixed a similar issue earlier.

**Comment by moman822** [comment]
I believe I am on the dev version:

` rhandsontable_0.3.4.3`

**Comment by moman822** [comment]
Are you able to confirm that this is a bug? If not, it would be great to know what I am doing incorrectly. Thanks.

**Comment by jrowen** [comment]
I think this should be fixed with the latest dev version, please let me know if you are still running into problems.  Thanks for reporting.
