### ISSUE TITLE
Mistake in hot_cols documentation

### ISSUE THREAD

**Issue by pfgherardini** [jrowen/rhandsontable#162]
Hi!

Thank you so much for a fantastic package. I think there is a mistake in the documentation of the hot_cols function. The fixedColumnsLeft is not a vector of which columns should be frozen on the left, but instead a single number indicating how many columns should be frozen on the left.

I tried using a vector and it doesn't work, while a single number works as intended. See also here

https://docs.handsontable.com/0.15.1/demo-fixed-rows-and-columns.html

**Comment by jrowen** [comment]
Thanks for reporting.
