### ISSUE TITLE
numerical formatting by category in rhandsontable in shiny

### ISSUE THREAD

**Issue by ghost** [jrowen/rhandsontable#165]
library(datasets)
library(rhandsontable)

data = iris

I want to change the numerical  format of Sepal.Length  to "0" only of Species = "setosa". How can I do it in rhandsontable ?

**Comment by jrowen** [comment]
Formatting is generally defined at the column level.  You'd need to create a custom cell renderer if you want to apply custom formatting based on the contents of other cells.

**Comment by sumeda85** [comment]
thank you
