### ISSUE TITLE
How to retain more than two decimal places in rhandsontable 

### ISSUE THREAD

**Issue by sumeda85** [jrowen/rhandsontable#168]
When I have hot object and try to convert it to an r object using  hot_to_r, it only retains two decimal places. How can I retain the numbers as it is ? As an example 3.5906 is shown as 3.59. 

Instead I want 3.5906 as in the r object.

**Comment by jrowen** [comment]
Take a look at using the `format` param of `hot_col` to specify the precision.

**Comment by sumeda85** [comment]
thank you
