### ISSUE TITLE
search option on rhandsontable when dealing with huge tables 

### ISSUE THREAD

**Issue by sumeda85** [jrowen/rhandsontable#170]
My table has 2000 rows and I want to have a search option or find option on rhandsontable object. How can I do this this in Shiny?

**Comment by jrowen** [comment]
Handsontable [supports searching](https://docs.handsontable.com/0.34.0/demo-searching.html), but this functionality hasn't been implemented in this package.

**Comment by jrowen** [comment]
Search was improved with v0.3.5.  Thanks for the suggestion.
