### ISSUE TITLE
Unable To install Package getting Error "unable to access index for repository "

### ISSUE THREAD

**Issue by NabiAli** [jrowen/rhandsontable#177]
Since Last few days i am trying to install this package , on the first place i thought there's some issue with my internet connection But then internet is working fine still i am getting an Error as specified below. Please do guide me on this 

> install.packages("rhandsontable")
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/src/contrib:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES'

**Comment by jrowen** [comment]
This looks like an issue with you local set-up.
