### ISSUE TITLE
Rhandsontable shrinks columns when opened twice

### ISSUE THREAD

**Issue by RobertLD** [jrowen/rhandsontable#178]
I have an Rhandsontable set to run from within a modaldialog in shiny. The code looks like this:
`rhandsontable(weight_file ,readOnly = FALSE,width = 500,height = 500,contextMenu = FALSE,columnSorting = FALSE) %>% hot_col(1, readOnly = TRUE) %>% hot_col(2, readOnly = TRUE)`

This statement is run from within a modaldialog by the user clicking an action button. The first time it is run it displays normally
![numer_1](https://user-images.githubusercontent.com/30250210/28420758-2e735572-6d31-11e7-8bff-a03c80e9209b.JPG)
and a little error message is displayed when using the shiny trace mechanic but it works fine
`SEND {"errors":[],"values":{"hot_cw":{"x":{"data":[{"admin":"Afghanistan","Index":1,"CiLV":1},{"admin":"Angola","Index":2,"CiLV":1},{"admin"`

However if I were to run it again, the table columns shrink from their current size to this:
![num_2](https://user-images.githubusercontent.com/30250210/28420919-a915696e-6d31-11e7-9cb1-1ca9c7cb58e7.JPG)

**Comment by jrowen** [comment]
This is difficult to debug without a minimally reproducible example.  For the second table, I'd suggest taking a look at the JS console to see if you're running into an error.

**Comment by suw09002** [comment]
I am seeing the same issue. Below is a minimally reproducible example.
The first time you hit "Launch", the table renders fine. Once you close out of the modalDialog and hit "Launch" again, only one of the columns renders. The table only renders fully again when you click on the table or the scroll bar . 

I checked out the JS Console and didn't see any errors come up. Any suggestions? Thanks!

shinyApp(
server = function(input, output, session) {
  
  newModal <- modalDialog(
    title = "xxx",
    HTML(" <b> Test: </b> <br> "),
    rHandsontableOutput("test"),
    footer = list(modalButton("Close")
    )
  )
  
  
  output$test <- renderRHandsontable({
    if (!is.null(input$test)) {
      test <- data.table(hot_to_r(input$test))
    } else if (!is.null(out$restoreTbl[["test"]])) {
      test <- hot_to_r(out$restoreTbl[["test"]])
    } else {
      test <- data.table(x = c(1:10),
                         y = 0,
                         z = 0,
                         a = 0)
    } 
    rhandsontable(test)
  })
  
  observeEvent(input$launch, { showModal(newModal) })
},

ui <- fluidPage(
  actionButton("launch", "Launch")
)
)

**Comment by xsswang** [comment]
Have the same issue. Still no solution yet.

**Comment by jrowen** [comment]
I'm not able to reproduce this issue with the latest version of the library.  Please re-open if the problem persists.

**Comment by vinamra9** [comment]
Did anyone find a solution to this issue?
