### ISSUE TITLE
A simple shiny example, read only cols

### ISSUE THREAD

**Issue by marciz** [jrowen/rhandsontable#18]
Hi,
when adding read only property for cols, example not working properly, but hot_table(readOnly = TRUE) is ok.

```
library(shiny)
library(rhandsontable)

ui = shinyUI(fluidPage(
  
  titlePanel("Handsontable"),
  
  sidebarLayout(
    sidebarPanel(
      helpText("Handsontable demo output. Column add/delete does work ",
               "for tables with defined column properties, including type."),
      radioButtons("useType", "Use Data Types", c("TRUE", "FALSE"))
    ),
    mainPanel(
      rHandsontableOutput("hot")
    )
  )
))

server = function(input, output) {
  output$hot <- renderRHandsontable({
    if (is.null(input$hot)) {
      DF = data.frame(val = 1:10, bool = TRUE, nm = LETTERS[1:10],
                      dt = seq(from = Sys.Date(), by = "days", length.out = 10),
                      stringsAsFactors = F)
    } else {
      DF = hot_to_r(input$hot)
    }
    rhandsontable(DF, useTypes = as.logical(input$useType)) %>%
      # hot_table(readOnly = TRUE) # ok
      hot_col(col = 1, readOnly = TRUE) 
  })
}

shinyApp(ui = ui, server = server)
```

Thanks

**Comment by jrowen** [comment]
Your example is working fine for me.  Could you please verify you have the latest Github version of rhandsontable and shiny?

**Comment by marciz** [comment]
Reinstalled everything but still the same and not sure it is ok - no any error message but when click on FALSE radio button all other columns except first one (the one which is set to read only) disappear

>R version 3.2.0 (2015-04-16)
>Platform: x86_64-w64-mingw32/x64 (64-bit)
>Running under: Windows 7 x64 (build 7601) Service Pack 1
>other attached packages:
>[1] rhandsontable_0.0.2 shiny_0.11.1.9004  
>loaded via a namespace (and not attached):
> [1] htmlwidgets_0.3.3 magrittr_1.5      R6_2.0.1          tools_3.2.0      
> [5] htmltools_0.2.6   yaml_2.1.13       Rcpp_0.11.5       jsonlite_0.9.16  
> [9] digest_0.6.8      xtable_1.7-4      httpuv_1.3.2      mime_0.3

**Comment by jrowen** [comment]
I now understand the issue, thanks for clarifying.  I pushed a fix; let me know if you're still running into problems.  Thanks for posting.
