### ISSUE TITLE
conditional formatting AND "dropdown"

### ISSUE THREAD

**Issue by mtseman** [jrowen/rhandsontable#184]
If I set a column to type=dropdown and then pipe conditional formatting. I loose the dropdown in the column.

It appears to be calling the renderer undoes prior formating. I tried changing pipe order and no difference

Compare these two tables to see what I mean, I loose the nice little arrow.

```
df<-data.frame(Values=seq(1,10),
               Letters=LETTERS[1:10],
               Percent=seq(1.4,.5,by=-.1))



#With dropdown arrow shown in cell
hot1<-rhandsontable(df, rowHeaders = F,stretchH='all', height = 450,readOnly = T) %>%
  hot_col(col = "Letters", type = "dropdown", source = LETTERS[1:10],readOnly=F)


#Without dropdown arrow shown in cell
hot2<-rhandsontable(df, rowHeaders = F,stretchH='all', height = 450,readOnly = T) %>%
  hot_col(col = "Letters", type = "dropdown", source = LETTERS[1:10],readOnly=F) %>%
  hot_cols(renderer = "
           function (instance, td, row, col, prop, value, cellProperties) {
             Handsontable.renderers.NumericRenderer.apply(this, arguments);
             if (col == 2 && value < 1 ) {
              td.style.background = 'pink';
             } else if (col == 2 && value > 1) {
              td.style.background = 'lightgreen';
             } 
           }")
``

**Comment by jrowen** [comment]
If you want the field to be a dropdown, you'll need to update your custom renderer to use one of the other options.  You can see some of the options [here](https://github.com/handsontable/handsontable/tree/master/src/renderers).

**Comment by cca32** [comment]
@jrowen I am having similar problems. When I use `hot_col("target_col", type = "dropdown" ...)`, it works just fine. When I use `hot_cols(renderer = "js here")` it conditionally highlights what I want. But it removes the dropdown arrow from `type = "dropdown"`. The type is still a dropdown (it works if I click the cell) but the arrow is missing. How do I fix that?

Is there a way to make the dropdown arrow bold?
