### ISSUE TITLE
rhandsontable block double_click gestures in shiny interactive plots on latest firefox browsers

### ISSUE THREAD

**Issue by sorhawell** [jrowen/rhandsontable#185]
The bug was observed both in windows and a fresh ubuntu environment. Code below assumes firefox is the default browser. The code below activates the bug on a fresh ubuntu install. Simply if a rhandsontable is loaded, the latest version of firefox browser cannot no longer send double_click gestures to rserver. No problems with edge or chrome. There was no problem with firefox browsers some weeks ago.
```
#R code
install.packages(c("shiny","rhandsontable"))
library(shiny)
library(rhandsontable) #does not work with cran version


install.packages("devtools")
library(devtools)
install_github("jrowen/rhandsontable") #and does not work with latest dev version


ui =   basicPage(
  titlePanel("rhandsontable disable double click in interactive plot in firefox under very specific conditions"),
  
  #just for viewing interactive commmands
  verbatimTextOutput("info"),
  
  #this interactive plot wont recognize double click in firefox browser, if....
  plotOutput("thisPlot",
             click = "plot_click",
             dblclick = "plot_dblclick",
             hover = "plot_hover",
             brush = "plot_brush",
             height = 400)
  #this rhandsontable is loaded, outcomment to remove double_click bug
  ,fluidRow(rHandsontableOutput("hotStatTable")) #out comment me and error disaapears
  
)  #end basic page


server = function(input,output) {
  
  output$thisPlot <- renderPlot(plot(rnorm(1000)))
  
  #this will block double click signals
  output$hotStatTable <- renderRHandsontable({rhandsontable(cars) %>% hot_table()})
  
  #remaing code only to show if double click works or not
  output$info <- renderText({
    xy_str <- function(e) {
      if(is.null(e)) return("NULL\n")
      paste0("x=", round(e$x, 1), " y=", round(e$y, 1), "\n")
    }
    xy_range_str <- function(e) {
      if(is.null(e)) return("NULL\n")
      paste0("xmin=", round(e$xmin, 1), " xmax=", round(e$xmax, 1), 
             " ymin=", round(e$ymin, 1), " ymax=", round(e$ymax, 1))
    }
    paste0(
      "click: ", xy_str(input$plot_click),
      "dblclick: ", xy_str(input$plot_dblclick),
      "hover: ", xy_str(input$plot_hover),
      "brush: ", xy_range_str(input$plot_brush)
    )
  })
  observeEvent(input$plot_dblclick,print("double activated"))
  
}  # renderRH


#writing server and ui file
writeLines(text=deparse(server),"server.R")
writeLines(text=deparse(ui),"ui.R")
runApp(launch.browser = T) #double click does not work with default firefox browser
#if started with chrome or windows edge browswer, it does seem to work


Sys.getenv()

this freshly installed ubuntu image is a little old, but the bug is also present in latest ubuntu environment

```

> 
> CLUTTER_IM_MODULE                       xim
> COMPIZ_BIN_PATH                         /usr/bin/
> COMPIZ_CONFIG_PROFILE                   ubuntu-lowgfx
> DBUS_SESSION_BUS_ADDRESS                unix:abstract=/tmp/dbus-QlreGrFZVS
> DEFAULTS_PATH                           /usr/share/gconf/ubuntu.default.path
> DESKTOP_SESSION                         ubuntu
> DISPLAY                                 :0
> EDITOR                                  vi
> GDM_LANG                                en_US
> GDMSESSION                              ubuntu
> GIO_LAUNCHED_DESKTOP_FILE               /usr/share/applications/rstudio.desktop
> GIO_LAUNCHED_DESKTOP_FILE_PID           22864
> GIT_ASKPASS                             rpostback-askpass
> GNOME_DESKTOP_SESSION_ID                this-is-deprecated
> GNOME_KEYRING_CONTROL                   
> GNOME_KEYRING_PID                       
> GPG_AGENT_INFO                          /home/cleanjean/.gnupg/S.gpg-agent:0:1
> GTK2_MODULES                            overlay-scrollbar
> GTK_IM_MODULE                           ibus
> GTK_MODULES                             gail:atk-bridge:unity-gtk-module
> HOME                                    /home/cleanjean
> IM_CONFIG_PHASE                         1
> INSTANCE                                
> JOB                                     unity-settings-daemon
> LANG                                    en_US.UTF-8
> LANGUAGE                                en_US:en
> LD_LIBRARY_PATH                         /usr/lib/R/lib::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/jre/lib/amd64/server
> LIBGL_ALWAYS_SOFTWARE                   1
> LN_S                                    ln -s
> LOGNAME                                 cleanjean
> MAKE                                    make
> MANDATORY_PATH                          /usr/share/gconf/ubuntu.mandatory.path
> PAGER                                   /usr/bin/pager
> PATH                                    /home/cleanjean/bin:/home/cleanjean/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> PWD                                     /home/cleanjean
> QT4_IM_MODULE                           xim
> QT_ACCESSIBILITY                        1
> QT_IM_MODULE                            ibus
> QT_LINUX_ACCESSIBILITY_ALWAYS_ON        1
> QT_QPA_PLATFORMTHEME                    appmenu-qt5
> R_BROWSER                               xdg-open
> R_BZIPCMD                               /bin/bzip2
> R_DOC_DIR                               /usr/share/R/doc
> R_GZIPCMD                               /bin/gzip -n
> R_HOME                                  /usr/lib/R
> R_INCLUDE_DIR                           /usr/share/R/include
> R_LIBS_SITE                             /usr/local/lib/R/site-library:/usr/lib/R/site-library:/usr/lib/R/library
> R_LIBS_USER                             ~/R/x86_64-pc-linux-gnu-library/3.4
> RMARKDOWN_MATHJAX_PATH                  /usr/lib/rstudio/resources/mathjax-26
> R_PAPERSIZE                             letter
> R_PAPERSIZE_USER                        letter
> R_PDFVIEWER                             /usr/bin/xdg-open
> R_PLATFORM                              x86_64-pc-linux-gnu
> R_PRINTCMD                              /usr/bin/lpr
> R_RD4PDF                                times,inconsolata,hyper
> R_SESSION_TMPDIR                        /tmp/Rtmp2E5jG3
> R_SHARE_DIR                             /usr/share/R/share
> RS_LOCAL_PEER                           /tmp/39547-rsession
> RS_PPM_FD_READ                          20
> RS_PPM_FD_WRITE                         21
> RS_RPOSTBACK_PATH                       /usr/lib/rstudio/bin/rpostback
> RS_SHARED_SECRET                        16816927778469308861804289383
> RSTUDIO                                 1
> RSTUDIO_PANDOC                          /usr/lib/rstudio/bin/pandoc
> RSTUDIO_SESSION_PORT                    39547
> RSTUDIO_USER_IDENTITY                   cleanjean
> RSTUDIO_WINUTILS                        bin/winutils
> R_SYSTEM_ABI                            linux,gcc,gxx,gfortran,?
> R_TEXI2DVICMD                           /usr/bin/texi2dvi
> R_UNZIPCMD                              /usr/bin/unzip
> R_ZIPCMD                                /usr/bin/zip
> SED                                     /bin/sed
> SESSION                                 ubuntu
> SESSIONTYPE                             gnome-session
> SHELL                                   /bin/bash
> SHLVL                                   0
> SSH_AUTH_SOCK                           /run/user/1000/keyring/ssh
> TAR                                     /bin/tar
> UPSTART_EVENTS                          xsession started
> UPSTART_INSTANCE                        
> UPSTART_JOB                             unity7
> UPSTART_SESSION                         unix:abstract=/com/ubuntu/upstart-session/1000/22028
> USER                                    cleanjean
> XAUTHORITY                              /home/cleanjean/.Xauthority
> XDG_CONFIG_DIRS                         /etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
> XDG_CURRENT_DESKTOP                     Unity
> XDG_DATA_DIRS                           /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
> XDG_GREETER_DATA_DIR                    /var/lib/lightdm-data/cleanjean
> XDG_MENU_PREFIX                         gnome-
> XDG_RUNTIME_DIR                         /run/user/1000
> XDG_SEAT                                seat0
> XDG_SEAT_PATH                           /org/freedesktop/DisplayManager/Seat0
> XDG_SESSION_DESKTOP                     ubuntu
> XDG_SESSION_ID                          c2
> XDG_SESSION_PATH                        /org/freedesktop/DisplayManager/Session0
> XDG_SESSION_TYPE                        x11
> XDG_VTNR                                7
> XMODIFIERS                              @im=ibus

**Comment by jrowen** [comment]
Is this still an issue.  If so, we should look to log something with `handsontable`.
