### ISSUE TITLE
Date columns in tibbles are not represented correctly

### ISSUE THREAD

**Issue by s-fleck** [jrowen/rhandsontable#186]
rhandsontable behaves weirdly when a tibble with a date column is passed to it. Each cell of the date column contains c(...whole data column...).

```
dat <- data.frame(x = as.Date(c("2016-01-01", "2016-01-02", "2016-01-03")))
rhandsontable::rhandsontable(dat)
rhandsontable::rhandsontable(tibble::as_tibble(dat))
```
A practical workaround to this issue would be just coercing all data.frame like inputs to rhandsontable with `as.data.frame()`. This would also fix #115.

**Comment by jrowen** [comment]
I think I'd rather have the user choose to make the conversion when rendering the table.  Maybe there's a need for a warning message stating that `data.tables` and `tibbles` aren't fully supported.  To fully support, we will need to enhance `get_col_types` in misc.R.

**Comment by s-fleck** [comment]
I don't think the problem is in `get_col_types()`. This works just fine:

```
get_col_types(
tibble::tibble(
  Date = as.Date(c("2017-08-12", "2017-08-13"))
))
```
I am not sure I agree with the warning. Since data.tables and tibbles produce faulty output, it should throw an error and abort, at least if illegal field types are present (such as date). Why are you so against converting the input to `data.frame` as a quick fix? The input object is never returned to the users if i understand correctly, so It should not matter to them.

**Comment by jrowen** [comment]
You bring up a good point. I wouldn't want someone to pass a tibble and
then get a data.frame back, but maybe we can convert the input object.

**Comment by jrowen** [comment]
We implemented the quick fix you suggested.  Thanks for the feedback.
