### ISSUE TITLE
rhandsontable.js onInputChange

### ISSUE THREAD

**Issue by marciz** [jrowen/rhandsontable#188]
What is the reason in rhandsontable.js to use second Shiny.onInputChange in function afterChange - lines 136-140, under the condition source == "loadData" && this.params. I am not aware what sourec == "loadData" stands for, but I tried to remove it and few examples I ran was just fine. In this case rhandsontable renders only once after the changes, not twice as originally. It also reduces sync problems between rhandsontable  input and output.

**Comment by jrowen** [comment]
Thanks for the suggestion.  We've implementated the suggestion.
