### ISSUE TITLE
Copy column larger than table

### ISSUE THREAD

**Issue by marciz** [jrowen/rhandsontable#19]
In Shiny copying single or few columns larger than given table row size and pasting causes error "invalid 'row.names' length".

Thanks

**Comment by jrowen** [comment]
Could you provide a reproducible example?  Thanks.

**Comment by marciz** [comment]
Try running simple shiny example given in README. Copy range a1:a5 (column 1 and rows 1 to 5), select and paste it into cell a10. 
I got this error in browser, in Shiny viewer copy-paste didnt not work even for single cell - NA were returned with warrning 'Warning in run(timeoutMs) : NAs introduced by coercion'.
