### ISSUE TITLE
How to reset rhandsontable to NULL? 

### ISSUE THREAD

**Issue by AshutoshAgrahari** [jrowen/rhandsontable#191]
I want to set rhandsontable as NULL after clicking on actionButton.
Error Message:

Browse[1]> input$Table <- NULL
Error in `$<-.reactivevalues`(`*tmp*`, "olsm_mmTable", value = NULL) : 
  Attempted to assign value to a read-only reactivevalues object

let's take example as
output$Table <- renderRHandsontable({
   mtcars
})

observeEvent(input$Button,{
   input$Table <- NULL
})

**Comment by jrowen** [comment]
I'm not sure if it's possible to set a shiny value to `NULL`.  You might have better luck just rendering a table with a `NULL` dataset.
