### ISSUE TITLE
Special character ("&") in the column is causing the crash

### ISSUE THREAD

**Issue by kulshresthaa** [jrowen/rhandsontable#197]
Hi,
I am using rhandsontable to render a editable table in my shiny application. The application works fine when run locally. I have also deployed the app on shinyapps.io and the app crashes on the server when I go to one of the tab on my app that is rendering the rhandsontable. 

After quite a bit of debugging, I figured out that the rhandsontable was causing the crash because in one of the columns of the data, I had  "&". When I removed "&" from the column values, there was no crash. I wonder if the special characters (or only &) in the data is creating some sort of problem, or if there is some other way to configure that particular column. 

I am suing 0.3.4 version of the package!

Interestingly, the app doesn't crash locally but crashes online on shinyapps.io 

Ashish

**Comment by jrowen** [comment]
If you can post a minimal example, we can take a look.  Are your server and local test environment running the same OS?

**Comment by jrowen** [comment]
This appears to be working fine when running locally, so I'd suggest opening a support ticket with shinyapps.io if the problem still persists.
