### ISSUE TITLE
rhot x Shiny: params is null

### ISSUE THREAD

**Issue by Steeefan** [jrowen/rhandsontable#198]
Hi there,

I'm encountering an issue when trying to implement a custom renderer [as mentioned here](https://jrowen.github.io/rhandsontable/#custom_renderer). I'm creating a rhot inside `renderRHandsontable` in which based on a value selected `input$routeID` the rows containing the selected value should be highlighted.

The code I have is this:
```
highlight = as.numeric(rownames(data[data$route_id==input$routeID,]))-1

rhandsontable(
  data,
  height = 300,
  width = '100%',
  row_highlight = highlight,
  stretchH = 'all'
) %>%
hot_cols(renderer = "
  function(instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);

    tbl = HTMLWidgets.widgets.filter(function(widget) {
      return widget.name === 'rhandsontable'
    })[0];

    hrows = tbl.params.row_highlight
    hrows = hrows instanceof Array ? hrows : [hrows]

    if(hrows.indexOf(row) > -1) {
      td.style.backgroundColor = 'pink';
    }

    return td;
  }"
)
```

Running this w/o the call to `hot_cols()` works just fine but with it no table is shown. Using my browser's console I was able to trace it to the fact that I am indeed able to assign `tbl` to the corret table. The `.params` however is empty (`params: null`). This in turn leads me to believe that the code crashes on `hrows = tbl.params.row_highlight` (`VM112:9 Uncaught TypeError: Cannot read property 'row_highlight' of null at eval (eval at window.HTMLWidgets.evaluateStringMember (htmlwidgets.js:732), <anonymous>:9:28)`).

Has anyone encountered sth like this before and is able to help out?

Take care,
-Stefan

**Comment by Steeefan** [comment]
Workaround for determing `hrows`:

```
hot_cols(renderer = paste0("
  function(instance, td, row, col, prop, value, cellProperties) {
    //snip

    hrows = [",
    paste(highlight, collapse=','),
    "];

    //snip
  }")
)
```

**Comment by jpark711** [comment]
Having a same issue. Please let me know if anyone has found a solution to load the params imported from R to the rhandsontable within Shiny.

**Comment by bklingen** [comment]
I just checked with version 0.3.6 and it seems that an R provided params cannot be accessed with rhandsontable in a shiny app. This code for row highlighting used to work fine for highlighting a user-specified row:
```{r}
DF <- data.frame(val = 1:20, bool = TRUE, nm = LETTERS[1:20],
                 dt = seq(from = Sys.Date(), by = "days", length.out = 20),
                 stringsAsFactors = F)

app <- shinyApp(
ui = fluidPage(
  numericInput("myindex", "Highlight Row:", value=1, min = 1, max = 20),
  rHandsontableOutput("hot", height=200, width = 300)
),
server = function(input, output) {
  output$hot <- renderRHandsontable({
    myindex <- input$myindex - 1
    rhandsontable(DF, myindex = myindex) %>%
        hot_cols(renderer = "function(instance, td, row, col, prop, value, cellProperties) {
               Handsontable.renderers.TextRenderer.apply(this, arguments);
               if (instance.params) {
               mhrows = instance.params.myindex;
               mhrows = mhrows instanceof Array ? mhrows : [mhrows];
               }
               if (instance.params && mhrows.includes(row)) td.style.background = 'lightblue';
               "
        )
    })
  }
)
runApp(app)
```

However, even when installing older versions of rhandsontable this code no longer seems to work, so maybe the error is somewhere else.

**Comment by jrowen** [comment]
Please take a look at the Custom Renderer using an R Parameter section at
http://jrowen.github.io/rhandsontable/#custom_renderer.  There's definitely
an opportunity to improve this functionality.

**Comment by bklingen** [comment]
Sorry, my code above was missing a ``}`` and therefor did not work. Using an R provided params works just fine in the newest version 0.3.6 of rhandsontable. Here is code where you can choose with rows to highlight:
```{r}
DF <- data.frame(val = 1:20, bool = TRUE, nm = LETTERS[1:20],
                 dt = seq(from = Sys.Date(), by = "days", length.out = 20),
                 stringsAsFactors = F)

app <- shinyApp(
  ui = fluidPage(
    textInput("myindex", "Chose Row(s) to highlight, separated by a comma:", value="2,3"),
    rHandsontableOutput("hot", height=200, width = 300)
  ),
  server = function(input, output) {
    output$hot <- renderRHandsontable({
      myindex <- as.integer(unlist(strsplit(input$myindex,","))) - 1
      rhandsontable(DF, myindex = myindex) %>%
        hot_cols(renderer = "function(instance, td, row, col, prop, value, cellProperties) {
          Handsontable.renderers.TextRenderer.apply(this, arguments);
          if (instance.params) {
            mhrows = instance.params.myindex;
            mhrows = mhrows instanceof Array ? mhrows : [mhrows];
          }
          if (instance.params && mhrows.includes(row)) td.style.background = 'lightblue';
          }"
        )
    })
  }
        )
runApp(app)
```
This should result in something like this:

![image](https://user-images.githubusercontent.com/4784206/35885055-a46815b6-0b5a-11e8-9743-4a4943f39511.png)

**Comment by jrowen** [comment]
It looks like this is resolved, but please re-open if it's still an issue.
