### ISSUE TITLE
Odd behaviour when using rhandsontable and D3Table in the same app

### ISSUE THREAD

**Issue by ihaddad-md** [jrowen/rhandsontable#20]
A minimal example:

```R
library(shiny)
library(rhandsontable)
library(D3TableFilter)

server = shinyServer(function(input, output, session) {
  output$ht <- renderRHandsontable({
    rhandsontable( data.frame( a = 1:5 ) )
  })
})

ui = shinyUI(fluidPage(
  rHandsontableOutput("ht"),
  d3tfOutput('d3t')
))

runApp( shinyApp(ui, server) )
```

If I run the app as it is, the resulting table will have 7 rows in total with 2 blank rows at the bottom. If I remove the line `d3tfOutput('d3t')`, the table has 5 rows. Any suggestions how one (empty) table manipulates the other?

**Comment by jrowen** [comment]
Are you seeing any error messages in the Javascript console?

**Comment by ihaddad-md** [comment]
Short answer: No! The console is empty.

**Comment by jrowen** [comment]
Sorry it took me a while to get back to you.  I'm not familiar with `D3TableFilter` and am not sure if it will work with a handsontable.  Your example also doesn't appear to be complete, as `output$d3t` is not defined.

**Comment by ihaddad-md** [comment]
Maybe I did not explain the issue very well:

> am not sure if it will work with a handsontable.

`rhandsontable` should only be able to work together with `D3T` in a way, that two distinct tables can coexist correctly within the same application.

> Your example also doesn't appear to be complete, as `output$d3t` is not defined.

Because it was not necessary for the demonstration of this behavior. The problem persists if you add
```R
  output$d3t  <-  renderD3tf({
    d3tf( data.frame( x = LETTERS[1:5] ) )
  })
```
to the `server`.

Maybe I am wrong, but this looks like an unexpected and undesirable side-effect of the usage of both tables in one app:

![image](https://cloud.githubusercontent.com/assets/2493392/8108088/b4c93714-104e-11e5-9446-5a55a238e00f.png)

**Comment by jrowen** [comment]
It appears that `D3TableFilter` adds functions to the input data array, and the logic used to convert the input array of objects to and arrary of arrays was adding these functions to the dataset.  Thanks for reporting, let me know if you run into any other problems.
