### ISSUE TITLE
Changes contains only the last change

### ISSUE THREAD

**Issue by ginberg** [jrowen/rhandsontable#201]
Hi, thanks for developing this package. 

I would like to make multiple changes in the table and then do something with the changed cells.
I am using input$hot$changes$changes and I expected that it would contain all the changes compared to the input (since it is a list), but it seems to only to contain the latest change.
Is it possible to get a list of all changes?

**Comment by jrowen** [comment]
The package doesn't currently keep an inventory of change history, but that could be an interesting enhancement.

**Comment by ginberg** [comment]
okay, thanks that's good to know
