### ISSUE TITLE
issues with shinydashboard

### ISSUE THREAD

**Issue by smartinsightsfromdata** [jrowen/rhandsontable#21]
Some issues with shinydashboard (I confess I haven't tried to reproduce them in "plain" shiny)

I'm sure some of them are due to improper parameter settings from my part?

* The handsontable is not horizontally self-sizing: it hasn't the ability of setting the size of the box (apparently).  Of course it works if I fix an appropriate width (e.g. width=12).
* The horizontal scroll does not include the handsontable head row.  This is pretty pretty confusing as the you loose track of which column header is the right one.
* As expected (due to the settings) there are no row headers, strangley not even row numbers.  But after trying to ender a char in mpg (defined as numeric) row numbers appear from nowhere as row headers.  This would be better if they would be there form the beginning, or not at all.
* No autosizing also vertically.  It is an issue as the unused  space left at the bottom is huge!

```R
library(shiny)
library(shinydashboard)
library(rhandsontable)


header <- dashboardHeader()

sidebar <- dashboardSidebar()

body <- dashboardBody(

          fluidRow(
            box(plotOutput("plot1")),
            box( title = "Controls", width=3,sliderInput("slider", "Number of observations:", 1, 10, 5) )),
          fluidRow( box(title = "Handsontable",rHandsontableOutput("hot") )
          
))

ui <- dashboardPage(header, sidebar, body)


server <- function(input, output) {

  set.seed(122)
  histdata <- rnorm(500)

  values  <-  reactiveValues()
  setHot  <-  function(x) values[["hot"]]  <-  x

  
  output$plot1 <- renderPlot({
    data <- histdata[seq_len(input$slider)]
    hist(data)
  })
  
  
  output$hot = renderRHandsontable({
  if (!is.null(input$hot)) {
    DF  <-  hot_to_r(input$hot)
    setHot(DF)
    rhandsontable(DF) %>%
      hot_table(highlightCol = TRUE, highlightRow = TRUE)
  } else {
    DF  <-  mtcars
    cols <- colnames(DF)
    DF$brand <- row.names(mtcars)
    DF <- DF[,c("brand", cols)]
    rhandsontable(DF, rowHeaders=FALSE) %>%
      hot_table(highlightCol = TRUE, highlightRow = TRUE) %>%
      hot_cols(columnSorting = TRUE, fixedColumnsLeft=1) %>%
      hot_validate_numeric(col = "mpg", allowInvalid=FALSE)
  }
  })
}

shinyApp(ui, server)
```

Thanks!

**Comment by jrowen** [comment]
I see what you mean and will take a look.  Interestingly, if I right click in Chome, inspect and then close the inspect window, the header now looks correct the the horizontal scroll works.

**Comment by jrowen** [comment]
If I take a look at the page source, I can see that the table width and height are being specified as large values in your example.  A cursory check, and I don't see the same when run standalone or via `shiny`.  We might need some special handling for `shinydashboard`; maybe @wch has some ideas.

**Comment by smartinsightsfromdata** [comment]
I've posted the sizing issue on `shinydashboard` as well. On the other hand there is a workaround setting `width` and `height` in the box.

The major issue of the ones reported above remain the "incomplete" horizontal scrolling: without the column header scrolling in-sync with the columns the scrolling (and the ability to 'fix' a column) doesn't really serve its purpose...

**Comment by jrowen** [comment]
Do you have an example of the scrolling issue that doesn't include shinydashboard?

**Comment by smartinsightsfromdata** [comment]
See example below in shiny "speak".   The scrolling in this case happens when you resize the window (in rstudio) or the browser.  I've tried adding / setting differently the various parameters, without any change.

If it is difficult / not possible to have the header scroll in sync with the columns, it would be better to have a way to disable *any* type of native handsontable scrolling, addressing the scrolling issue with:

```R
tags$head(tags$style( type = 'text/css',  '#test{ overflow-x: scroll; }')),
```

With the current setup we would have two types of scrolling active at the same time...

Example in in shiny "speak":

```R
library(shiny)
library(rhandsontable)

ui <- fluidPage(
 mainPanel(
  tabsetPanel(
        tabPanel("hot",
          fluidRow( 
              column(4,rHandsontableOutput("hot")),
              column(8,"experiment")
              ) ),
        tabPanel("barplot",
          fluidRow(
              column(6,plotOutput("plot1")),
              column(4, sliderInput("slider", "Number of observations:", 1, 10, 5) )))
            
  )))

server <- function(input, output,session) {
  
  set.seed(122)
  histdata <- rnorm(500)
  
  values  <-  reactiveValues()
  setHot  <-  function(x) values[["hot"]]  <-  x
  
  output$plot1 <- renderPlot({
    data <- histdata[seq_len(input$slider)]
    hist(data)
  })
  
  output$hot = renderRHandsontable({
    if (!is.null(input$hot)) {
      DF  <-  hot_to_r(input$hot)
      setHot(DF)
      rhandsontable(DF) %>%
        hot_table(highlightCol = TRUE, highlightRow = TRUE)
    } else {
      DF  <-  mtcars
      cols <- colnames(DF)
      DF$brand <- row.names(mtcars)
      DF <- DF[,c("brand", cols)]
      rhandsontable(DF, rowHeaders=FALSE) %>%
        hot_table(highlightCol = TRUE, highlightRow = TRUE) %>%
        hot_cols(columnSorting = TRUE, fixedColumnsLeft=1) %>%
        hot_validate_numeric(col = "mpg", allowInvalid=FALSE)
    }
  })
}

shinyApp(ui, server)
```

**Comment by jrowen** [comment]
I understand the issue you're referring to.  As you noted, I think the [fix](http://docs.handsontable.com/0.16.0/demo-scrollbars.html) is to specify a `width` and `height`.  I'll have to see if there is a way to automatically specify these values for shiny apps.

**Comment by smartinsightsfromdata** [comment]
In my view, *the most painful issue* is the inability to scroll the header alongside the rest of the table, as this has no work around.

Secondly is the problem that in certain cases all of a sudden the standard row header (as 1 2 3) appears out of the  blue.  You can see it with the following sequence:

* Run the `shinydashboard` example.
* Type a character in any mpg cell.  This will be prevented by the `hot_validate_numeric` code.
* Correct the entry with a proper numeric value
* Suddenly out of the blue the row header suddenly appears. It seems that in these cases the `rowHeaders=FALSE` setting is ignored (or it should be re-send?) 

In hindsights, all the other issues around width and height can be worked around just setting proper values (e.g. amending the documentation).

**Comment by jrowen** [comment]
I think we need to set `overflow: auto` and specify a `width` and `height` for this to work as expected.  This seems to be working better
```R
library(shiny)
library(rhandsontable)

ui <- fluidPage(
  mainPanel(
    tabsetPanel(
      tabPanel("hot",
               fluidRow( 
                 column(4,rHandsontableOutput("hot")),
                 column(8,"experiment")
               ) ),
      tags$head(
        tags$style(type="text/css",
                   "div.rhandsontable { overflow: auto; }")
      )
    )
  )
)

server <- function(input, output,session) {
  values  <-  reactiveValues()
  setHot  <-  function(x) values[["hot"]]  <-  x

  output$hot = renderRHandsontable({
    if (!is.null(input$hot)) {
      DF  <-  hot_to_r(input$hot)
      setHot(DF)
      rhandsontable(DF, width = 400, height = 500) %>%
        hot_table(highlightCol = TRUE, highlightRow = TRUE)
    } else {
      DF  <-  mtcars
      cols <- colnames(DF)
      DF$brand <- row.names(mtcars)
      DF <- DF[,c("brand", cols)]
      rhandsontable(DF, rowHeaders=F, width = 400, height = 500) %>%
        hot_table(highlightCol = TRUE, highlightRow = TRUE) %>%
        hot_cols(columnSorting = TRUE, fixedColumnsLeft = 1) %>%
        hot_validate_numeric(col = "mpg", allowInvalid = FALSE)
    }
  })
}

shinyApp(ui, server)
```

**Comment by smartinsightsfromdata** [comment]
An update: the issue of jumping back to numeric row header was my mistake (need to set same parameters for the two definition of the table).

The following code works in `shinydasboard`.  While I haven't been able to set the tag$style, if you set a box size only marginally bigger than the handsontable width, it works.

The annoying thing is that you need to specify it very precisely (out of trial and error - moreover box uses  bootstrap columns, while `rhandsontable` uses pixels - it would be great if they all used pixels).

```R
library(shiny)
library(shinydashboard)
library(rhandsontable)

header <- dashboardHeader(title = "Test")

sidebar <- dashboardSidebar()

body <- dashboardBody(
  fluidRow(
    box(title = "Hot", status = "primary", solidHeader = TRUE, width=8
     ,  rHandsontableOutput("hot")
  )))

ui <- dashboardPage(header, sidebar, body)
  
server <- function(input, output, session) {
  values  <-  reactiveValues()
  setHot  <-  function(x) values[["hot"]]  <-  x
  
output$hot = renderRHandsontable({
  if (!is.null(input$hot)) {
    DF  <-  hot_to_r(input$hot)
    setHot(DF)
    rhandsontable(DF, rowHeaders=FALSE, width = 420, height = 250)  %>%
      hot_table(highlightCol = TRUE, highlightRow = TRUE) %>%
      hot_cols(columnSorting = TRUE, fixedColumnsLeft=1)  %>%
      hot_validate_numeric(col = "mpg", allowInvalid=FALSE)
  } else {

    DF  <-  mtcars
    cols <- colnames(DF)
    DF$brand <- row.names(mtcars)
    DF <- DF[,c("brand", cols)]
    rhandsontable(DF, rowHeaders=FALSE, width = 420, height = 250)  %>%
       hot_table(highlightCol = TRUE, highlightRow = TRUE) %>%
       hot_cols(columnSorting = TRUE, fixedColumnsLeft=1)  %>%
       hot_validate_numeric(col = "mpg", allowInvalid=FALSE)
  }
})

}

shinyApp( ui=ui, server = server)
  `

**Comment by jrowen** [comment]
I committed a couple updates that might fix the scroll problem.  You should only need to specify a height, or if not specified, it will default to `400px`.  You can add `stretchH = "all"` as a param to `rhandsontable` (or `hot_table`) to stretch a smaller table to the full width (see [here](http://docs.handsontable.com/0.16.0/Options.html#stretchH) for more info).

**Comment by smartinsightsfromdata** [comment]
That is exactly it!!

With:
```R
    rhandsontable(DF, rowHeaders=FALSE,  stretchH = "all")  %>%
```
I do not need to set any more width or height in `rhandsontable`:  it is enough to set it in the `shinydashboard` `box`.

Well done.
