### ISSUE TITLE
Github dev version not rendering table

### ISSUE THREAD

**Issue by mmgledhill** [jrowen/rhandsontable#210]
The github dev version of rhandsontable isn't rendering the table as expected (blank where table should be).

I am using demo code as example which runs as expected if I use CRAN package instead.

shiny::runGitHub("rhandsontable", "jrowen", 
             subdir = "inst/examples/rhandsontable_output")

If I install from GitHub then I get the sidebar input, but the table doesn't render. 

I've tried other code examples from documentation (sparkline example) and confirmed Viewer pane doesn't render table either...(but will if I revert back to CRAN version)...

Most recent version that I confirmed it on:
"R version 3.3.3 (2017-03-06)", RStudio Version: ‘1.1.383’, rhandsontable '0.3.4.16'

Any ideas?

**Comment by jrowen** [comment]
I sometimes see this with RStudio and the dev version as well.  Usually clicking the icon to open the table in a browser window resolves the issue.

**Comment by mmgledhill** [comment]
Ok, I tried opening in browser and it is still missing/invisbile. 

This time I used the example code from the sparkline documentation:
```
DF = data.frame(int = 1:10,
                numeric = rnorm(10),
                logical = TRUE,
                character = LETTERS[1:10],
                fact = factor(letters[1:10]),
                date = seq(from = Sys.Date(), by = "days", length.out = 10),
                stringsAsFactors = FALSE)
# add a sparkline chart
DF$chart = sapply(1:10, function(x) jsonlite::toJSON(list(values=rnorm(10))))

rhandsontable(DF, rowHeaders = NULL) %>%
  hot_col("chart", renderer = htmlwidgets::JS("renderSparkline"))
```


If I inspect the source code I can that both have a htmlwidget_container that includes a rhandsontable html-widget and both have the correct application/json data....but the version that is working has a lot more details/info in the htmlwidget.

Version from DEV that isn't working (div#htmlwidget...)::
`<div class="rhandsontable html-widget" id="htmlwidget-85d117c4979620119010" style="width: 100%; height: 100%;"></div>`

Version from CRAN that is visible (div#htmlwidget...):
`<div class="rhandsontable html-widget html-widget-static-bound handsontable htColumnHeaders" id="htmlwidget-3e66e57e0de303c13f51" style="width: 100%; height: 100%;" data-initialstyle="width: 100%; height: 100%;" data-originalstyle="width: 100%; height: 100%;"><div class="ht_master handsontable" style="position: relative;"><div class="wtHolder" style="width: 100%; height: 100%; position: relative;"><div class="wtHider" style="width: 431px; height: 257px;"><div class="wtSpreader" style="left: 0px; top: 0px; position: relative;"><table class="htCore"><colgroup><col style="width: 50px;"><col style="width: 61px;"><col style="width: 53px;"><col style="width: 68px;"><col style="width: 50px;"><col style="width: 99px;"><col style="width: 50px;"></colgroup><thead><tr><th style="height: 25px;"><div class="relative"><span class="colHeader">int</span></div></th><th><div class="relative"><span class="colHeader">numeric</span></div></th><th><div class="relative"><span class="colHeader">logical</span></div></th><th><div class="relative"><span class="colHeader">character</span></div></th><th><div class="relative"><span class="colHeader">fact</span></div></th><th><div class="relative"><span class="colHeader">date</span></div></th><th><div class="relative"><span class="colHeader">chart</span></div></th></tr></thead><tbody><tr><td class="htRight htNumeric">1</td><td class="htRight htNumeric">-1.68</td><td><input tabindex="-1" class="htCheckboxRendererInput" type="checkbox" autocomplete="off" data-row="0" data-col="2"></td><td>A</td><td class="htAutocomplete">a<div class="htAutocompleteArrow">▼</div></td><td class="htAutocomplete">01/10/2018<div class="htAutocompleteArrow">▼</div></td><td><span class="sparklines_r0_c6"><canvas width="46" height="19" style="width: 42px; height: 18px; vertical-align: top; display: inline-block;"></canvas></span></td></tr><tr><td class="htRight htNumeric">2</td><td class="htRight htNumeric">1.69</td><td><input tabindex="-1" class="htCheckboxRendererInput" type="checkbox" autocomplete="off" data-row="1" data-col="2"></td><td>B</td><td class="htAutocomplete">b<div class="htAutocompleteArrow">▼</div></td><td class="htAutocomplete">01/11/2018<div class="htAutocompleteArrow">▼</div></td><td><span class="sparklines_r1_c6"><canvas width="46" height="19" style="width: 42px; height: 18px; vertical-align: top; display: inline-block;"></canvas></span></td></tr><tr><td class="htRight htNumeric">3</td><td class="htRight htNumeric">1.27</td><td><input tabindex="-1" class="htCheckboxRendererInput" type="checkbox" autocomplete="off" data-row="2" data-col="2"></td><td>C</td><td class="htAutocomplete">c<div class="htAutocompleteArrow">▼</div></td><td class="htAutocomplete">01/12/2018<div class="htAutocompleteArrow">▼</div></td><td><span class="sparklines_r2_c6"><canvas width="46" height="19" style="width: 42px; height: 18px; vertical-align: top; display: inline-block;"></canvas></span></td></tr><tr><td class="htRight htNumeric">4</td><td class="htRight htNumeric">1.36</td><td><input tabindex="-1" class="htCheckboxRendererInput" type="checkbox" autocomplete="off" data-row="3" data-col="2"></td><td>D</td><td class="htAutocomplete">d<div class="htAutocompleteArrow">▼</div></td><td class="htAutocomplete">01/13/2018<div class="htAutocompleteArrow">▼</div></td><td><span class="sparklines_r3_c6"><canvas width="46" height="19" style="width: 42px; height: 18px; vertical-align: top; display: inline-block;"></canvas></span></td></tr><tr><td class="htRight htNumeric">5</td><td class="htRight htNumeric">0.63</td><td><input tabindex="-1" class="htCheckboxRendererInput" type="checkbox" autocomplete="off" data-row="4" data-col="2"></td><td>E</td><td class="htAutocomplete">e<div class="htAutocompleteArrow">▼</div></td><td class="htAutocomplete">01/14/2018<div class="htAutocompleteArrow">▼</div></td><td><span class="sparklines_r4_c6"><canvas width="46" height="19" style="width: 42px; height: 18px; vertical-align: top; display: inline-block;"></canvas></span></td></tr><tr><td class="htRight htNumeric">6</td><td class="htRight htNumeric">-0.41</td><td><input tabindex="-1" class="htCheckboxRendererInput" type="checkbox" autocomplete="off" data-row="5" data-col="2"></td><td>F</td><td class="htAutocomplete">f<div class="htAutocompleteArrow">▼</div></td><td class="htAutocomplete">01/15/2018<div class="htAutocompleteArrow">▼</div></td><td><span class="sparklines_r5_c6"><canvas width="46" height="19" style="width: 42px; height: 18px; vertical-align: top; display: inline-block;"></canvas></span></td></tr><tr><td class="htRight htNumeric">7</td><td class="htRight htNumeric">0.89</td><td><input tabindex="-1" class="htCheckboxRendererInput" type="checkbox" autocomplete="off" data-row="6" data-col="2"></td><td>G</td><td class="htAutocomplete">g<div class="htAutocompleteArrow">▼</div></td><td class="htAutocomplete">01/16/2018<div class="htAutocompleteArrow">▼</div></td><td><span class="sparklines_r6_c6"><canvas width="46" height="19" style="width: 42px; height: 18px; vertical-align: top; display: inline-block;"></canvas></span></td></tr><tr><td class="htRight htNumeric">8</td><td class="htRight htNumeric">-1.76</td><td><input tabindex="-1" class="htCheckboxRendererInput" type="checkbox" autocomplete="off" data-row="7" data-col="2"></td><td>H</td><td class="htAutocomplete">h<div class="htAutocompleteArrow">▼</div></td><td class="htAutocomplete">01/17/2018<div class="htAutocompleteArrow">▼</div></td><td><span class="sparklines_r7_c6"><canvas width="46" height="19" style="width: 42px; height: 18px; vertical-align: top; display: inline-block;"></canvas></span></td></tr><tr><td class="htRight htNumeric">9</td><td class="htRight htNumeric">-2.96</td><td><input tabindex="-1" class="htCheckboxRendererInput" type="checkbox" autocomplete="off" data-row="8" data-col="2"></td><td>I</td><td class="htAutocomplete">i<div class="htAutocompleteArrow">▼</div></td><td class="htAutocomplete">01/18/2018<div class="htAutocompleteArrow">▼</div></td><td><span class="sparklines_r8_c6"><canvas width="46" height="19" style="width: 42px; height: 18px; vertical-align: top; display: inline-block;"></canvas></span></td></tr><tr><td class="htRight htNumeric">10</td><td class="htRight htNumeric">0.82</td><td><input tabindex="-1" class="htCheckboxRendererInput" type="checkbox" autocomplete="off" data-row="9" data-col="2"></td><td>J</td><td class="htAutocomplete">j<div class="htAutocompleteArrow">▼</div></td><td class="htAutocomplete">01/19/2018<div class="htAutocompleteArrow">▼</div></td><td><span class="sparklines_r9_c6"><canvas width="46" height="19" style="width: 42px; height: 18px; vertical-align: top; display: inline-block;"></canvas></span></td></tr></tbody></table><div class="htBorders"><div style="left: 0px; top: 0px; position: absolute;"><div class="wtBorder fill" style="width: 1px; height: 1px; display: none; background-color: red;"></div><div class="wtBorder fill" style="width: 1px; height: 1px; display: none; background-color: red;"></div><div class="wtBorder fill" style="width: 1px; height: 1px; display: none; background-color: red;"></div><div class="wtBorder fill" style="width: 1px; height: 1px; display: none; background-color: red;"></div><div class="wtBorder fill corner" style="border: 2px solid rgb(255, 255, 255); border-image: none; width: 5px; height: 5px; display: none; background-color: red;"></div></div><div style="left: 0px; top: 0px; position: absolute;"><div class="wtBorder area" style="width: 1px; height: 1px; display: none; background-color: rgb(137, 175, 249);"></div><div class="wtBorder area" style="width: 1px; height: 1px; display: none; background-color: rgb(137, 175, 249);"></div><div class="wtBorder area" style="width: 1px; height: 1px; display: none; background-color: rgb(137, 175, 249);"></div><div class="wtBorder area" style="width: 1px; height: 1px; display: none; background-color: rgb(137, 175, 249);"></div><div class="wtBorder area corner" style="border: 2px solid rgb(255, 255, 255); border-image: none; width: 5px; height: 5px; display: none; background-color: rgb(137, 175, 249);"></div></div><div style="left: 0px; top: 0px; position: absolute;"><div class="wtBorder current" style="width: 2px; height: 2px; display: none; background-color: rgb(82, 146, 247);"></div><div class="wtBorder current" style="width: 2px; height: 2px; display: none; background-color: rgb(82, 146, 247);"></div><div class="wtBorder current" style="width: 2px; height: 2px; display: none; background-color: rgb(82, 146, 247);"></div><div class="wtBorder current" style="width: 2px; height: 2px; display: none; background-color: rgb(82, 146, 247);"></div><div class="wtBorder current corner" style="border: 2px solid rgb(255, 255, 255); border-image: none; width: 5px; height: 5px; display: none; background-color: rgb(82, 146, 247);"></div></div></div></div></div></div></div><div class="ht_clone_top handsontable" style="left: 0px; top: 0px; width: 1735px; height: 30px; overflow: hidden; position: absolute;"><div class="wtHolder" style="width: 1735px; height: 47px; position: relative;"><div class="wtHider" style="width: 431px;"><div class="wtSpreader" style="left: 0px; position: relative;"><table class="htCore"><colgroup><col style="width: 50px;"><col style="width: 61px;"><col style="width: 53px;"><col style="width: 68px;"><col style="width: 50px;"><col style="width: 99px;"><col style="width: 50px;"></colgroup><thead><tr><th style="height: 25px;"><div class="relative"><span class="colHeader">int</span></div></th><th style="border-left-width: 0px;"><div class="relative"><span class="colHeader">numeric</span></div></th><th><div class="relative"><span class="colHeader">logical</span></div></th><th><div class="relative"><span class="colHeader">character</span></div></th><th><div class="relative"><span class="colHeader">fact</span></div></th><th><div class="relative"><span class="colHeader">date</span></div></th><th><div class="relative"><span class="colHeader">chart</span></div></th></tr></thead><tbody></tbody></table><div class="htBorders"><div style="left: 0px; top: 0px; position: absolute;"><div class="wtBorder fill" style="width: 1px; height: 1px; display: none; background-color: red;"></div><div class="wtBorder fill" style="width: 1px; height: 1px; display: none; background-color: red;"></div><div class="wtBorder fill" style="width: 1px; height: 1px; display: none; background-color: red;"></div><div class="wtBorder fill" style="width: 1px; height: 1px; display: none; background-color: red;"></div><div class="wtBorder fill corner" style="border: 2px solid rgb(255, 255, 255); border-image: none; width: 5px; height: 5px; display: none; background-color: red;"></div></div><div style="left: 0px; top: 0px; position: absolute;"><div class="wtBorder area" style="width: 1px; height: 1px; display: none; background-color: rgb(137, 175, 249);"></div><div class="wtBorder area" style="width: 1px; height: 1px; display: none; background-color: rgb(137, 175, 249);"></div><div class="wtBorder area" style="width: 1px; height: 1px; display: none; background-color: rgb(137, 175, 249);"></div><div class="wtBorder area" style="width: 1px; height: 1px; display: none; background-color: rgb(137, 175, 249);"></div><div class="wtBorder area corner" style="border: 2px solid rgb(255, 255, 255); border-image: none; width: 5px; height: 5px; display: none; background-color: rgb(137, 175, 249);"></div></div><div style="left: 0px; top: 0px; position: absolute;"><div class="wtBorder current" style="width: 2px; height: 2px; display: none; background-color: rgb(82, 146, 247);"></div><div class="wtBorder current" style="width: 2px; height: 2px; display: none; background-color: rgb(82, 146, 247);"></div><div class="wtBorder current" style="width: 2px; height: 2px; display: none; background-color: rgb(82, 146, 247);"></div><div class="wtBorder current" style="width: 2px; height: 2px; display: none; background-color: rgb(82, 146, 247);"></div><div class="wtBorder current corner" style="border: 2px solid rgb(255, 255, 255); border-image: none; width: 5px; height: 5px; display: none; background-color: rgb(82, 146, 247);"></div></div></div></div></div></div></div><div class="ht_clone_left handsontable" style="left: 0px; top: 0px; width: 0px; height: 257px; overflow: hidden; position: absolute;"><div class="wtHolder" style="width: 17px; height: 257px; position: relative;"><div class="wtHider" style="height: 257px;"><div class="wtSpreader" style="position: relative;"><table class="htCore"><colgroup></colgroup><thead><tr></tr></thead><tbody></tbody></table></div></div></div></div></div>`

**Comment by sbihorel** [comment]
Hi,

Rstudio does not render the table with the newly released version 0.3.5. The table is shown upon switching to a browser view.
I do not have this issue with 0.3.4.

**Comment by timelyportfolio** [comment]
I can confirm that I am experiencing the same issue.  Debugging in RStudio Viewer reveals the following problem in [line](https://github.com/jrowen/rhandsontable/blob/master/inst/htmlwidgets/rhandsontable.js#L332).  While default arguments work in R, JavaScript did not get this until ES6 (see [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters)).  RStudio Viewer does not support this yet.  In this case changing to old-timey JavaScript should not be overly difficult.

![image](https://user-images.githubusercontent.com/837910/34808355-0af37ec2-f654-11e7-90b8-3398e8ad217e.png)

**Comment by jrowen** [comment]
Thanks to everyone for the feedback.  We'll get this updated and out on
cran shortly.
