### ISSUE TITLE
Conditional readOnly in empty cells

### ISSUE THREAD

**Issue by akubisch** [jrowen/rhandsontable#214]
Hi,
first of all this is really a great package! What I need for a table now is a specific column to be read-only, except for new entries (which are `<NA>` by default). I tried the following implementation, but the result is just a blank canvas:

```R
library(shiny)
library(rhandsontable)

ui <- fluidPage(
  
  rHandsontableOutput("hot")
   
)

server <- function(input, output) {
  
  data <- reactive({
   
    if (is.null(input$hot))  {
      DF <- data.frame(x = rnorm(10), y = rnorm(10))
    } else {
      DF <- hot_to_r(input$hot)
    }
    DF
  })
  
  output$hot <- renderRHandsontable({
    rhandsontable(data()) %>%
      hot_col("x",renderer = "
                function (instance, td, row, col, prop, value, cellProperties) {
                Handsontable.renderers.NumericRenderer.apply(this, arguments);
                if (!isNaN(value)) {
                  cellProperties.readOnly = TRUE;
                } else {
                  cellProperties.readOnly = FALSE;
                }
            }")
  })
  
}

shinyApp(ui = ui, server = server)
``` 

Now I can't see the problem (except probably for my excessive lack of JS knowledge, of course ;-)). Any help is highly appreciated!

Thank you and all the best,
Alex

**Comment by jrowen** [comment]
You can make a column read-only by passing `readOnly = TRUE` into `hot_col`.  See the [doc here](http://jrowen.github.io/rhandsontable/#read-only).

**Comment by jrowen** [comment]
We added some additional `readOnly` options to the dev version of the library.  See the doc for more details.

**Comment by jrowen** [comment]
Added to v0.3.6.  Thanks for suggesting.

**Comment by akubisch** [comment]
Great, thanks a lot!
