### ISSUE TITLE
IE11 rendering error with rhandsontable 0.3.5

### ISSUE THREAD

**Issue by jpark711** [jrowen/rhandsontable#215]
Hello,

Whenever rhandsontable is loaded on IE11, a blank page is rendered instead and the console on the developer tool yields the following error message. Chrome renders the tables without any problem.

SCRIPT1006: Expected ')'
File: rhandsontable.js, Line: 332, Column: 32

My company only allows CRAN package installation so i have not tested this issue on the latest dev version.

Thank you for the excellent package and support.

Best regards,
Jason

**Comment by bklingen** [comment]
I can confirm that current CRAN package does not render on IE11, but 
works in Chrome, Firefox and Safari.

Bernhard

**Comment by jpark711** [comment]
Thanks Bernhard for the prompt reply.

When are you planning to update CRAN release to support IE11? 

I would love to have it compatible for the shiny app that I have been testing to build.

I appreciate your kind support.

Best,
Jason

**Comment by jrowen** [comment]
This should be fixed in the dev version, and we'll try to get an update on CRAN soon.
```
devtools::install_github("jrowen/rhandsontable")
```

**Comment by jrowen** [comment]
Fixed in v0.3.6.  Thanks for reporting.
