### ISSUE TITLE
Filter and dropdown + digits problem

### ISSUE THREAD

**Issue by adiguzelomer** [jrowen/rhandsontable#219]
Hello,

Thanks again for the great package !

1st - Can we use handsontable JS code to enable filter and dropdown also on rhandsontable and use in shiny app ?
2nd - When i installed the rhandsontable 0.3.5, the rhandsonoutputtable in shiny show all the numbers with the digits 0. And it can not be adjusted bys digits input inside the rhandsontable function. Therefore I again reinstalled v 0.3.4 / 0.3.4. Should i keep using older versions ?

Thanks in advance
Omer,

**Comment by jrowen** [comment]
The second item is fixed in the dev version.  Can you give me some examples
(maybe links from handsontable) of the functionality you'd like to see
added?

**Comment by adiguzelomer** [comment]
thanks for fast reply !
[](https://docs.handsontable.com/pro/1.15.1/demo-filtering.html)
here the filtering link, however I just realized that it comes with the pro version of handsontable. And do you think to put this feature also in rhandsontable in future ? Or if I buy the pro version of the hadnsontable, will it be working with rhandsontable package in shiny?

**Comment by jrowen** [comment]
At this point, you'd have to create your own fork to support the pro
version.

**Comment by jrowen** [comment]
Fixed in v0.3.6.  Thanks for reporting.

**Comment by stevepowell99** [comment]
You can do it by conditionally hiding the rows using conditional formatting http://jrowen.github.io/rhandsontable/#custom_renderer_using_r. 
So you'd have to change `td.style.background = 'pink';` to `td.style.display = 'none';`
The only snag is that if you try to navigate using arrow keys across the hidden rows, the cursor will disappear.
