### ISSUE TITLE
Pass the index of row clicked to R?

### ISSUE THREAD

**Issue by panlanfeng** [jrowen/rhandsontable#22]
Just like the `input$tableId_rows_selected` and `input$tableId_row_last_clicked` in [DT](https://rstudio.github.io/DT/) package. 

Thanks for the nice package!

By the way the link to examples in vignettes break out.

**Comment by jrowen** [comment]
I'm sorry the links are no longer working--I think I've run into a usage limit.  Please take a look at the example below and let me know if this meets your needs.
```
shiny::runGitHub("rhandsontable", "jrowen", subdir = "inst/examples/rhandsontable_corr")
```

**Comment by panlanfeng** [comment]
Thanks, I got it!

To those who might also need this feature: 
we can use `input$tableId_select$select$r` for row index and `input$tableId_select$select$c` for column index.

**Comment by mbacou** [comment]
This works for me as well, but I noticed that when `columnSorting=T` and the user re-order a column, then the row index in rhandsontable no longer corresponds to the index in the underlying data.frame. Is there a way to keep that link?
Thx!

**Comment by jrowen** [comment]
I think this is a bug.  Do you mind submitting a short issue?

**Comment by mbacou** [comment]
@jrowen you mean this is a bug in rhandsometable, right -- not in the JS libs?

**Comment by jrowen** [comment]
Correct.
