### ISSUE TITLE
Instead of selectRows(NULL), use selectRows(list())

### ISSUE THREAD

**Issue by KasperSkytte** [jrowen/rhandsontable#220]
In a shiny app, when clicking a button to clear the selected rows by a simple `observeEvent`, using `selectRows(selected = NULL)` on a `dataTableProxy` throws this warning:
```R
Warning in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```
Using `selectRows(selected = list())` instead causes no warning, however the documentation of `dataTableProxy` says 
> ...you may use NULL to clear existing selections

It does work with `NULL`, but for me it results in a warning spam. Perhaps the documentation should be adjusted? I can provide more details of what I've done, but I think it's sufficient.

**Comment by jrowen** [comment]
I'm not familiar with selectRows and dataTableProxy--these seem to be from
the DT library.

**Comment by KasperSkytte** [comment]
Oh, sorry. You're right :) its the wrong place I posted the issue
