### ISSUE TITLE
shiny fileInput drag and drop disabled with rHandsontableOutput in ui.R

### ISSUE THREAD

**Issue by dylancis** [jrowen/rhandsontable#222]
It took me a while to pinpoint where the issue is coming from but I have now a reproducible example.
shiny fileInput component allows drag and drop file functionality. However this option is cancelling out while the ui contains a rHandsontableOutput widget.

Please check app.R
`
library(shiny)
library(rhandsontable)

ui <- fluidPage(
  
  titlePanel("Uploading Files"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      # Input: Select a file ---- this is where the issue is
      fileInput("file1", "Choose CSV File",
                multiple = TRUE,
                accept = c("text/csv",
                           "text/comma-separated-values,text/plain",
                           ".csv")),
      
      tags$hr(),
      
      checkboxInput("header", "Header", TRUE),
      
      radioButtons("sep", "Separator",
                   choices = c(Comma = ",",
                               Semicolon = ";",
                               Tab = "\t"),
                   selected = ","),
      
      radioButtons("quote", "Quote",
                   choices = c(None = "",
                               "Double Quote" = '"',
                               "Single Quote" = "'"),
                   selected = '"'),
      
      tags$hr(),
      radioButtons("disp", "Display",
                   choices = c(Head = "head",
                               All = "all"),
                   selected = "head")
      
    ),
  
    mainPanel(
      
      tableOutput("contents"),
     # try to drag and drop any file in fileInput field with and without the line below
      rHandsontableOutput("hot")
    )
    
  )
)

server <- function(input, output) {
  
  output$contents <- renderTable({
    req(input$file1)
    
    df <- read.csv(input$file1$datapath,
                   header = input$header,
                   sep = input$sep,
                   quote = input$quote)
    
    if(input$disp == "head") {
      return(head(df))
    }
    else {
      return(df)
    }
    
  })
  
}

shinyApp(ui, server)`

**Comment by ktanizar78** [comment]
I found the same bug. Wondering if it has been fixed.

**Comment by jrowen** [comment]
Do you see a JavaScript error?

**Comment by dylancis** [comment]
Yes I do. See attached.
![36787626-b1a8e76c-1c82-11e8-830f-4d912e649951](https://user-images.githubusercontent.com/4976433/38011317-e48e0814-3254-11e8-9ff6-c939555fa6b8.png)

**Comment by dylancis** [comment]
Hi guys, does anybody know a workaround maybe to get the feature back ?

**Comment by aslomko** [comment]
This issue is now fixed in the latest version of Shiny actually.  Shiny v. 1.1
