### ISSUE TITLE
renderRHandsontable

### ISSUE THREAD

**Issue by RohitRustagi** [jrowen/rhandsontable#223]
Hi,

This code I had written a month ago was working fine, but for some reason, it will not work now. I am using it in conjuction with Shiny, and it renders a hot with renderRHandsontable. For some reason, I think that command is not working. 

Actually, I do not think that the rhandsontable command is working for me either. I tried making a DF and just made it display with rhandsontable, it is just appears as blank.

**Comment by jrowen** [comment]
There was a new release this last weekend.  If you're still having trouble
after upgrading, please post a minimally reproducible example, so we can
take a look.  Thanks.
