### ISSUE TITLE
rhandsontable still doesn't resize in shinydashboard

### ISSUE THREAD

**Issue by nguyenjoshvo** [jrowen/rhandsontable#226]
Hi,

I believed this issue has been brought up in the past, but I still can't make rhandsontable  resize properly in dashboardBody(). The "box" around the table expands, but not the table itself. 

Here are the codes
**ui.R**
```
 dashboardBody(
    
    tabItems(
      tabItem(tabName= "management",
              titlePanel("Working Portal"),
              helpText("For Internal Use Only. This portal allows authenticated users to edit the data."),
              br(),
              rHandsontableOutput("cases")                 
    
    )
  )
```

**server.R**
`    rhandsontable(DF, width = 500, height = 500) %>%
      hot_table(highlightCol = TRUE, highlightRow = TRUE)
`
_*Note that it still doesn't work if I put the handsontable in a box._

**Screenshot:**

![forgit](https://user-images.githubusercontent.com/11356521/35771580-3daae272-08fd-11e8-8091-cf0305fdd225.JPG)

I installed the packages with

`devtools::install_github("jrowen/rhandsontable", dependencies = T, upgrade_dependencies = T)`

Please help me have a look. Thanks!

**Comment by nguyenjoshvo** [comment]
My bad. I figured it out. Just need to add stretchH = "all" in renderRHandsontable.

**Comment by gueyenono** [comment]
This issue is already closed, but I wanted to say that I did not find any `stretchH` argument in the `renderRHandsontable` function. It is in the `hot_table` function instead.
