### ISSUE TITLE
Empty row value is now NULL instead of "NA" with latest package version

### ISSUE THREAD

**Issue by markusdumke** [jrowen/rhandsontable#227]
I have been using this code with rhandsontable 0.3.4 and it worked fine. After upgrading to rhandsontable 0.3.6 this code is now broken because the value of an empty cell is now NULL instead of "NA". Not sure if this is intended behaviour or a bug.

This is the code:
```
library(shiny)
library(rhandsontable)

test.data <- data.frame(a = NA, b = 1, c = NA)

ui <- fluidPage(
  rHandsontableOutput("table")
)

server <- function(input, output, session) {

  output$table <- renderRHandsontable({
    rhandsontable(t(test.data))
  })

  observeEvent(input$table, {
    row.names <- unlist(input$table$params$rowHeaders)
    vals <- unlist(input$table$data)
    names(vals) <- row.names
    # ...
  })
}

shinyApp(ui = ui, server = server)
```

Of course I can insert these lines to overwrite the NULL values with "NA", then my code works again.
```
    dat <- input$table$data
    dat[sapply(dat, function(x) sapply(x, is.null))] <- list(list("NA"))
    vals <- unlist(dat)
```

I used this code to allow a user to edit values of a data.frame.

**Comment by jrowen** [comment]
The default behavior was updated to return `NULL` instead of `NA` (see #153).
