### ISSUE TITLE
Custom renderer not working post Windows/R upgrade

### ISSUE THREAD

**Issue by DiptanilRay** [jrowen/rhandsontable#229]
Previous to the update this particular snippet was functional.
Upgrade from Windows 7 to 10
Upgrade from R version 3.3.3 to 3.4.3

I am trying to edit LB and UB based on values entered in LB_pct and UB_pct.
If I remove the renderer section, this code is working.
Please suggest a remedy

Following is the code snippet:
pc_table <- data.table(Region = c("R1","R2","R3"), value = c(200,400,600),
                        LB_pct = c(-10,-20,-30), LB = c(180,320,420),
                        UB_pct = c(10,20,30), UB = c(220,480,780))
ui = shinyUI(fluidPage(
  
  titlePanel("Handsontable"),
  
  sidebarLayout(
    sidebarPanel(
      helpText("Testing")
    ),
    mainPanel(
      rHandsontableOutput("hot")
    )
  )
))

server = function(input, output) {
  output$hot <- renderRHandsontable({
    rhandsontable(pc_table,
                  selectCallback = T,
                  rowHeaders = NULL,
                  height = 260,
                  strechH="all") %>%
      # Enabling sorting, freeze panes & conditional formatting
      hot_cols(columnSorting = TRUE,fixedColumnsLeft = 1) %>%
      hot_cols(renderer = ("function (instance, td, row, col, prop, value, cellProperties){
                           Handsontable.NumericCell.renderer.apply(this, arguments);
                           if (instance.getColHeader(col) == 'LB'){
                             old_price=instance.getDataAtCell(row,col-2);
                             new_price_pct=instance.getDataAtCell(row,col-1);
                             changed_price = old_price + (old_price*new_price_pct)/100;
                             td.innerHTML=changed_price;
                           }
                           if (instance.getColHeader(col) == 'UB'){
                             old_price=instance.getDataAtCell(row,col-4);
                             new_price_pct = instance.getDataAtCell(row,col-1);
                             changed_price = old_price + (old_price*new_price_pct)/100;
                             td.innerHTML=changed_price;
                           }
                         }"))%>%
      ## formatting the rhandson table
      hot_col(c("Region","value","LB","UB"), readOnly = T) %>%
      hot_context_menu(allowRowEdit = FALSE, allowColEdit = FALSE)
  })
}

shinyApp(ui = ui, server = server)

**Comment by bklingen** [comment]
Now I don't know any javascript, but I know that due to a change in handsontable, the code ``Handsontable.TextCell.renderer.apply(this, arguments);`` that worked in previous versions of rhandsontable had to be changed to ``Handsontable.renderers.TextRenderer.apply(this, arguments);``. So, maybe check if your ``Handsontable.NumericCell.renderer.apply(this, arguments);`` is still the right call. But this is just a suggestion.

**Comment by DiptanilRay** [comment]
This solved the problem. I used 
Handsontable.renderers.NumericRenderer.apply(this, arguments);

Thanks for your help!
