### ISSUE TITLE
no method or default for coercing “character” to “factor”

### ISSUE THREAD

**Issue by Rustastra** [jrowen/rhandsontable#23]
Hi! Some time ago this seemed to work perfectly fine, but now it doesn't. I have a table with mixed datatypes and some blank cells. Then the table is bound to a reactive value, which then is used in calculations. Now, however I either don't get any reaction whatsoever or have the error message no method or default for coercing “character” to “factor”. When I specify useTypes=FALSE, there is reaction, but then I have to work with a messy string. Is there a way to specify that all data in the table should be strings?
THanks!

**Comment by jrowen** [comment]
Does your input table include factor columns?  If so, have you tried converting the factors to characters before passing to the table?

We could look at including an automatic factor conversion--I'm open to ideas here.  The dropdown column type might be a good option.

If you can share a minimally reproducible example, I can probably provide better feedback.

**Comment by Rustastra** [comment]
Can you please tell me how to convert factors to chars? The error happens when user modifies the table. I came aroundd this issue with the following code (decoded the string), but it is defo not the most optimal:
 output$tbl1 <- renderRHandsontable({
    if (!is.null(input$tbl1)) {
      DF5 <-(input$tbl1)$data#hot_to_r(input$tbl1)
	  m<-as.data.frame(matrix(rep(0,14*8),14))
	  for(i in 1:14)
	  {
		  init<-substr(as.character(DF5[i]),6,(nchar(as.character(DF5[i]))-1))
		 init<-gsub("\"","",init,ignore.case=T)
		  ar<-unlist(strsplit(init,","))
		  m[i,1:length(ar)]<-ar
	  }
	DF5<-m
	  rv$cachedTbl<-DF5
	  
      values[["tbl1"]]<-DF5
	  	rhandsontable(DF5,rowHeaders=NULL,useTypes=F) %>%
        hot_cols(renderer = "function (instance, td, row, col, prop, value, cellProperties) {
               Handsontable.renderers.TextRenderer.apply(this, arguments);
               if ((row == 0)||(row==7)) {
               td.style.background = '#BEE2E7';
               } }")
    } else {
      table_to_show<-data.frame(tabletoshow(datain()),stringsAsFactors = F);
	 a<-table_to_show[1:7,1:8]
	 colnames(a)<-c("A","B","C","D","E","F","G","H")
	 b<-table_to_show[1:7,9:16]
	 colnames(b)<-c("A","B","C","D","E","F","G","H")
	 DF5<-rbind(a,b)
	  rv$cachedTbl<-DF5
      values[["tbl1"]]<-DF5
	  	rhandsontable(DF5,rowHeaders=NULL,useTypes=F) %>%
        hot_cols(renderer = "function (instance, td, row, col, prop, value, cellProperties) {
               Handsontable.renderers.TextRenderer.apply(this, arguments);
               if ((row == 0)||(row==7)) {
               td.style.background = '#BEE2E7';
               } }")
    }

  })

**Comment by jrowen** [comment]
Take a look at `?as.data.frame`.  You probably want to set `stringsAsFactors = FALSE`.

A quick way to convert all columns to character could be something similar to
```
do.call(cbind, lapply(mtcars, as.character))
```
You might also want to take a look at the `data.table` package, which is a little "smarter" about data types.

**Comment by Rustastra** [comment]
Yea I tried stringsasfactors. will check the other method too!
tx
