### ISSUE TITLE
hot_col(); using valign results in empty table

### ISSUE THREAD

**Issue by dalekube** [jrowen/rhandsontable#231]
The `valign` argument causes the table to be empty when used in `hot_col()`. As a workaround, I'm able to use a javascript function in the renderer to vertically align my cells to the middle.

This results in an empty table:

`         rhandsontable(x,
                       contextMenu=F,
                       height=400,
                       width=650) %>%
           hot_cols(colWidth=c(55,250,80,90,90),
                    manualColumnResize=T) %>%
           hot_col(col=1:3,
                   readOnly=T,
                   halign="htCenter",
                   valign="htMiddle") %>%
           hot_col(col=4:5,
                   halign="htCenter")`

This properly aligns the cells in my first three columns to the middle, and all of the data is presented in the table as expected:

`       rhandsontable(x,
                       contextMenu=F,
                       height=400,
                       width=650) %>%
           hot_cols(colWidth=c(55,250,80,90,90),
                    manualColumnResize=T) %>%
           hot_col(col=1:3,
                   readOnly=T,
                   halign="htCenter",
                   renderer="function (instance, td, row, col, prop, value, cellProperties) {
                            Handsontable.renderers.TextRenderer.apply(this, arguments);
                            td.style.verticalAlign = 'middle';
                            }
                            ") %>%
           hot_col(col=4:5,
                   halign="htCenter")`

**Comment by jrowen** [comment]
This has been fixed in the `devel` branch and will be included in the next version of the library.
