### ISSUE TITLE
Table selection to persist after clicking outside table (in shiny)

### ISSUE THREAD

**Issue by anders-carlsson** [jrowen/rhandsontable#232]
Hi,
Thanks for an awesome package. 

I'm using a handsontable in a shiny app, where the user plots data based on which cell they click in a table. This works well, but after clicking outside the table, the cell selection (blue frame around the clicked cell) disappears in the table. The user can therefore no longer see which cell they had selected.

In the DT package, in contrast, the cell selection is still visible after interacting with other parts of the application. Is there some way to replicate that behavior?

Ive tried drawing a border around the last selected cell (via reacitveValue), but can't get the table to rerender them after a new selection.

I've also tried to use a custom renderer to try to, for example, change the background of the last selected cell (by passing reactive values), but have not been successful. Any input on how to get that to work would be fantastic!

Many thanks.
Anders

**Comment by jrowen** [comment]
If this is still and issue, could you please post a minimally reproducible example?

**Comment by acbionamic** [comment]
Hi and thanks for getting back on this,

Sorry I was probably unclear, but the behavior I was trying to explain should be present in any example, including the ones at https://jrowen.github.io/rhandsontable/

If I select a cell and then click anything outside the table (including another table) , the blue border indicating the selected cell disappears. For my app, the workflow included clicking the table and then a plot. But after clicking the plot the user could no longer see which cell that was selected. 

A feature where the cell would stay "blue" as long as `input$hot_select` is valid would solve my issue.

**Comment by YsoSirius** [comment]
This is because the `afterDeselect` method is not yet implemented, so the selection will remain until you make a new selection.

Inserting the following in the `afterSelectCallback` callback should work:
```
    x.afterDeselect = function() {
      Shiny.setInputValue(this.rootElement.id+"_select", null);
    };
```

**Comment by eleanor-m** [comment]
The solution posted by YsoSirius didn't seem to work for me, or maybe I just failed to implement it correctly (being a newbie to js). But I was able to solve this by adding `outsideClickDeselects = FALSE` into hot_table() function.
