### ISSUE TITLE
hot_row

### ISSUE THREAD

**Issue by eglekaleckaite** [jrowen/rhandsontable#234]
hot_row <- function(hot, row, readOnly = NULL) 
{
  ct = hot$x$rDataDim[1] # have to change to ct = hot$x$rDataDim[2]
  for (i in seq_len(ct)) {
    if (!is.null(readOnly)) {
      hot = hot %>% hot_cell(row, i, readOnly = readOnly)
    }
  }
  hot
}

This function goes over row number, not column. But it is an easy fix :)

**Comment by jrowen** [comment]
I think #240 fixed this.  Please let me know if you're still experiencing
an issue.

**Comment by jrowen** [comment]
Fixed with #258.
