### ISSUE TITLE
Problem with row addition using dropdown

### ISSUE THREAD

**Issue by JakHou** [jrowen/rhandsontable#237]
I've been experiencing this problem since i started using the rhandsontable. Basically i have a hansontable object, that contains several columns with different types (setting useType as FALSE doesn't solve the issue).

Two columns I'm using are supposed to contain only previously specified values, let's say they are similiar to the LETTERS. Dropdown works, but only until i add rows. 

Error produced by this actions is following:
```
Warning: Error in seq.default: argument 'length.out' must be of length 1
Stack trace (innermost first):
    62: seq.default
    61: seq
    60: genRowHeaders
    59: <Anonymous>
    58: do.call
    57: hot_to_r
    56: observerFunc [C:\Users\jak\Desktop\sf\smartApp/server.R#72]
     1: runApp
```

I've tried to search all around the internet and have found no answer. I can imagine there might be a solution which would need a use of javascript, but I'm not really able to write that code. 

Does anyone have any idea what can i do? I can provide a sample code if needed. 

Thanks

**Comment by jrowen** [comment]
Would you mind posting a minimally reproducible example?

**Comment by Yo-B** [comment]
I had the same. A solution that work for me was given by dni300

> Same here on version rhandsontable_0.3.4.6.
when adding rows to the table, they all get rowlabel '1'
and hot_to_r gives:
```

Warning: Error in row.names<-.data.frame: invalid 'row.names' length
Stack trace (innermost first):
    86: row.names<-.data.frame
    85: row.names<-
    84: rownames<-
    83: <Anonymous>
    82: do.call
    81: hot_to_r

```

> EDIT: When I removed the rownames from the input dataframe of rhandsontable, the problem was solved:

```
rownames(data) <- NULL
rhandsontable(data)
```

[source](https://github.com/jrowen/rhandsontable/issues/166)

**Comment by jrowen** [comment]
This appears to be resolved, but please re-open if this is still an issue.
