### ISSUE TITLE
Right horizontal align for a row?

### ISSUE THREAD

**Issue by hedberg503** [jrowen/rhandsontable#238]
Hello,
I am wondering if it is possible to right align the text for a row. For instance,
```{r}
DF = data.frame(Group = c("TOTAL : All the mumbo jumbo that I can handle","Segment 1","Segment 2","Segment 3"), Recommended = c(10,5,2,3),
                Actual = c(12,6,3,3))

rhandsontable(DF, width = 550, height = 300) %>%
  hot_context_menu(allowRowEdit = FALSE, allowColEdit = FALSE)
```
![image](https://user-images.githubusercontent.com/21182659/37549249-5ce8b1e2-293b-11e8-988f-43bf78c3a920.png)
This is the output I get, but what I would really like is
![image](https://user-images.githubusercontent.com/21182659/37549280-a29f5e84-293b-11e8-8153-c227124844c0.png)

Is there a way to have specific rows cells right align without changing the output every time with right clicks? I know I can change the horizontal alignment of a column but I would like to change the horizontal alignment of rows.

**Comment by jrowen** [comment]
I think the following will work.
```
rhandsontable(DF, width = 550, height = 300) %>%
  hot_context_menu(allowRowEdit = FALSE, allowColEdit = FALSE) %>%
  hot_col(1, valign='htRight')
```
