### ISSUE TITLE
Number of rows doesn't change

### ISSUE THREAD

**Issue by Rustastra** [jrowen/rhandsontable#24]
Hi I have come across another issue. I have a dynamic data frame in Shiny. And again - a week ago it was working fine, and now it doesn't :)
In the dynamic data frame the number of rows changes, and it used to automatically update the number of rows in the handsontable, but now it doesn't

**Comment by jrowen** [comment]
Can you provide a minimally reproducable example of the issue?  Thanks.

**Comment by Rustastra** [comment]
output$hot <- renderRHandsontable({
    if (!is.null(input$hot)) {
      DF1 <- hot_to_r(input$hot)
	  reactv$DF1<-DF1	  
     values[["hot"]]<-DF1
      rhandsontable(DF1,rowHeaders=NULL) %>%
        hot_table(highlightCol = TRUE, highlightRow = TRUE)
    } else {
      DF1 <- data.frame("Year"=0:nrow(rates3()),"Libor"=c(0,(rates3())$LIBOR),"Euribor"=c(0,(rates3())$EURIBOR))
	  reactv$DF1<-DF1
      values[["hot"]]<-DF1
      rhandsontable(DF1,rowHeaders=NULL) %>%
        hot_table(highlightCol = TRUE, highlightRow = TRUE)
    }
  })


######
rates3<-reactive({
	LIBOR1<-c(0.7,1.1,1.6,1.8,2.0,2.1,2.2,2.3,2.451,2.5328);
	EURIBOR1<-c(0.08,0.1,0.2,0.4,0.6,0.8,1.1,1.4,1.6,1.8)
			a<-rep(0,as.numeric(input$years9));
			for(i in 1:as.numeric(input$years9))
			{
				a[i]<-LIBOR1[min(10,i)];
			}			
			b<-rep(0,as.numeric(input$years9));
			for(i in 1:as.numeric(input$years9))
			{
				b[i]<-EURIBOR1[min(10,i)];
			}
return(data.frame("LIBOR"=a,"EURIBOR"=b));
})

####
#years9 is a numeric input

**Comment by Rustastra** [comment]
So I can see that both rates3() and reactv$DF1 change, but no effect on the number of rows

**Comment by Rustastra** [comment]
I see that it actually adds rows in a separate program, so the issue is probably somewhere else...

**Comment by Rustastra** [comment]
Found it, I somehow missed out the overflow:scroll styling... sorry for the hassle!

**Comment by jrowen** [comment]
Since it looks like you're resolved this issue, I'll close.  Please re-open if the problem persists.  Thanks.
