### ISSUE TITLE
can only select first 1000 rows

### ISSUE THREAD

**Issue by survtools** [jrowen/rhandsontable#243]
Hi,

rhandsontable 0.3.6 in Shiny.

Can only copy the first 1000 rows with ctrl A -> ctrl C. 

Cannot manually select a range of rows by selecting the first cell and using shift select after scrolling the page.

Tested in RStudio 1.0.143, Chrome, Firefox and IE on Windows 10.

**Comment by jrowen** [comment]
This is the [default copy limit](https://github.com/handsontable/handsontable/issues/3524), but I think you can override this by including the following in your `rhandsontable` call.
```
copyPaste = list(columnsLimit = <new limit>, rowsLimit = <new limit>)
```
Please re-open if this is still an issue.
