### ISSUE TITLE
Hiding columns in render

### ISSUE THREAD

**Issue by crzysquirrel** [jrowen/rhandsontable#249]
I have a hot DF that is 11x13 and I only want to display the first 3 columns of the DF to the user, where they can input data. I need the other columns to act reactively to the input, but only in the background. Is there a way to make this happen easily or do I need to hack it?

**Comment by buggythepirate** [comment]
@crzysquirrel I have a similar problem and I had a closer look at the code. 

TL;DR Version: With the current version of rhandsontable it is not possible.

Long version: Handsontable supports this feature [(See here)](https://docs.handsontable.com/pro/4.0.0/demo-hiding-columns.html) The current version delivered with the rpackage already supports this feature. However, it has not been implemented in the package yet. So in principle you could add it to the package. However, I lack the required javascript skills to add it in a justifiable time frame. So I'll do a quick not-so-nice hack in R instead.

Maybe @jrowen can add it in a future release.

**Comment by pythiantech** [comment]
@buggythepirate could you get your hack going for this?

**Comment by pythiantech** [comment]
@jrowen is this issue likely to be addressed?

**Comment by pythiantech** [comment]
I finally discovered something that works. You can specify `colWidths` as 0.1 for your column. It will not render but will still be available for other operations on it. I have a table with 19 columns and I don't wish to display the last three. This worked:

`hot_cols(colWidths = c(rep(150,16),rep(0.1,3)))`

**Comment by dylancis** [comment]
it will be nice to have that feature indeed.

**Comment by jrowen** [comment]
Unfortunately, this is a `handsontable` [pro feature](https://handsontable.com/docs/6.2.2/demo-hiding-columns.html), so we won't be able to implement it.  If it becomes part of the Community version, the following should work.
```
MAT = matrix(rnorm(26 * 26), nrow = 26)
rhandsontable(MAT, hiddenColumns = list(columns=c(2, 3), indicators = TRUE))
```

**Comment by sbihorel** [comment]
> I finally discovered something that works. You can specify `colWidths` as 0.1 for your column. It will not render but will still be available for other operations on it. I have a table with 19 columns and I don't wish to display the last three. This worked:
> 
> `hot_cols(colWidths = c(rep(150,16),rep(0.1,3)))`

This works also hot_col for single column interaction
```
hot_col(col = 'myColumn', colWidths=0.1)
```

**Comment by Teebusch** [comment]
Unfortunately, setting `colWidths=0.1` is not a fix as it creates new issues. 

In the image below, the "hidden" column is the rightmost column of the table and it contains a rather long uid: 
<img width="275" alt="image" src="https://github.com/jrowen/rhandsontable/assets/3391092/0a05cfe4-a067-4bae-9873-416cc9ad8311">

- The border is wider where the hidden column would be (compare borders 1 and 2). (It looks worse "live" than in the screenshot)
- The row height calculation incorporates the content of the "hidden" column (see 3). In the example, the row would be just one line high if the "hidden" column wasn't hidden. 

## Expanded solution

A more complete solution is to use a custom renderer that sets `display: none` for all cells in the column with css:
```r
hide_column <- "function(instance, td, row, col, prop, value, cellProperties) {
  Handsontable.renderers.TextRenderer.apply(this, arguments);
  td.style.display = 'none';
  return td;
}"

# ...
rhandsontable::hot_col(
  col = 'my_hidden_column', 
  renderer = hide_column,         # use custom renderer for cells
  colWidths = 0.1                 # hide the header
)
```

However, it's still not perfect, as the header is not hidden by the custom renderer (but only made smaller by `colWidths=0.1`). Thus, the border of the header still looks "off": 
<img width="246" alt="image" src="https://github.com/jrowen/rhandsontable/assets/3391092/c4b1d5fd-775a-4625-86ba-c19688b7ebd2">

If the hidden column is simply the last column, as in this example, we can hide the double border by adding the following to the css:
(If there are multiple handsontables on the page, you might want to add a wrapper div and use a more specific selector)
```css
.handsontable thead tr th:last-of-type,
.handsontable tbody tr td:last-of-type {
    border-width: 0;
}
````
Interestingly, you _cannot_ just set `display: none` here and get rid of the custom renderer and `colWidths=0.1` altogether. If you do this, the row height will be wrong again. Apparently row heights are calculated before external stylesheets are applied.

<img width="255" alt="image" src="https://github.com/jrowen/rhandsontable/assets/3391092/388c3b11-cb86-43ad-b794-f85edde0ada9">

This seems to work, but is is a pretty awkward solution, to say the least.

---

FYI, I tested @jrowen 's suggestion above
```r
MAT = matrix(rep(1:3, 2), nrow = 2, byrow = TRUE)
rhandsontable::rhandsontable(MAT, hiddenColumns = list(columns=c(1, 2), indicators = TRUE))
````
and it doesnt hide columns. So I suppose, the feature has not yet made it into the free version.
