### ISSUE TITLE
Issue with heatmap & format 

### ISSUE THREAD

**Issue by viewasia** [jrowen/rhandsontable#250]
if you have a MxN dataframe and try to format one column with % and another with currency, while also trying to render a heatmap the formatting gets messed up & the heatmap does not render correctly in R & Shiny

example: 

    output$d1 <- renderRHandsontable ({
        rhandsontable(abcDF, 
                      search = TRUE, height = 500)%>%
            hot_heatmap(color_scale = c('#FFFFFF', '#006600')) %>%
            hot_col(2, format="$0,0.00") %>%
            hot_col(1, format="$0,0.00") %>%
            hot_col(3:10, format="0.%") 
  })
Any suggestions on how to address this?  abcDF contains values ranging from 0.000 to 99.999 in about 10 columns and 31 rows.

Thanks.

**Comment by jrowen** [comment]
This should now be fixed in the `devel` branch and will be included in an upcoming release.
