### ISSUE TITLE
Rhandsontable no work on Hugo site

### ISSUE THREAD

**Issue by Kaiwenteoh** [jrowen/rhandsontable#251]
Rhandsontable works well in my rstudio viewer when it is rendered. However when I push to github and deploy on netlify, table disappear on Hugo site. 

Can you help me with this? Thank you in advance!

**Comment by jrowen** [comment]
I'm sorry, I'm not familiar with Hugo, so I won't be able to assist.  I'd suggest pulling up the Chrome debugger window (Ctrl + Shift + i) to see if you are seeing any errors.
