### ISSUE TITLE
Allwoing only single selection in Logical column of a rhandsontable

### ISSUE THREAD

**Issue by Yogitha785** [jrowen/rhandsontable#254]
I am not able to figure out any way to restrict user for only one selection(TRUE) in logical column of rhandsontable. Is this functionality already inplace or is there any other method to get this?

**Comment by ElsaMes** [comment]
have you tried hot_validate_character?

See https://jrowen.github.io/rhandsontable/#character_columns
Validation > character for an example

:)

**Comment by jrowen** [comment]
Please re-open if this is still an issue.
