### ISSUE TITLE
Adding rows via the context menu doesn't extend the table

### ISSUE THREAD

**Issue by juancentro** [jrowen/rhandsontable#26]
Hi, in my code when I add a row via the context menu the table doesn't expand.
The rows are added (I see them in the data.frame if I debug) but they aren't displayed.
In the examples they are displayed (the table extends) but I can't find the property that controls this feature.
It seems related to the boundaries of the table. For example, If I have a column with a autocomplete feature, the menu doesn't go beyond the table (it's cut). It seems that the table can't draw anymore than it's initial boundary. I'm using a sidebar layout

**Comment by jrowen** [comment]
If you can post a minimally reproducible example, I can try to take a look.

**Comment by juancentro** [comment]
I'm trying, but haven't been able to repro yet. Please keep it open while I try to create an example.

**Comment by jrowen** [comment]
Are you setting the table width and height in your shiny app?

**Comment by juancentro** [comment]
I'm doing it now, setting the height to a number high enough that gives me a good amount of rows. This is my poor kludge.

**Comment by jrowen** [comment]
That was going to be my suggestion.  Right now I'm not aware of a way to have the widget size grow dynamically and am open to ideas and suggestions.

**Comment by Deleetdk** [comment]
I had the same issue today. But when I reset the Shiny, I could not get it to reproduce. It happened when I added a new below the current last row.

**Comment by jrowen** [comment]
The widget doesn't currently resize when adding rows or columns, so you'll
want to specify a big enough initial size to accommodate additions.  This
is something I'm looking to improve.

**Comment by jrowen** [comment]
I think I found a resize bug in v0.2.  I made some changes and I'd appreciate your feedback.  You can install using
```
devtools::install_github("jrowen/rhandsontable", ref = "context_menu")
```

**Comment by juancentro** [comment]
Seems better to me, I sometimes notice that when I open the app the table
appears collapsed, haven't experienced it with this build. A little more
time using it will tell.

**Comment by Deleetdk** [comment]
Using the old version, I managed to produce the bug again. 

![table extension error](https://cloud.githubusercontent.com/assets/6759913/9654058/956ddfa6-51ed-11e5-9797-c7f4543347e5.png)

I'll let you know if I get a bug with the new version.

**Comment by jrowen** [comment]
These updates are now part of the dev version (v0.2.1) and will post to CRAN shortly.  Please re-open this issue if you run into problems with the latest version.  Thanks.
