### ISSUE TITLE
widget search logic help

### ISSUE THREAD

**Issue by hhellemons** [jrowen/rhandsontable#265]
Hi Jonathan, how do I incorporate your note on the the search logic when using multiple widgets. "When using this approach in a shiny app or in a document with more than one widget, the widget search logic will need to be more robust."

`HTMLWidgets.widgets.filter(function(widget) {
  // this should match the table id specified in the shiny app
  return widget.name === "hot"
})[0];`

I assume that I need to adjust this part:

`tbl = this.HTMLWidgets.widgets[0]` into ?

many thanks in advance!

**Comment by timelyportfolio** [comment]
@hhellemons Not sure I fully understand the objective or context, but to access the `rhandsontable` widget, we can

```
HTMLWidgets.find('#elid...the htmlwidget/shiny element id');
```

Similarly to get the `handsontable`, we can

```
HTMLWidgets.find('#elid...the htmlwidget/shiny element id').hot;
```

`HTMLWidgets.find` works much like `$/jQuery` with css selectors.  Does this help answer the question?

**Comment by jrowen** [comment]
Please re-open if this is still an issue.

**Comment by JoshOBrien** [comment]
For anyone else experiencing the same problem as the OP, [this StackOverflow answer](https://stackoverflow.com/a/42027600/980833) demonstrates an alternative approach to getting an *rhandsontable* custom renderer working in shiny. I, for one, found it much easier to implement than the tangential comment quoted above from [this section](https://jrowen.github.io/rhandsontable/#custom_renderer) of the *rhandsontable* introduction.
