### ISSUE TITLE
Multiple Column Sort

### ISSUE THREAD

**Issue by him4u324** [jrowen/rhandsontable#267]
I am impressed with rhandsontable but only thing which keeps me away from it and stick to datatable is **multiple column sorting** option. I have checked the handsontable js option but no headway.
looking forward for your response on how to enable multiple sort on rhandsontable.

**Comment by jrowen** [comment]
Since `rhandsontable` is just a wrapper over `handsontable`, the latter project will first need to implement multi-column sorting.  I'd suggest filing an [enhancement request](https://github.com/handsontable/handsontable) with `handsontable`.
