### ISSUE TITLE
Using rhandsontable to display/edit multiple files

### ISSUE THREAD

**Issue by kdp4be** [jrowen/rhandsontable#27]
Hi,

I'm using rhandsontable to display and edit .csv files in a Shiny app, and the file that is displayed in the table depends on the value of  selectInput. When I first load the app, if I change the file I want to display using the selectInput, the rhandsontable changes properly. But once I double click into the table or make any edits, changing the value of selectInput no longer changes what .csv file is displayed in the rhandsontable, it just displays whatever file was shown when I clicked into/edited it. I know this is because once I've clicked/edited, the rHandsontableOutput is no longer considered null, but is there a way around this so I can use the same table to edit multiple files? Setting `input$file <- NULL` seems like it would solve it, but isn't possible.

I have the following in my shiny server.R:
```R
hotvalues = reactiveValues()
setHot = function(x) hotvalues[["file"]] <<- x
rHandsontableOutput("file")
```
And my `output$file <- renderRHandsontable` looks generally like this:
```R
if (!is.null(input$file)) {
  hotdf = hot_to_r(input$file)
  setHot(hotdf)
  rhandsontable(hotdf) %>% 
    hot_table(highlightCol = TRUE, highlightRow = TRUE,
              allowRowEdit=FALSE, allowColEdit=FALSE)
} else {
  hotdf <- read.csv(filefromselectInput), stringsAsFactors = FALSE)
  setHot(hotdf)
  rhandsontable(hotdf) %>% 
    hot_table(highlightCol = TRUE, highlightRow = TRUE,
              allowRowEdit=FALSE, allowColEdit=FALSE)
}
```

**Comment by jrowen** [comment]
It's difficult to debug without a working example, but my guess is you need a `reactive` function to initiate the `reactiveValue` when the `selectInput` changes.  It might be useful to use `shiny::showReactLog` to debug what happens when you change the `selectInput`.

**Comment by kdp4be** [comment]
runGist is bugging for me right now, but I have a short example [here](https://gist.github.com/kdp4be/5b09299d3ff455451b47). Should I be using setHot as a reactive function that changes based on selectInput? Right now if I double click into the table or edit anything, it gets stuck on that one file.

**Comment by jrowen** [comment]
I think an approach like the example below should work.  
```R
library(shiny)
library(rhandsontable)

df_a = data.frame(a=1, b=2, c=3)
df_b = data.frame(d=4, e=5, f=6)

ui = shinyUI(fluidPage(

  titlePanel("rhandsontable example"),

  sidebarLayout(
    sidebarPanel(
      selectInput("val", label = "select", choices= c("df_a", "df_b"))
    ),

    mainPanel(
      rHandsontableOutput("file")
    )
  )
))

server = shinyServer(function(input, output) {
  val_ = NULL

  output$file <- renderRHandsontable({
    if (is.null(input$file) || val_ != input$val) {
      val_ <<- input$val
      hotdf <- get(input$val)
    } else if (!is.null(input$file)) {
      hotdf = hot_to_r(input$file)
    }

    rhandsontable(hotdf) %>%
      hot_table(highlightCol = TRUE, highlightRow = TRUE,
                allowRowEdit=FALSE, allowColEdit=FALSE)
  })
})

shinyApp(ui = ui, server = server)
```
Defining `val_` as a `reactiveValue` will lead to the behavior you're seeing, where by the table no longer responds to `selectInput` after the table data is updated.  This because the `renderRHandsontable` function gets called twice: the first time as a reload event and the second time as a change event using the original input, which overwrites the reload.

**Comment by kdp4be** [comment]
I did notice the `renderRHandsontable` getting called twice but didn't realize that the `reactiveValue` was causing that. It works now! Thanks for your help.

**Comment by lucacerone** [comment]
Hi @jrowen , your proposed solution worked in my case too ( #46 ).
However I must admit that I can't understand why storing the state of the inputID in a reactiveValue won't work (which is what I was doing).

For example why if I modify the example above like this won't work (i.e. why it gets called twice as you mentioned in one of your previous answers?)

```r
server = shinyServer(function(input, output) {
rv <- reactiveValues(val_ = NULL)

  output$file <- renderRHandsontable({
    if (is.null(input$file) || rv$val_ != input$val) {
      rv[["val_"]] <<- input$val
      hotdf <- get(input$val)
    } else if (!is.null(input$file)) {
      hotdf = hot_to_r(input$file)
    }

    rhandsontable(hotdf) %>%
      hot_table(highlightCol = TRUE, highlightRow = TRUE,
                allowRowEdit=FALSE, allowColEdit=FALSE)
  })
})

shinyApp(ui = ui, server = server)
```

In renderRHandsontable I use input$val, which should make the code react to changes in its value, right? So I expect that if I change input$var, renderRHandsontable is triggered.

Probably I misunderstood reactiveValues, but what am I missing here?

**Comment by lucacerone** [comment]
OK I finally got it. The first time renderRHandsontable is triggered by the change in input$tbl,
but in there we also modify rv$val_, so renderRHandsontable is triggered a second time, which is what causes the issue! 

Thanks again for the help!

**Comment by yosch123** [comment]
Hi @jrowen , I've been having a similar issue trying to edit two different rhandsontables with the selectInput. I tried your example code but when I run it and update df_a, then select df_b, then go back to df_a, it gives me back the original, pre-edited df_a. The only thing I changed in the code was allowColEdit=FALSE, since with that in it gave me the error 
formal argument "allowColEdit" matched by multiple actual arguments
