### ISSUE TITLE
updateSliderInput broken

### ISSUE THREAD

**Issue by benphil** [jrowen/rhandsontable#275]
Hi,
I have a problem with using rhandsontable and trying to use the updateSliderInput function in shiny.
If I use a rhandsontable triggering a update to a slider via updateSliderInput instead of updating the slider it creates a new text field. Below is an example.

```
library(shiny)
library(rhandsontable)
ui <- fluidPage(
  sliderInput("testslider","Test",0,10,5),
  actionButton("do", "Click Me"),
  rHandsontableOutput("hot")  
)
server <- function(input, output, session) {
  output$hot <- renderRHandsontable({
    DF = data.frame(val = 1:10, bool = TRUE, big = LETTERS[1:10],
                    small = letters[1:10],
                    dt = seq(from = Sys.Date(), by = "days", length.out = 10),
                    stringsAsFactors = FALSE)
    return(rhandsontable(DF))
  })
  observeEvent(input$do, {
    updateSliderInput(session,inputId = "testslider" ,value = 10,
                      min = 0, max = 10, step = 0.1)
  })
}
# Run the application 
shinyApp(ui = ui, server = server)
```

Any advice/fix would be great!
Thanks!

**Comment by AshesITR** [comment]
I can't reproduce this on R-win 3.5.1 x64 running rhandsontable 0.3.6 and shiny 1.1.0
Can you post a sessionInfo()?

**Comment by artofstat** [comment]
I could reproduce it, it brings up an unexpected textbox, see image:

![image](https://user-images.githubusercontent.com/42886499/47592675-498f5800-d942-11e8-8eeb-9900ba6d9a5b.png)


Here is the sessionInfo()
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rhandsontable_0.3.6 shiny_1.1.0        

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18    digest_0.6.17   later_0.7.5     mime_0.5        R6_2.2.2        xtable_1.8-3   
 [7] jsonlite_1.5    magrittr_1.5    rlang_0.2.2     promises_1.0.1  tools_3.5.1     htmlwidgets_1.2
[13] httpuv_1.4.5    yaml_2.2.0      compiler_3.5.1  htmltools_0.3.6
>

**Comment by AshesITR** [comment]
@artofstat What's the browser? Looks like edge?
I'm running the latest Firefox version on Windows 7

**Comment by artofstat** [comment]
Browser was Chrome.

**Comment by AshesITR** [comment]
@artofstat What‘s your IE Version?
I think the RStudio Viewer is just an embedded IE frame given how quirky it is compared to a regular browser.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrowen** [comment]
I'm not seeing an issue when using an external browser (Chrome) with the latest version of `rhandsontable`.  If you're running into problems with the RStudio Viewer, I'd suggest logging an issue with that project.  

Please re-open if you are still running into problems.
