### ISSUE TITLE
Broken links in the vigette

### ISSUE THREAD

**Issue by Deleetdk** [jrowen/rhandsontable#28]
http://rpubs.com/jrowen/intro_rhandsontable

The links to the shiny examples do not work. Instead they return an XML error.

**Comment by jrowen** [comment]
I ran into a usage limit on rpubs, so in the dev version of the vigette I switched to the `shiny::runGitHub` approach
```
shiny::runGitHub("rhandsontable", "jrowen", subdir = "inst/examples/rhandsontable_output")
```
Thanks for reporting and let me know if this approach doesn't work for you.
