### ISSUE TITLE
Search Functionality Not Working

### ISSUE THREAD

**Issue by StevenMMortimer** [jrowen/rhandsontable#285]
The search box is not highlighting matches in the table. 

```
shiny::runGitHub("rhandsontable", "jrowen", 
             subdir="inst/examples/rhandsontable_search")
```

<img width="512" alt="screen shot 2018-12-13 at 5 33 34 pm" src="https://user-images.githubusercontent.com/5299737/49971687-473a8a80-fefd-11e8-921a-603efda0bd48.png">

**Comment by jrowen** [comment]
This has been fixed on the `devel` branch and will included in an upcoming release.

**Comment by StevenMMortimer** [comment]
@jrowen Awesome! Thanks!
