### ISSUE TITLE
Question concerning the input

### ISSUE THREAD

**Issue by Deleetdk** [jrowen/rhandsontable#29]
I could not find an example of actually getting the input from the table. For those who are wondering, it is just like the other inputs using input$ID, where ID is the ID of the object.

My question is whether there is some clever method of getting the table in a useful format. Right now it is returned as a list of lists instead of matrix/data.frame which I was expecting.

Here's the input returned from a simple 3x2 matrix:

```
$data
$data[[1]]
$data[[1]][[1]]
[1] "1"

$data[[1]][[2]]
[1] "4"


$data[[2]]
$data[[2]][[1]]
[1] "2"

$data[[2]][[2]]
[1] "5"


$data[[3]]
$data[[3]][[1]]
[1] "3"

$data[[3]][[2]]
[1] "6"



$changes
$changes$event
[1] "afterChange"

$changes$changes
$changes$changes[[1]]
$changes$changes[[1]][[1]]
[1] 2

$changes$changes[[1]][[2]]
[1] 1

$changes$changes[[1]][[3]]
[1] 0

$changes$changes[[1]][[4]]
[1] "6"




$params
$params$data
$params$data[[1]]
$params$data[[1]][[1]]
[1] "1"

$params$data[[1]][[2]]
[1] "4"


$params$data[[2]]
$params$data[[2]][[1]]
[1] "2"

$params$data[[2]][[2]]
[1] "5"


$params$data[[3]]
$params$data[[3]][[1]]
[1] "3"

$params$data[[3]][[2]]
[1] "6"



$params$rClass
[1] "matrix"

$params$rColClasses
[1] "numeric"

$params$selectCallback
[1] FALSE

$params$colHeaders
NULL

$params$rowHeaders
NULL

$params$columns
$params$columns[[1]]
$params$columns[[1]]$type
[1] "text"


$params$columns[[2]]
$params$columns[[2]]$type
[1] "text"



$params$width
NULL

$params$height
NULL

$params$contextMenu
$params$contextMenu$items
$params$contextMenu$items$row_above
named list()

$params$contextMenu$items$row_below
named list()

$params$contextMenu$items$hsep1
[1] "---------"

$params$contextMenu$items$col_left
named list()

$params$contextMenu$items$col_right
named list()

$params$contextMenu$items$hsep2
[1] "---------"

$params$contextMenu$items$remove_row
named list()

$params$contextMenu$items$remove_col
named list()

$params$contextMenu$items$hsep3
[1] "---------"

$params$contextMenu$items$undo
named list()

$params$contextMenu$items$redo
named list()

$params$contextMenu$items$hsep4
[1] "---------"

$params$contextMenu$items$make_read_only
named list()

$params$contextMenu$items$alignment
named list()



$params$allowRowEdit
[1] TRUE

$params$allowColEdit
[1] TRUE

$params$csvFileName
[1] "download.csv"
```

Now, the first part of this long list contains the actual numbers. One can convert it to a matrix like this:

    table_rows = length(input$table[[1]])
    print(matrix(unlist(input$table[[1]]), nrow = table_rows, byrow = T))

```
     [,1] [,2]
[1,] "1"  "4" 
[2,] "2"  "5" 
[3,] "3"  "6"
```

Still, is there some less messy way that I am overlooking?

**Comment by jrowen** [comment]
Take a look at this example
```
shiny::runGitHub("rhandsontable", "jrowen", subdir = "inst/examples/rhandsontable_portfolio")
```
There is a helper function called `hot_to_r` that can assist with the conversion.  This process is still evolving, so suggestions are very welcome.

**Comment by Deleetdk** [comment]
Thanks.

Could you add an example with the use of the input from the table? The current examples are not entire Shiny apps and do not show the use of input, unless I missed something.

**Comment by jrowen** [comment]
The portfolio, frontier and datafile examples use the inout.  If you change the table, it will trigger a recalc/reaction.  The first two will recalculate a data series that's then presented in a chart.  Let me know if you have any additional questions.

**Comment by jrowen** [comment]
Has this been resolved?

**Comment by Deleetdk** [comment]
Yes, my mistake.
