### ISSUE TITLE
FR: Enabling promises

### ISSUE THREAD

**Issue by trafficonese** [jrowen/rhandsontable#291]
Can we enable rhandsontable to accept promises?

The package DT already has that functionality, so the following example will only render 1 table with DT and leave the rhandsontable blank:

```
library(shiny)
library(rhandsontable)
library(DT)
library(promises)
library(future)
plan(multiprocess)

ui <- fluidPage(
  h4("rhandson"),
  rHandsontableOutput("table1"),
  h4("DT"),
  DT::dataTableOutput("table2")
)

server <- function(input, output, session) {

  dataTable <- reactive({
    future({
      Sys.sleep(1)
      mtcars
    })
  })

  output$table1 <- renderRHandsontable({
    dataTable() %...>%
      head(2)
  })
  
  output$table2 <- DT::renderDataTable({
    dataTable() %...>%
      head(3)
  })
}

shinyApp(ui, server)
```

**Comment by jrowen** [comment]
I agree that this would be a great enhancement.  Please let us know if you run across any references on how to add `promises` support to a `htmlwidget`.

**Comment by trafficonese** [comment]
Maybe the implementation of DT or plotly could be helpful?

https://github.com/rstudio/DT/blob/ac6802a4f5b84b60d7db918ec55eee051d4658b9/R/shiny.R#L53
https://github.com/ropensci/plotly/blob/390884105372c2c0daa3608b4a24e117051c66e1/R/shiny.R#L37

**Comment by YsoSirius** [comment]
I think there is nothing to do, as it already accepts promises. There is just something missing/wrong in the given example.

Exchanging the `renderRHandsontable`-part to the part below works for me:

```
  output$table1 <- renderRHandsontable({
    dataTable() %...>% {
      rhandsontable(head(.))
    }
  })
```

The data must be wrapped in `rhandsontable` to work.
