### ISSUE TITLE
hot_cols(format = '0') not converting numbers to integers

### ISSUE THREAD

**Issue by automa7** [jrowen/rhandsontable#292]
I am having problems after I updated rhandsontable with the hot_cols() function. It is not forcing the format on to the columns. if I do the following:  `rhandsontable(mtcars) %>% hot_cols(format = '0')` the numbers still show as decimals.

**Comment by jrowen** [comment]
I think the following will allow you to format as integers
```
rhandsontable(mtcars) %>% hot_cols(format = '1')
```
`handsontable` uses `numbro.js` for [formatting](http://numbrojs.com/format.html#format).

**Comment by automa7** [comment]
@jrowen solution works. But this is only necessary on rhandsontable 0.3.7, in 0.3.6 I was using '0' as described in numbro.js [documentation](http://numbrojs.com/old-format.html#numbers).

Thanks and Regards!
