### ISSUE TITLE
Using values in R variables for conditional formatting

### ISSUE THREAD

**Issue by gueyenono** [jrowen/rhandsontable#295]
My goal is to be able to use values contained within an R variable to perform conditional formatting in a `rhandsontable`. Let's assume that I want to develop the following game as a Shiny app.

I have 3 x 3 data frame containing the numbers from 1 to 9 in a random order.

    set.seed(123)
    df_correct <- as.data.frame(matrix(sample(9), nrow = 3, ncol = 3))
    df_correct
    
      V1 V2 V3
    1  3  6  2
    2  7  5  8
    3  9  1  4

When the Shiny app loads, the user is presented with an empty 3 x 3 `rhandsontable` as well as a Submit button. The objective of the game is to successfully find the number "hidden behind each cell".

What I am attempting to achieve is to dynamically color-code the cells based on the user inputs when the Submit button is clicked (red = wrong, green = correct, light grey = empty). Even though I do not know how to code in Javascript, [the tutorial on the `rhandsontable` package][1] provides code samples, which are relatively easy to understand and tweak. I proceed in  3 steps:

1. Identify empty cells

2. Identify cells with correct user inputs

3. Identify cells with wrong user inputs
 
Each of these steps results in an `R` object containing indices (i.e. row and column number). I do not know how to pass this information to the `hot_cols()` function (more specifically to the `renderer` argument that takes in Javascript code). Your help is very much appreciated.

  [1]: https://jrowen.github.io/rhandsontable/

    library(shiny)
    library(rhandsontable)
    library(magrittr)
    
    ui <- fluidPage(
       
       titlePanel("Simple game"),
       
       rHandsontableOutput("table"),
       
       actionButton("button", "Submit")
    
    )
    
    server <- function(input, output) {
    	
    	tables <- reactiveValues(
    		df_correct = {
    			set.seed(123)
    			as.data.frame(matrix(sample(9), nrow = 3, ncol = 3))
    		},
    		df_user = rhandsontable(
    			data = as.data.frame(matrix(NA_integer_, nrow = 3, ncol = 3)
    		))
    	)
    	
    	output$table <- renderRHandsontable({
    		tables$df_user
    	})
    	
    	observeEvent(input$button, {
    		
    		df <- hot_to_r(input$table)
    		
    		index_empty <- which(is.na(df), arr.ind = TRUE)
    		index_correct <- which(df == tables$df_correct, arr.ind = TRUE)
    		index_wrong <- which(df != tables$df_correct, arr.ind = TRUE)
    		
    		tables$df_user <- 
    			df %>%
    			rhandsontable() %>%
    			hot_cols(renderer = "")
    	})
    }
    
    shinyApp(ui = ui, server = server)

**Comment by artofstat** [comment]
You can submit "parameters" (i.e., R objects such as row and column indices) with your rhandsontable call via ```...```. The relevant line in the help for rhandsontable is the one that explains the ```...``` argument.

```
rhandsontable(data, colHeaders, rowHeaders, comments = NULL,
  useTypes = TRUE, readOnly = NULL, selectCallback = FALSE,
  width = NULL, height = NULL, digits = 4, debug = NULL,
  search = FALSE, ...)
```

Arguments:

**...	   passed to hot_table and to the params property of the widget**

In the app below I allow the user to input which rows in the rhandsontable should be highlighted, and I pass these indices to the rhandsontable (called ```myindex``` in the code below). You can then access ```myindex``` in the renderer function:

```
library(shiny)
library(rhandsontable)
DF <- data.frame(val = 1:20, bool = TRUE, nm = LETTERS[1:20],
                 dt = seq(from = Sys.Date(), by = "days", length.out = 20),
                 stringsAsFactors = F)

app <- shinyApp(
  ui = fluidPage(
    textInput("myindex", "Chose Row(s) to highlight, separated by a comma:", value="2,3"),
    rHandsontableOutput("hot", height=200, width = 300)
  ),
  server = function(input, output) {
    output$hot <- renderRHandsontable({
      myindex <- as.integer(unlist(strsplit(input$myindex,","))) - 1
      rhandsontable(DF, myindex = myindex) %>%
        hot_cols(renderer = "function(instance, td, row, col, prop, value, cellProperties) {
                 Handsontable.renderers.TextRenderer.apply(this, arguments);
                 if (instance.params) {
                 mhrows = instance.params.myindex;
                 mhrows = mhrows instanceof Array ? mhrows : [mhrows];
                 }
                 if (instance.params && mhrows.includes(row)) td.style.background = 'lightblue';
    }"
        )
  })
    }
        )
runApp(app)
```

I hope this helps, although your renderer function is probably going to be a bit more complicated.

**Comment by artofstat** [comment]
Not related to the above, I just realized how including a renderer function messed up how the boolean column is displayed (i.e., not showing checkboxes).

**Comment by gueyenono** [comment]
@artofstat I just tested your code and it works. I am going to adapt it to my example above and post the final code here for anyone else who needs it. Thank you very much.

**Comment by gueyenono** [comment]
@artofstat With your help, I am able to achieve my goal fairly easily. But nothing seems to work when I use an action button as the trigger. If I use your example app above to illustrate this fact, the rows are not highlighted if I try to channel the process through a button:

```
library(shiny)
library(rhandsontable)
DF <- data.frame(val = 1:20, bool = TRUE, nm = LETTERS[1:20],
				 dt = seq(from = Sys.Date(), by = "days", length.out = 20),
				 stringsAsFactors = F)

app <- shinyApp(
	ui = fluidPage(
		textInput("myindex", "Chose Row(s) to highlight, separated by a comma:", value="2,3"),
		actionButton("button", "Highlight rows"),
		rHandsontableOutput("hot", height=200, width = 300)
	),
	server = function(input, output) {
		output$hot <- renderRHandsontable({
			
			myindex <- eventReactive(input$button, {
				as.integer(unlist(strsplit(input$myindex,","))) - 1
			})

			rhandsontable(DF, myindex = myindex) %>%
				hot_cols(renderer = "function(instance, td, row, col, prop, value, cellProperties) {
                 Handsontable.renderers.TextRenderer.apply(this, arguments);
                 if (instance.params) {
                 mhrows = instance.params.myindex;
                 mhrows = mhrows instanceof Array ? mhrows : [mhrows];
                 }
                 if (instance.params && mhrows.includes(row)) td.style.background = 'lightblue';
    }"
				)
		})
	}
)
```

Do you have an idea how to make it work?

**Comment by gueyenono** [comment]
Thank you very much for the help @artofstat and @bklingen
