### ISSUE TITLE
Handsontable licensing

### ISSUE THREAD

**Issue by johndrummond** [jrowen/rhandsontable#304]
Looking at the Handsontable website it doesn’t seem currently to be open source and is free only for non commercial use.
Does Rhandsontable use a fork of an earlier open source version?

**Comment by jrowen** [comment]
It looks like this is a change with v7.  We will likely update rhandsontable to v6.2.2, but I wouldn't expect we'll make any additional updates to the handsontable libraries while it remains commercially restrictive.  

Thanks for pointing out this change.

**Comment by johndrummond** [comment]
Good, thanks; I can carry on with rhandsontable.
Thanks for your work
