### ISSUE TITLE
Request: Pre-populate new rows with template values

### ISSUE THREAD

**Issue by thercast** [jrowen/rhandsontable#33]
Hello, thank you for your excellent work to create this package!  I'm starting to use it within a Shiny application and I'd like any new rows to be pre-populated with some template values as seen in [this example](http://docs.handsontable.com/0.16.1/demo-pre-populating-new-rows.html) from the handsontable documentation.  I didn't see any parameters in `hot_table` to accomplish this, but it would be a great feature to have.  Let me know if you'd like me to provide more details on this idea.

**Comment by jrowen** [comment]
Thanks for the suggestion.  This may be possible but would cause some challenges when is comes to keeping the data in sync with the source in shiny.  I'll take a deeper look.

For now, it might be easier to include this logic in your shiny app.  Adding a new row to the table should fire an input change in shiny.  If `changes$event == 'afterCreateRow'`, you can pre-populate the new row with default values (use `int` and `ct` to identify the new row(s)).  This would allow you to control the default values in R and keep the table in sync with your source data.

This could also be a useful shiny example to incorporate into the package.

**Comment by jrowen** [comment]
I just added a `default` parameter to `hot_col` that should allow you to pre-populate new rows.  If you have time, please take a look at the dev version and let me know if  you have any feedback.  Thanks for the suggestion.
