### ISSUE TITLE
columnSorting=T and input$tableId_select$select$r don't work together

### ISSUE THREAD

**Issue by mbacou** [jrowen/rhandsontable#34]
When `columnSorting=T` manually sorting columns seem to affect row indices, so any subsequent call to `input$tableId_select$select$r` will return data for the wrong row. Best would be to ensure that `input$tableId_select$select$r` always returns the underlying data.frame's `row.name`.

**Comment by jrowen** [comment]
Thanks for filing.  I checked in a possible [fix](https://github.com/jrowen/rhandsontable/blob/master/inst/htmlwidgets/rhandsontable.js#L103-L142); please let me know if this is working better.

**Comment by mbacou** [comment]
Yes, seems fixed, thanks! (I have a live example here http://tools.harvestchoice.org/subnatpov/ where rhandsonsetable rows are linked to areas on a map with custom column sorting, seems to retain teh index now)
