### ISSUE TITLE
Automatic re-render of table responding to other widget action?

### ISSUE THREAD

**Issue by lsusatyo-gcmlp** [jrowen/rhandsontable#35]
Hi Jonathan,

We posted this issue in the stackexchange to no avail. Wondering if this feature is supported or not.

http://stackoverflow.com/questions/31863518/linking-shiny-actionbutton-and-rhandsontable

Thank you!

**Comment by jrowen** [comment]
Take a look at the calculation input and data file examples [here](http://jrowen.github.io/rhandsontable/#shiny).  You should be able to use an action button with the table.  Unfortunately, it is a little complicated, usually requiring the use of `reactiveValues` to cache the table.

I'd very much like to streamline this approach and am very open to suggestions.

**Comment by jrowen** [comment]
Is this still an outstanding issue?
