### ISSUE TITLE
Live-edit data file with factors

### ISSUE THREAD

**Issue by cho7tom** [jrowen/rhandsontable#36]
Dear all,

##### Context

First let me congratulate you for this great package, I see many opportunities to use it in my future Shiny apps!
Being quite new to rhandsontable, I have an issue while trying to live-edit an Excel file when some columns are interpreted as factor by R (which is my expected behavior).

##### Reproducible example
As an simple reproducible example (based on your demo rhandsontable_datafile):

###### ui.R
```
library(rhandsontable)
shinyUI(fluidPage(
  actionButton("saveBtn", "Save changes"),
  rHandsontableOutput("hot")
))
```
###### server.R
```
library(rhandsontable)
library(xlsx)

shinyServer(function(input, output, session) {
  fname <- "filename"
  values = list()
  setHot = function(x) values[["hot"]] <<- x
  
  observe({ # will update xlsx file each time the button is pressed
    input$saveBtn
    if (!is.null(values[["hot"]])) {
      write.csv(values[["hot"]], fname)
      write.xlsx(x = values[["hot"]], file = paste0(fname, ".xlsx"), row.names = FALSE)
    }
  })
  
  output$hot = renderRHandsontable({
    if (!is.null(input$hot)) {
      DF = hot_to_r(input$hot)
      setHot(DF)
      rhandsontable(DF) %>%
        hot_table(highlightCol = TRUE, highlightRow = TRUE)
    } else {
      DF <- read.xlsx2("filename.xlsx", sheetIndex = 1)                            # DOES NOT WORK
      # DF <- read.xlsx2("filename.xlsx", sheetIndex = 1, stringsAsFactors = FALSE)  # DOES WORK
      setHot(DF)
      rhandsontable(DF) %>%
        hot_table(highlightCol = TRUE, highlightRow = TRUE)
    }
  })
})

```

###### filename.xlsx

![test](https://cloud.githubusercontent.com/assets/4041568/9251501/d337ecfc-41d3-11e5-9fcd-0fb7f1896bd0.PNG)

#### Error

When running the version with the folowing row active
```
DF <- read.xlsx2("filename.xlsx", sheetIndex = 1)
```
![1](https://cloud.githubusercontent.com/assets/4041568/9251648/9165f700-41d4-11e5-8494-d9206737582a.PNG)
the following error occurs as soon as I change a cell value:
![2](https://cloud.githubusercontent.com/assets/4041568/9251654/985e3cac-41d4-11e5-9a16-3610c65685fa.PNG)

I would like values to be treated as factors (to have dropdown values proposal). Is that feasible? Could you please let me know how to proceed?

Many thanks in advance for your views on this issue !

Regards

**Comment by jrowen** [comment]
Can you try installing the dev version from github?  I added some new
handling for factors, mapping to dropdown columns.  You won't be able to
add new factors but can choose from existing--if you're looking for
unrestricted editing, you probably want to stay away from using factors.
See the new doc page for more examples,
https://github.com/jrowen/rhandsontable.

I'd very much like feedback on the approach, PRs also welcome.
Alternately, you can convert factors to characters after loading the Excel
file.

**Comment by jrowen** [comment]
Did this resolve your issue?

**Comment by cho7tom** [comment]
Yes thank you very much!
