### ISSUE TITLE
hot_to_r error with dropdown column

### ISSUE THREAD

**Issue by rvwheelock-gcm** [jrowen/rhandsontable#37]
there doesn't seem to be a way to call hot_to_r() if the table contains a column of type dropdown.

for example:

server.R - 

shinyServer(function(input, output) {
    output$saveButton <- downloadHandler(
          filename=function() { paste0(Sys.Date(), '.csv') },
          content = function(file) { 
              hot.df <- hot_to_r(input$table)
      
              write.csv(hot.df, file=file) 
          }
     )
  
  output$table <- renderRHandsontable({
         df <- data.frame( a = "")
    
         rhandsontable(df, rowHeaders = NULL) %>%
             hot_col("a", type = "dropdown", source = list("hello", "world"))
   })
})

gives the error: 
no method or default for coercing “character” to “factor”

**Comment by jrowen** [comment]
I added some logic to the dev version to support factors.  Could you try it out and let me know if you are still running into errors?

**Comment by rvwheelock-gcm** [comment]
I grabbed the dev version and with the same code I get still get the error: 
      <code>no method or default for coercing “character” to “factor” </code>

Here's a better looking version of the code I'm using to test:


    output$saveButton <- downloadHandler(
        filename=function() { paste0(Sys.Date(), '.csv') },
        content = function(file) { 
             hot.df <- hot_to_r(input$table)
             write.csv(hot.df, file=file) 
        }
    )
    output$table <- renderRHandsontable({
        df <- data.frame( a = "")
        rhandsontable(df, rowHeaders = NULL) %>%
             hot_col("a", type = "dropdown", source = list("hello", "world"))
    })

**Comment by jrowen** [comment]
I just make another update that should correct the error.  

Your example doesn't work exactly as expected, but I think this is because you're defining a single cell table containing an empty string as a factor.  Please update the library and then try one of the example datasets below.
```R
df = data.frame(a = "", stringsAsFactors = FALSE)  # with define a character column
# or
df = data.frame(a = LETTERS[1:3])  # will define a factor column
```
If this doesn't resolve your issue, please let me know.  Thanks for reporting.

**Comment by rvwheelock-gcm** [comment]
Thanks so much! factors work now!
