### ISSUE TITLE
readOnly not enforced?

### ISSUE THREAD

**Issue by prescient** [jrowen/rhandsontable#38]
I may misunderstand this the readOnly parameter, but in shiny when I create a new table and set columns to read only using readOnly = T I am able to right click and make them in the web browser and make them editable. 

Is this the intended functionality?

**Comment by jrowen** [comment]
There's an example [here](http://jrowen.github.io/rhandsontable/#read-only).  If you're still running into problems, let me know.  Thanks.

**Comment by prescient** [comment]
Thanks for the feedback! 

What I'm curious about is whether I can disable the read only dialog indicated in the screenshot below. I've made what should be a repeatable example in the below code to illustrate how I'm going about this.

![rhandsontable screen grab](https://cloud.githubusercontent.com/assets/764399/9508949/6e1ea522-4c28-11e5-842e-9b586a42a393.png)

require(rhandsontable)
require(shiny)
df <- data.frame(col1 = rnorm(20),
                 col2 = rnorm(20),
                 col3 = rnorm(20),
                 col4 = rep(T, 20),
                 col5 = rep(T, 20))


server <- function(input, output) {
  output$out <- renderRHandsontable(rhandsontable(df, readOnly = T) %>%
                                           hot_col(c("col4", "col5"), readOnly = F))
}

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(),
    mainPanel(rHandsontableOutput("out"))
  )
)

shinyApp(ui = ui, server = server)

**Comment by jrowen** [comment]
Good suggestion--I hadn't thought about disabling [this](https://github.com/jrowen/rhandsontable/blob/master/inst/htmlwidgets/rhandsontable.js#L58), which seems to be an all or nothing setting on the context menu.  It might make sense to move these types of settings to a new function, `hot_context_menu`, for example.

**Comment by prescient** [comment]
That would be great.

**Comment by jrowen** [comment]
Reopening to track enhancement.

**Comment by jrowen** [comment]
I made some changes to the context menu options, and I'd appreciate your feedback.  You can install using
```
devtools::install_github("jrowen/rhandsontable", ref = "context_menu")
```
and there is a new [example](https://github.com/jrowen/rhandsontable/blob/context_menu/inst/examples/context_menu.R) that might be of interest.

**Comment by jrowen** [comment]
These updates are now part of the dev version (v0.2.1) and will post to CRAN shortly.  Please re-open this issue if you run into problems with the latest version.  Thanks.
