### ISSUE TITLE
Cannot add new columns

### ISSUE THREAD

**Issue by Deleetdk** [jrowen/rhandsontable#39]
I have enabled allowColEdit and allowRowEdit. This makes it possible to add new rows, but not new columns. I'm not sure if I'm missing something or it's a bug. The menu options show up correctly, but nothing happens when clicking them.

It happens with this Shiny: https://github.com/Deleetdk/Jensens_method_2

**Comment by jrowen** [comment]
You can only add new columns if the column types are not specified (matrix
data set). I'll have to see if I can improve the documentation around this.

**Comment by Deleetdk** [comment]
I'm not sure I understand. Are you saying that I need to use a matrix instead of a data.frame and then it will work? In my case, I only need numeric data input, so that would be a useful workaround. It is however important that one can add new columns so the simulator.

**Comment by jrowen** [comment]
Handsontable does not support add/remove columns when column properties, like type, are defined.  See an example without types [here](http://docs.handsontable.com/0.17.0/demo-context-menu.html) (first example) and with types [here](http://jsfiddle.net/55vqwote/).  The latter will have the column edit options grayed out.

In `rhandsontable`, you should be able to set `useTypes = FALSE` to enable column edit options.

**Comment by Deleetdk** [comment]
I confirm that using `useTypes  = F` works. It however also means that the table is returned as character matrix instead of data.frame. This caused errors in my code I had to spend time correcting.

**Comment by jrowen** [comment]
I just pushed some updates that should fix this, maintaining the original data classes.  There is a conversion from R to JS back to R, which can be problematic.  Please let me know if you run into any additional errors.  The rhandsontable_output example in this branch has been updated to make it easier to test this functionality.

**Comment by jrowen** [comment]
These updates are now part of the dev version (v0.2.1) and will post to CRAN shortly.  Please re-open this issue if you run into problems with the latest version.  Thanks.
