### ISSUE TITLE
Few minor questions

### ISSUE THREAD

**Issue by smartinsightsfromdata** [jrowen/rhandsontable#4]
@jrowen  Again congrats for a great implementation of this widget.
Few minor questions listed here:

- (Some) of the examples of handsontable.js do not have the rowname column altogether.
How can I do that with rhandsontable?
- +1 for the implementation of comments.  How can a user use / write them (i.e. excel-style)?
- +1 for the heat map implementation.  Could you kindly add an example to use just a column for RAG status?
- So far I haven't managed to send rhandsontable in a malicious loop as other widgets may do - see my comment to DT from rstudio  :)
        How did you achieve this - and is there a programming pattern in shiny that avoids the setting of endless loops?

Thanks

**Comment by jrowen** [comment]
Thanks for testing and the feedback--keep it coming.
* I [updated](https://github.com/jrowen/rhandsontable/commit/7e855e4dc10d248c1b573121d927d4264825df43) the logic to omit the row and column headers if set to `NULL`.  If the parameters are missing, the row and columns names of the `data.frame` or `matrix` will be used.  Good suggestion.
* A user should be able to add comments (right click) after enabling the functionality sing the code below, but I don't yet have a mechanism for returning comments back to R.  I'm open to suggestions here.  This is beta functionality in handsontable.js, and it doesn't look like any comment related events have been implemented yet.  Once events are available, comments could be handled similarly to table changes.
```
rhandsontable(DF) %>% 
  hot_table(comment = TRUE)
```
* There was a [bug](https://github.com/jrowen/rhandsontable/commit/df4aad88c332ee91a680baeb4a90698f7c431884) with `hot_heatmap`.  You should now be able to set the heatmap columns using the `cols` parameter of `hot_heatmap`.
* I haven't run into a malicious loop before, so I'm afraid I don't have any suggestions in this area.  Please let me know if you run into this behavior with `rhandsontable`.

**Comment by smartinsightsfromdata** [comment]
What do to with comments.
@jrowen based with my experience in systems that had this functionality (typically budgeting systems), this is what I would do:
- provide a method to pre-amble messages with a user name (leaving to the app the responsibility to pick the "right" name).  
- a message could have different authors (i.e. same message, different pre-amble)
- messages should be stored somewhere and - at some point available on the server (different options here).  Useful to store also cell (e.g. row by col) and row content at the time of the comment.
- what else? A user will be able to see a message and comment on it underneath (as mentioned above). At times applications can print all the messages in a certain table (with the reference to the cell and cell content they referred to), but it is an app decision, provided that the bulk of messages are stored.

To facilitate collaboration it is useful to have ways to save the visible table (with comments) as a pic, so that it can be attached in an email...

**Comment by jrowen** [comment]
Great suggestions.  To really leverage the comment functionality and implement these suggestions, handsontable.js needs to support comment change events.  Once before and after comment change events are available, it should be relatively easy to prefix comments and send updates to R.  The comment functionality is listed as beta on the project [site](http://handsontable.com/demo/comments.html), so it may be worthwhile filing a feature request issue with the project.

**Comment by smartinsightsfromdata** [comment]
Closing for now - awaiting for more development on handsontable comments as discussed.
