### ISSUE TITLE
Can't disable contextMenu

### ISSUE THREAD

**Issue by doubletang** [jrowen/rhandsontable#41]
When set contextMenu=F, the right-click menu still there.

mtcars %>% rhandsontable() %>% hot_table(contextMenu=F)

R 3.2.1, rhandsontable 0.2

**Comment by jrowen** [comment]
I've made some improvements to this functionality in the dev version.  Would you mind giving that version a try and letting me know if this is still a problem?
```
devtools::install_github("jrowen/rhandsontable", ref = "context_menu")
```

**Comment by doubletang** [comment]
It works very well! Thank you!

**Comment by jrowen** [comment]
These updates are now part of the dev version (v0.2.1) and will post to CRAN shortly.  Please re-open this issue if you run into problems with the latest version.  Thanks.
