### ISSUE TITLE
can't show multiple tables in the shiny built-in browser

### ISSUE THREAD

**Issue by haythorn** [jrowen/rhandsontable#42]
If there are multiple calls to rHandsontableOutput, in the built=in browser only one of them will show.  For example, this happens with the data file editor example - if I copy it into RStudio and execute it, I will only see one of the tables.
The page looks fine in Chrome, so it is easy to work around this by calling runApp( launch.browser=TRUE, ...),  So no urgency about solving it.  Since I never experienced the problem with shinytable, I figured I should tell you about it.

**Comment by jrowen** [comment]
Take a look at the [rhandsontable_frontier](https://github.com/jrowen/rhandsontable/tree/master/inst/examples/rhandsontable_frontier) example.  It's using two tables, and I'm not running into any issues with the viewer and window in RStudio v0.99.679.  If you can provide a minimally reproducible example, I can take a closer look at the problem you're encountering.

**Comment by haythorn** [comment]
Hi,
Thank you for getting back to me so quickly - the issue was my RStudio 
version - when I updated it the problem went away.

On 9/10/2015 4:59 AM, Jonathan Owen wrote:
>
> Take a look at the rhandsontable_frontier 
> <https://github.com/jrowen/rhandsontable/tree/master/inst/examples/rhandsontable_frontier> 
> example. It's using two tables, and I'm not running into any issues 
> with the viewer and window in RStudio v0.99.679. If you can provide a 
> minimally reproducible example, I can take a closer look at the 
> problem you're encountering.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jrowen/rhandsontable/issues/42#issuecomment-139213901>.
>

-- 
  “To enable Cortana to provide personalized experiences and relevant suggestions,
Microsoft collects and uses various types of data, such as your device location,
data from your calendar, the apps you use, data from your emails and text messages,
who you call, your contacts and how often you interact with them on your device.
Cortana also learns about you by collecting data about how you use your device
and other Microsoft services, such as your music, alarm settings, whether the
lock screen is on, what you view and purchase, your browse and Bing search history,
and more.” …  “we collect your voice input, as well your name and nickname,
your recent calendar events and the names of the people in your appointments,
and information about your contacts including names and nicknames.” … “We will
access, disclose and preserve personal data, including your content (such as
the content of your emails, other private communications or files in private
folders), when we have a good faith belief that doing so is necessary to …
protect our customers [or] enforce the terms governing the use of the services”.
Windows 10 EULA

**Comment by jrowen** [comment]
Glad to hear it's working.
