### ISSUE TITLE
Tables not re-sizing in shinydashboard

### ISSUE THREAD

**Issue by jrowen** [jrowen/rhandsontable#44]
In the example below, the tables don't re-size when the browser window size changes and may overlap.

```
shiny::runGitHub("rhandsontable", "jrowen", subdir="inst/examples/rhandsontable_dash")
```

**Comment by jrowen** [comment]
Also see https://github.com/ramnathv/htmlwidgets/issues/102

**Comment by fineswag** [comment]
I've encountered this issue as well in my shiny dashboard. My heatmap table doesn't conform to the gridlines and jumps off to the right out of view. Is there a way to specify the width of the table using Shiny?

**Comment by jrowen** [comment]
Take a look at the example above and the latest dev version of the package.  I'm now seeing the tables resize with the window.

**Comment by fineswag** [comment]
Thanks for the quick response. When I run the example above, and my own app, after downloading the developer version, I'm getting `ERROR: unused argument (all_files = FALSE)`. Are you seeing this too? Do you know how to get around this error?

**Comment by jrowen** [comment]
I think you want to be using the `box` function when building a dashboard page (see https://rstudio.github.io/shinydashboard/structure.html and my earlier example).  If you still are seeing display problems after those updates, please share a reproducible example, and I'll take a look.

**Comment by jrowen** [comment]
Please re-open if this is still an issue.

**Comment by trafficonese** [comment]
I am still having problems with resizing the table. I am actually using a custom UI with htmlTemplate, but the problem seems to be the same with shinydashboard when closing the sidebar. On the right side of the table, something is missing from the table header and it is also not filling up the whole space.

By manually changing the window size, the table gets redrawn correctly. 
I tried to manually use `.trigger("shown")`, `.trigger("resize")` etc without success. What would be the correct way of triggering a resize when the sidebar is closed/opened?


```
## Libs / Data ##########
library(shiny)
# packageVersion("shiny")
# ‘1.2.0’
library(rhandsontable)
# packageVersion("rhandsontable")
# ‘0.3.7’
library(shinydashboard)
# packageVersion("shinydashboard")
# ‘0.7.0’

dfN <- data.frame(
  val = runif(20, 100,1000),
  qual = 8,
  col = "green", stringsAsFactors = F
)
##########

ui = dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    # box(
      rHandsontableOutput("table")
    # )
  )
)

server <- function(input, output, session) {
  output$table <- renderRHandsontable({
    
    d <- rhandsontable(dfN, selectCallback = T,
                       height = "inherit"
    ) %>%
      hot_table(highlightCol = TRUE, contextMenu= FALSE, highlightRow = TRUE, 
                stretchH = "all", overflow = "visible")
    
    d$elementId = NULL
    d
  })
}

shinyApp(ui, server)
```
