### ISSUE TITLE
Numeric Formatting and Conditional Formatting (using rendered) don't work together

### ISSUE THREAD

**Issue by AdamBarnhard** [jrowen/rhandsontable#45]
Awesome package!! Thanks for putting it together. One potential issue: it seems like a column can't have both a rendered JS input and a format input.

- Column with just numeric formatting:

`rhandsontable(iris) %>% hot_col(1,format="0%")`

![screen shot 2015-09-16 at 12 50 38 am](https://cloud.githubusercontent.com/assets/10203350/9899176/01317c24-5c0d-11e5-9f79-e9669d3850bd.png)

- Column with just JS formatting:

```
rhandsontable(iris) %>% 
 hot_col(1,renderer="function (instance, td, row, col, prop, value, cellProperties) {
Handsontable.renderers.TextRenderer.apply(this, arguments);
          td.style.background = 'lightgrey';
          td.style.fontWeight = 'bold';
          }
          ")
```

![screen shot 2015-09-16 at 12 52 18 am](https://cloud.githubusercontent.com/assets/10203350/9899246/7786390a-5c0d-11e5-8221-a48ee4801f39.png)

- Column with both in function, only JS formatting works:

```
 rhandsontable(iris) %>% 
     hot_col(1,format="0%",renderer="function (instance, td, row, col, prop, value, cellProperties) {
             Handsontable.renderers.TextRenderer.apply(this, arguments);
             td.style.background = 'lightgrey';
             td.style.fontWeight = 'bold';
             }
             ")
```

![screen shot 2015-09-16 at 12 58 16 am](https://cloud.githubusercontent.com/assets/10203350/9899343/0ba42e44-5c0e-11e5-9a46-fde37f85d6d3.png)

Is this a known issue or an error on my end? Thanks!!!

**Comment by jrowen** [comment]
Try using [`NumericRenderer`](https://github.com/handsontable/handsontable/blob/5aaf57e1224c11cfd158a071d75179583bbe7a2f/src/renderers/numericRenderer.js) instead of `TextRenderer`.  The former makes a call to numeral.js to format the cell.

**Comment by AdamBarnhard** [comment]
Awesome - thanks so much!! You saved me a ton of time!

**Comment by SamSpilkin** [comment]
Would you mind perhaps sharing your solution? I'm struggling with combining numeric and conditional formatting, and would greatly appreciate some guidance! thank you

**Comment by jrowen** [comment]
Did you see the example at http://jrowen.github.io/rhandsontable/#conditional-formatting?  Also see my earlier comment and the link to the NumericRenderer function details.

**Comment by ecogamut** [comment]
This is unclear to me. I can't seem to get scientific notation..

**Comment by Cullrich** [comment]
As someone the solution for scientific notation ?

**Comment by yishuanwu** [comment]
Still having the issue and unable to get scientific notation to work

**Comment by kamitoth** [comment]
Scientific notation would be an excellent addition.

**Comment by yishuanwu** [comment]
Struggling with this issue too, please help -- how do you make the column scientific format? I have a mix of small and large values, and the small numbers got rounded to 0 which is not desirable behavior, but I can't anticipate the number of post-decimal places.
