### ISSUE TITLE
Allow to reset input$hot

### ISSUE THREAD

**Issue by lucacerone** [jrowen/rhandsontable#46]
Hi first of all thanks for this amazing package!

I am having a hard time in figuring out how to use rhandsontable in an app where i can switch among different tables and save the edited tables to a file.

I followed the example in inst/examples/rhandson_datafile.

I then added a selectInput  (with inputID tablename) in the ui.R and modified server.R to read different files depending on input$tablename. If I don't edit the tables, then switching the tables works.

The problem I have is that using !(is.null(input$hot)) prevents the switch if I already edited one of the tables, in which case input$hot is not null. I couldn't come out with a solution and can not set input$hot to null manually when the switch happens (I tried `observeEvent(input$tablename, input$hot <- NULL)` but receive an error saying that I am not allowed to do this because it is a read-only value).

Is it possible to add a function to reset input$hot (or whathever other inputID one might choose),
or do you have any workaround for this in mind?

Thanks a lot for the help!
Cheers,
Luca

**Comment by jrowen** [comment]
A similar question came up earlier: https://github.com/jrowen/rhandsontable/issues/27.  If this doesn't answer your question, please post a minimal example, and I'll take a closer look.  Thanks.

**Comment by lucacerone** [comment]
Thanks @jrowen, that looks exactly the same issue I have! (sorry for not noticing the question was already asked). I'll try the solution in #27 and let you know whether I manage to make it work!

**Comment by jrowen** [comment]
@lucacerone, based on your comment in the other issue, I'm going to assume this is resolve.  Please re-open if you're still experiencing issues.  Thanks.
