### ISSUE TITLE
Columns are jumbled

### ISSUE THREAD

**Issue by kferris10** [jrowen/rhandsontable#47]
Not really sure what is going on here.  When using `rhandsontable`, I get the columns in the wrong order like this:

| vs|  4|  6|  8|
|--:|--:|--:|--:|
|  1|  3|  14| 0|
|  10| 4|  | 1|

```
library(dplyr)
library(tidyr)
library(rhandsontable) 

mtcars %>% 
  group_by(vs, cyl) %>% 
  summarise(num = n()) %>% 
  spread(cyl, num)

  vs  4 6  8
1  0  1 3 14
2  1 10 4 NA

mtcars %>% 
  group_by(vs, cyl) %>% 
  summarise(num = n()) %>% 
  spread(cyl, num) %>% 
  rhandsontable()
```

Here's my session info

```
> devtools::session_info()
Session info ------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.3 (2015-03-09)
 system   x86_64, mingw32             
 ui       RStudio (0.99.473)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            

Packages ----------------------------------------------------------------------------------------------------------
 package       * version date       source                               
 assertthat    * 0.1     2013-12-06 CRAN (R 3.1.3)                       
 DBI           * 0.3.1   2014-09-24 CRAN (R 3.1.3)                       
 devtools      * 1.7.0   2015-01-17 CRAN (R 3.1.3)                       
 digest        * 0.6.8   2014-12-31 CRAN (R 3.1.3)                       
 dplyr           0.4.1   2015-01-14 CRAN (R 3.1.3)                       
 htmltools     * 0.2.6   2014-09-08 CRAN (R 3.1.3)                       
 htmlwidgets   * 0.5.1   2015-09-16 Github (ramnathv/htmlwidgets@3a2e312)
 jsonlite      * 0.9.16  2015-04-11 CRAN (R 3.1.3)                       
 lazyeval      * 0.1.10  2015-01-02 CRAN (R 3.1.3)                       
 magrittr      * 1.5     2014-11-22 CRAN (R 3.1.3)                       
 Rcpp          * 0.11.5  2015-03-06 CRAN (R 3.1.3)                       
 rhandsontable   0.2.2   2015-09-23 Github (jrowen/rhandsontable@d96bf46)
 rstudioapi    * 0.3.1   2015-09-16 Github (rstudio/rstudioapi@d0417a9)  
 tidyr           0.2.0   2014-12-05 CRAN (R 3.1.3)                       
 yaml          * 2.1.13  2014-06-12 CRAN (R 3.1.3)  
```

**Comment by jrowen** [comment]
Thanks for posting.  The hand off between `rhandsontable` and `htmlwidgets` isn't working as expected, so I've posted an issue with that project as well.

**Comment by timelyportfolio** [comment]
I think changing this [line](https://github.com/jrowen/rhandsontable/blob/master/inst/htmlwidgets/rhandsontable.js#L18) to be explicit and follow ordering specified by `x.colHeaders` will be a more robust way to handle.

```
toArray(x.data.map(function(d){return x.colHeaders.map(function(ky){return d[ky]})}))
```

**Comment by jrowen** [comment]
Thanks, your suggestion fixes the problem and is more robust.

It appears to me that the column reordering is happening outside of the `toArray` call, as in the js debugger I see the `x.data` obj passed to `toArray` already has an incorrect order.  It seems that js is reordering the obj values.
```
> x.data[0]
<- Object {4: 1, 6: 3, 8: 14, vs: 0}
```
Just trying to understand why this is occurring so I can prevent future bugs.  Thanks again for the help.

**Comment by timelyportfolio** [comment]
I should in bold say **I am not a definitive source** but I recall seeing in multiple places that order of keys is not assured in JavaScript objects. Here is one StackOverflow [post](http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order) that seems to be more authoritative than me.

**Comment by jrowen** [comment]
Thanks for the link.  I checked in a fix, but please re-open if you still run into issues.

**Comment by ramnathv** [comment]
If I remember correctly, the reordering occurs only when the keys are numbers.
