### ISSUE TITLE
Cell red color

### ISSUE THREAD

**Issue by omarbenites** [jrowen/rhandsontable#48]
Hello jrowen, 
I have a doubt when I use the next example, 
```{r, echo=FALSE}
MAT = matrix(rnorm(50), nrow = 10, dimnames = list(LETTERS[1:10],
                                                   letters[1:5]))
rhandsontable(MAT * 10) %>%
    hot_validate_numeric(col = 1, min = -2, max = 4, exclude = 40,allowInvalid = FALSE)
```
![image](https://cloud.githubusercontent.com/assets/5264796/10148179/b3074660-65f7-11e5-861b-95521b99c532.png)

It says: "Invalid data cells will be color red" but when I execute the example, the cell values which are out of range (-2,4) does not have any red color.

Help me if I have an error.
Thank so much in advance and congratulations for this amazing package!!.

**Comment by jrowen** [comment]
You're correct, when you set `allowInvalid = TRUE` the cell background color should change if an invalid value is entered.  I just added a fix to the dev version, so let me know if you're still running into the problem.  Thanks for reporting.

**Comment by omarbenites** [comment]
Thanks jrowen!. Now it is working very well!

On the other hand, just one more question: When I run the example, it does not automatically change the background color (red) when I load the matrix o df, so I had to press ENTER for every cell to change the color.

![image](https://cloud.githubusercontent.com/assets/5264796/10224472/b47f0824-6823-11e5-89e5-24dcee567937.png)

I wonder If could be possible just running the code, automatically change the background color of these out of range cell values when I load the matrix or df ?

Something like this:

![image](https://cloud.githubusercontent.com/assets/5264796/10224996/5036b10c-6826-11e5-911d-2d39edd90ef1.png)

Thanks so much again!

**Comment by jrowen** [comment]
The validation logic fires when a cell is changed by the user.  If you want to apply validation when the table is generated, take a look at [conditional formatting](http://jrowen.github.io/rhandsontable/#conditional-formatting).
