### ISSUE TITLE
validator logic

### ISSUE THREAD

**Issue by smartinsightsfromdata** [jrowen/rhandsontable#5]
@jrowen I find the validator one of the most interesting things of your implementation (as it makes so much sense to do this client-side).  Unfortunately it is not very clear how it works.  
- Am I right assuming that it works also with a data.frame - or it is not column specific hence it works only with a matrix?
- Does it need to be written in  JS?
- Could you kindly give an example of a validation  test similar to ```typeof(value) == "string" && value > 0``` ?

**Comment by jrowen** [comment]
You should be able to use a matrix or a data.frame.  You can apply the logic a specific column using `hot_col` and specifying the column.  Currently, the validator function needs to be written in JS, but I've been considering adding some pre-built functions.  Take a look at the [validator](https://github.com/jrowen/rhandsontable/tree/validator) branch and let me know what you think of this approach.  I included a few more examples too.

**Comment by smartinsightsfromdata** [comment]
@jrowen It looks good, but ```hot_validate_numeric``` does not force only numeric value: it is possible to type a letter and get a NA in exchange.
As I mentioned above, to me the main driver for using validator is to spare the lengthy cycles between client and server needed to: 
1 get the data server side after each data entry
2 check for NA and in case correct data
3 re-send data to client
To avoid the above ```hot_validate_numeric``` should first and foremost refuse a data entry that is not numeric (e.g. with a ```typeof``` test?)
