### ISSUE TITLE
Saving user edits to table

### ISSUE THREAD

**Issue by dlennon** [jrowen/rhandsontable#51]
I am having trouble understanding how to obtain the edited table from the ui.R once it a table is edited in a shiny app implementation of rhandsontable. Are there examples of this? I would like to be able to use the user edits in downstream calculations, so obtaining them is the first step.

**Comment by jrowen** [comment]
Take a look at the corr and frontier examples in
https://github.com/jrowen/rhandsontable/tree/master/inst/examples.

**Comment by jrowen** [comment]
Where you able to find an answer to your question?

**Comment by jrowen** [comment]
Please let me know if you're still having trouble.  Thanks.
