### ISSUE TITLE
Trim Whitespace in Shiny

### ISSUE THREAD

**Issue by TonyDIRL** [jrowen/rhandsontable#54]
Hi,

I am having some trouble with correctly formatting whitespace characters. 

Specifically, with the following ui.R and server.R code the dataframe below is produced.
Unfortunately, in the handsontable produced note how the list data are misaligned even though it is formatted with sprintf and trimWhitespace set to false.

Any idea how to correctly format this?
Also, how would I generate the table without the separating comma's?

```
library(shiny)
library(shinydashboard)
library(rhandsontable)


header <- dashboardHeader()

sidebar <- dashboardSidebar()

body <- dashboardBody(
  
  fluidRow( box(title = "Handsontable",rHandsontableOutput("hot") )
            
  ))

ui <- dashboardPage(header, sidebar, body)

```
```

server <- function(input, output) {
  
  output$hot = renderRHandsontable({
  
    Y<-data.frame(Names=c("a","b","c","d"),stringsAsFactors=FALSE)
    Y$Data=list(c(100,2,300),c(1,20,30),c(10,20,300),c(1,20,3))
    Y$Data<-lapply(Y$Data,function(x) sprintf("% 4d",x) )
    rhandsontable(Y, rowHeaders=FALSE,trimWhitespace =FALSE)
  })
}
```
![image](https://cloud.githubusercontent.com/assets/7284709/11409385/7381a6dc-93b7-11e5-917c-4a85559bf623.png)

**Comment by jrowen** [comment]
Do you want the Data column to be split into 3 columns or be a single
column?

**Comment by TonyDIRL** [comment]
Thank you for the response.

I'm trying to get the data displayed in one column but correctly padded, essentially so the powers of ten correctly line up and without the separating comma's if possible.

**Comment by jrowen** [comment]
Take at look at http://docs.handsontable.com/0.20.1/demo-alignment.html.
```
rhandsontable(Y, rowHeaders=FALSE, rimWhitespace=FALSE) %>%
  hot_col(2, className = "htCenter")
```
You might need to specify your own css class to control whitespace size (maybe via a specified [font](http://stackoverflow.com/questions/4686754/making-every-character-on-a-web-page-the-same-width)).

**Comment by TonyDIRL** [comment]
Thank you, unfortunately, I went through the various choices for className already and couldn't get it to align. I'll look into specifying a font.

Thanks again

**Comment by TonyDIRL** [comment]
Specifying a font resolved the issue

```
fluidRow( div(box(title = "Handsontable",rHandsontableOutput("hot"), style = "font-family: Courier;") )
```

Thank you
