### ISSUE TITLE
hot_to_r converts character into numeric

### ISSUE THREAD

**Issue by BDalheimer** [jrowen/rhandsontable#55]
I was wondering how the hot_to_r function works. I am using data.table with 2 columns which are characters and a varying number of columns which are all numeric. It seems that when using hot_to_r, all columns are coerced to numeric, resulting in a messed up table. Can I pass an argument in the function to keep the types of columns?

**Comment by jrowen** [comment]
That shouldn't be happening.  Tale a look at the example in https://github.com/jrowen/rhandsontable/tree/master/inst/examples/rhandsontable_output and change the data.frame to a data.table.  If you are still running into a problem, post a minimally reproducible example and I'll take a look.

**Comment by BDalheimer** [comment]
Thanks, I did as you advised and it turned out there was another problem in my code which was responsible for the mess up. Sorry for bothering you with this. Anyway, great job on the package. It is a really useful tool and I'm going to use it in my app!
