### ISSUE TITLE
Is it possible to know which cell has changed?

### ISSUE THREAD

**Issue by juancentro** [jrowen/rhandsontable#56]
My table does several calculations. Whenever a user inputs a change, I want to change only the cells that depend on the changed cell. Is that possible? Is there a parameter that specifies which cell has been changed?

**Comment by jrowen** [comment]
If you have a table called `hot`, after it is updated `input$hot $changes$changes` includes the row, column, new and old values (0 indexed as they come from Javascript; row and column based on original data set).  This currently won't work with sorted tables that, but I'll get that bug fixed shortly.

**Comment by juancentro** [comment]
Thanks! That's great

**Comment by SmithaShivakumar** [comment]
Hi, I have the same issue. I am not able to find any example regarding this. Could you please direct me to it? Thanks in advance!

**Comment by jrowen** [comment]
Take a look at
https://github.com/jrowen/rhandsontable/tree/master/inst/examples/rhandsontable_corr.


We definitely could use more documentation around this functionality.

**Comment by SmithaShivakumar** [comment]
@jrowen  Thank you very much!

**Comment by cca32** [comment]
What if multiple edits were made? I'm having trouble finding a list of all changes made

**Comment by VyomDutt** [comment]
Late reply but you could get the length of all changes via` input$myTable$changes$changes` list. 

Something like this : `input$myTable$changes$changes[[i]][[4]]`. It gives you the new value of the ith change.
