### ISSUE TITLE
dplyr tbls generate a warning

### ISSUE THREAD

**Issue by kferris10** [jrowen/rhandsontable#6]
For example

    libray(dplyr)
    iris %>% tbl_df() %>% rhandsontable
    Warning message:
    In if (rClass == "matrix") { :
      the condition has length > 1 and only the first element will be used

I'm not sure if this is worth fixing, but I thought I'd mention in case you hadn't seen this before :)

Great package!

**Comment by jrowen** [comment]
Thanks for reporting this.

**Comment by kferris10** [comment]
Glad I could help
