### ISSUE TITLE
rHandsontableOutput in Shiny when table is empty

### ISSUE THREAD

**Issue by hsy9045** [jrowen/rhandsontable#60]
Hi, thank you for this great package! 

I was trying to put it into a Shiny app to display a table with filter. However if I change the value of the filter, the table does not update correspondingly particularly when the table have no rows returned. Here is a short example using `mtcars` data:

```r
library(rhandsontable)

server <- function(input, output) {
  output$mytable <- renderRHandsontable({
    data = mtcars[mtcars$mpg> as.numeric(input$minMPG),]
    rhandsontable(data)
  })
}

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      numericInput("minMPG","minimum mpg",20)
    ),
    mainPanel(rHandsontableOutput("mytable"))
  )
)

shinyApp(ui = ui, server = server)
```

Changing the input from the default 20 to any value up to 33 seems to work fine. But values beyond 34 does not update the output.

**Comment by jrowen** [comment]
If you take a look at the Javascript console, you'll see an error for rhandsontable, which is caused by passing a data.frame with 0 rows.  Instead of passing the empty data.frame, you could check for 0 rows in your render function and return `NULL` if true.

**Comment by jrowen** [comment]
I also pushed a quick fix that should eliminate the Javascript error.

**Comment by hsy9045** [comment]
Great! thank you.
