### ISSUE TITLE
handsontable output

### ISSUE THREAD

**Issue by dmenne** [jrowen/rhandsontable#62]
https://jrowen.shinyapps.io/rhandsontable_output/

Click/edit first dt row works as expected.

On trying to editing all following date lines, I get NA 

(Firefox, Windows)

**Comment by jrowen** [comment]
Thanks for reporting.  I hit the monthly time limit for my account, so the shinyapps.io examples won't working again until next month.  You could try running locally using the steps [here](http://jrowen.github.io/rhandsontable/#shiny)
