### ISSUE TITLE
Dash not found

### ISSUE THREAD

**Issue by dmenne** [jrowen/rhandsontable#64]
https://jrowen.shinyapps.io/rhandsontable_dash

Gives 404

**Comment by jrowen** [comment]
Thanks for reporting.  I hit the monthly time limit for my account, so the shinyapps.io examples won't working again until next month.  You could try running locally using the steps [here](http://jrowen.github.io/rhandsontable/#shiny)

**Comment by dmenne** [comment]
... Grrr. Sorry, I should have known. I had this problem on my page several times. They really should have a better reporting.
Feel free to close.
