### ISSUE TITLE
filter data with NA values

### ISSUE THREAD

**Issue by cardiomoon** [jrowen/rhandsontable#65]
Thank you for great package !

I 'd like to make a shiny app with a data editing function.

I want to filter data with NA values for easy editing. Also want  toogle between filter/unfilter options.

Is there any possibility?

Sincerely,

Keon-Woong Moon

**Comment by jrowen** [comment]
This is certainly possible. If you use an input to control filtering in
your server.R file, then you'll need to be sure to merge the filtered
dataset with the original before saving.  This is pretty straightforward if
you dataset has a unique key.

I believe the new pro version of handsontable has a filtering plug-in,
which may not require the server logic.  To use, you'd need to buy a
license and build and maintain your own version of the library, though.

**Comment by jrowen** [comment]
Let me know if you still have questions.
