### ISSUE TITLE
Cell Comments

### ISSUE THREAD

**Issue by Atan1988** [jrowen/rhandsontable#66]
Hi Jrowen,

     It seems that we should be able to add Comments to cells with hot_cell(1, 1, "Test Comment"),  however, it doesn't seem that comments are showing up when the cell in the output table is selected.

    Am I missing something regarding the cell comments?
    Also, is it possible to add comments to colHeader row?

Thanks a lot in advance!
Allen

**Comment by jrowen** [comment]
You're right, there's a bug with the comments.  I'll push a fix to the dev
version shortly.  Thanks for reporting.

**Comment by jrowen** [comment]
Let me know if you're still running into problems with the comments.  Thanks again for reporting.

**Comment by Atan1988** [comment]
Thanks,  Jonathan! I got busy with some other work and put the project aside. 
I would assume that I need to re-install the rhandsontable package, right?

Thanks again!
Allen

**Comment by Atan1988** [comment]
Jonathan,

       I updated my R to 3.2.3, and the rhandsontable package. However, I still can't see comments when hovering the cell. 

       I tried following code in the introduction:
       "DF = data.frame(val = 1:10, bool = TRUE, big = LETTERS[1:10],
                small = letters[1:10],
                dt = seq(from = Sys.Date(), by = "days", length.out = 10),
                stringsAsFactors = FALSE)

       rhandsontable(DF) %>%
                 hot_cell(1, 1, "Test comment")"

Thanks,
Allen

**Comment by jrowen** [comment]
For now, you need to install the dev version.

**Comment by jrowen** [comment]
You can install the dev version using
```
devtools::install_github("jrowen/rhandsontable")
```
You can see an example at http://jrowen.github.io/rhandsontable/#cell-comments.  Let me know if you still run into any problems.

**Comment by Atan1988** [comment]
I see, that makes sense! I will install the dev version. Please do let me know when the update go into CRAN. 
Thanks a lot!Allen

Date: Mon, 8 Feb 2016 12:09:18 -0800

**Comment by Atan1988** [comment]
It make sense that the CRAN version is not changed yet.  Thanks for the quick fix. The comment matrix method of adding comments is also very nice. 

However, although I am able to make the comments work with the example code, the comments are not showing up when used in my shinyapp within a renderRHandsontable() in the server.R code.   Am I missing something?

Thanks!
Allen

**Comment by jrowen** [comment]
I was able to confirm the examples work with a simple shiny app.  Can you
send a minimal example of the code giving you trouble?

**Comment by Atan1988** [comment]
Jonathan,
     
     You are right. When I was trying to build a simpler code to post here, it works fine. 
     I think the issue is actually that the comment in the cell seems to time out after a few seconds, so it appeared to not working on my more complicated app (takes a few button clicks, and a few renderUI statements before I get to see the table). 

     Is there a way that I can make the comment stay permanently?
     I have included a simplified sample code below. 

     Btw, I really like this package, which is enabling me to build a web-based insurance pricing model  in shiny to replace the fairly complicated excel workbook.  The tabgenerator function below is used to create tabs conditional on some user selections in the actual app.  
[testapp.txt](https://github.com/jrowen/rhandsontable/files/123259/testapp.txt)

Thanks again!
Allen

     `
library(shiny)
library(rhandsontable)

tablecreater <- function(x, n, p=10, br=T) {
  m <- data.frame(matrix("", ncol = length(x), nrow = n))
  m[] <- lapply(m, as.character)
  if (br) {
    colnames(m) <- colla(x, p)
  } else{
    colnames(m) <- x
  }
  return(m)
}

colla <- function(x, plen=10){
  if (length(plen) < length(x)) plen <- rep(plen[1], length(x))
  for (i in (1:length(x))) x[i] <- paste(strwrap(x[i], width = plen[i]), collapse = "<br>")
  return(x)
}

cols <- c("US/Can",  "Deviation",  "MFG Product To Own Specs (Incl. Mix/Blend)", 
          "MFG Product To Custom Specs (Tolling)", 
          "MFG by 3rd Party (Tolling By Others)", 
          "Distributor (No Repackaging, relabeling, mix / blend)",
          "Distributor (Repackaging and/or relabeling)",
          "Distributor (Foreign MFG)",
          "Broker / Drop Ship / MFG Rep (No Physical Possession)",
          "Processing", "Foreign Revenue")

db <- tablecreater(cols, n=30, p=c(20, 20, 20, rep(20, 13)))

tabgenerator <- function(x) {
  if (x=="GLCPLPLRating") return(GLCPLPLRatingtab())
}

GLCPLPLRatingtab <- function() {
  return(
    tabPanel("GL CPL PL Rating",
             fluidRow(
               column(12, div(rHandsontableOutput("FixedSiteRevAdjTb", width = "1440px"), 
                              style="Font-size:65%") ))))}

ui <- shinyUI(fluidPage(
  title = 'Test Example of Comments',
  uiOutput("mainUI")

))

server <- shinyServer(function(input, output, session) {
  
  output$mainUI <- renderUI({
    do.call(tabsetPanel, 
            lapply(c("GLCPLPLRating"),
                   tabgenerator))
  })
  output$FixedSiteRevAdjTb <- renderRHandsontable({
    kw <- rep(110, ncol(db))
    kw[1] <- 60
    kw[c(2)] <- 300
    rhandsontable(db, selectCallback = TRUE, rowHeaders=NULL,
                  strict=F, readOnly=T,
                  useTypes=T, height =750) %>%
      hot_table(highlightCol = TRUE, highlightRow = TRUE) %>%
      hot_cols(colWidths= kw*0.9) %>%
      hot_col(1, halign="htCenter", readOnly=F, strict =F, type="dropdown", 
              source=c("US", "Can")) %>%
      hot_cell(1, 3, "Test comment")
    })
})


runApp(list(ui=ui,server=server))
`

**Comment by jrowen** [comment]
Cool app.  I tried the example, and I don't have any issue seeing the comment.  Which browser are you using?  Also, have you tried looking at the JS console in the browser?

**Comment by Atan1988** [comment]
I am not familiar with the JS console, but I will look into that. I am using Google Chrome. 

This is actually the link to my app on shinyapps.io: https://allentanironshore.shinyapps.io/EnviroRater/
When I first log in by clicking "Log in" and "Submit", the comment will show up in the version table, however, if I click "log in" and "Submit" again, the comment will disappear. 

If I click "Open Rater", the comments won't show up at all in the rendered tabs. I think it might be something related to my complicated structure, but it can also be just related to my browser.  

Also, for my simple app, the comment only disappear in my Rstudio environment, but it would actually stick if I "Open Browser". 

Thanks!
Allen

**Comment by jrowen** [comment]
It's hard to debug without the source code, but the html source shows
additional comment tags added after each login click (the reset if the page
is reloaded).  I'd take a look at your code to be sure the comments are
cleared when then login link is clicked.

**Comment by Atan1988** [comment]
Thanks! I am sorry about not posting the source code. I didn't think of a way to create a simplified code, however I got some inspiration from your reply. 

I think this code demonstrates the problem I have. The comment will go away after a second set of "Log in" and "Submit" clicks.

`
library(shiny)
library(rhandsontable)

tablecreater <- function(x, n, p=10, br=T) {
  m <- data.frame(matrix("", ncol = length(x), nrow = n))
  m[] <- lapply(m, as.character)
  if (br) {
    colnames(m) <- colla(x, p)
  } else{
    colnames(m) <- x
  }
  return(m)
}

colla <- function(x, plen=10){
  if (length(plen) < length(x)) plen <- rep(plen[1], length(x))
  for (i in (1:length(x))) x[i] <- paste(strwrap(x[i], width = plen[i]), collapse = "<br>")
  return(x)
}

cols <- c("US/Can",  "Deviation",  "MFG Product To Own Specs (Incl. Mix/Blend)", 
          "MFG Product To Custom Specs (Tolling)", 
          "MFG by 3rd Party (Tolling By Others)", 
          "Distributor (No Repackaging, relabeling, mix / blend)",
          "Distributor (Repackaging and/or relabeling)",
          "Distributor (Foreign MFG)",
          "Broker / Drop Ship / MFG Rep (No Physical Possession)",
          "Processing", "Foreign Revenue")

db <- tablecreater(cols, n=30, p=c(20, 20, 20, rep(20, 13)))

tabgenerator <- function(x) {
  if (x=="GLCPLPLRating") return(GLCPLPLRatingtab())
}

GLCPLPLRatingtab <- function() {
  return(
    tabPanel("GL CPL PL Rating",
             fluidRow(
               column(12, div(rHandsontableOutput("FixedSiteRevAdjTb", width = "1440px"), 
                              style="Font-size:65%") )
             )
    )
  )
}



ui <- shinyUI(fluidPage(
  title = 'Test Example of Comments',
  fluidRow(
    column(2, actionButton("lg", "Log in"))
  ),
  uiOutput("mainUI")

))

server <- shinyServer(function(input, output, session) {
  observeEvent(input$lg, {
    isolate({
       output$mainUI <- renderUI({actionButton("sbm1", "Submit")})
      })
    }
  )
  
  observeEvent(input$sbm1, {
    isolate({
      output$mainUI <- renderUI({
        do.call(tabsetPanel, 
                lapply(c("GLCPLPLRating"),
                       tabgenerator))
      })
    })
  })
    

  output$FixedSiteRevAdjTb <- renderRHandsontable({
    kw <- rep(110, ncol(db))
    kw[1] <- 60
    kw[c(2)] <- 300
    rhandsontable(db, selectCallback = TRUE, rowHeaders=NULL,
                  strict=F, readOnly=T,
                  useTypes=T, height =750) %>%
      hot_table(highlightCol = TRUE, highlightRow = TRUE) %>%
      hot_cols(colWidths= kw*0.9) %>%
      hot_col(1, halign="htCenter", readOnly=F, strict =F, type="dropdown", 
              source=c("US", "Can")) %>%
      hot_cell(1, 3, "Test comment")
    })
})


runApp(list(ui=ui,server=server))
`
[testapp.txt](https://github.com/jrowen/rhandsontable/files/123748/testapp.txt)

**Comment by jrowen** [comment]
The widget's `resize` function calls `updateSettings` on the table, which apparently causes the table to lose the comments.  This seems like a bug in handsontable.  Thanks for being persistent.

**Comment by Atan1988** [comment]
Thanks! Looking forward to the fixed version.

Allen

**Comment by jrowen** [comment]
I pushed a temporary fix to the dev version that should preserve comments.

**Comment by jrowen** [comment]
Please re-open if this is still an issue.

**Comment by AMBudnik** [comment]
Hi @jrowen 
Here's an exact issue https://github.com/handsontable/handsontable/issues/3221 but I was calling `updateSettings` to change rowHeaders the comments stayed the same.
Can you share more details when there're gone?
