### ISSUE TITLE
Disable Scrollbar?

### ISSUE THREAD

**Issue by hsy9045** [jrowen/rhandsontable#67]
Hello,

Is there a way to disable scrollbar? In some cases, especially on a lower resolution screen, i found table outputs being like this:
![image](https://cloud.githubusercontent.com/assets/14853869/12984210/5c4304c4-d0b2-11e5-964d-e5fb45d5c160.png)
This is a table with only one row in a Shiny app. The actual content is blocked by the scroll bar. (I don't have a way to really reproduce what I saw... It just happens sometimes, and goes away after refresh. It is inside of a wellPanel with width set by fluid grid layout. I did not give the table specific height or width settings)

Any help is appreciated!

**Comment by jrowen** [comment]
You can override the css using an approach similar to the example below.
```
library(rhandsontable)
library(shiny)

server <- function(input, output) {
  output$mytable <- renderRHandsontable({
    rhandsontable(mtcars)
  })
}

ui <- fluidPage(
  fluidRow(rHandsontableOutput("mytable", width = "300px", height = "200px"))
  tags$head(
    tags$style(HTML("
      .handsontable {
        overflow: visible;
      }
    "))
  )
)

shinyApp(ui = ui, server = server)
```

**Comment by hsy9045** [comment]
This works great. thank you for the example!

**Comment by jrowen** [comment]
I pushed an update that should eliminate the need to override the css.  Please let me know how it works for you.
```
rhandsontable(mtcars, overflow = 'visible')
````
