### ISSUE TITLE
Data Entry Shiny Gadget

### ISSUE THREAD

**Issue by GShotwell** [jrowen/rhandsontable#68]
Thanks for the great package! I was thinking today that there might be some chance to spin off a neat little handsontable shiny gadget for data entry. This has always been a big missing RStudio feature for me, and a little lightweight spreadsheet input for creating small dataframes might be great. Have you put any thought into this already?

**Comment by jrowen** [comment]
Great idea, and I have thought about this a bit.  I've experimented with a RStudio addin enables one to edit an existing data.frame; you can install with the command below.
```
devtools::install_github("jrowen/rhandsontable", ref="addin")
```
There's no reason another version couldn't be created that allows one to create a new data.frame.  I'm very open to ideas, suggestions and contributions here.

**Comment by jrowen** [comment]
This has been rolled into the library.  Please let me know if you have any feedback.
