### ISSUE TITLE
fixed rows and columns issue with rstudio viewer

### ISSUE THREAD

**Issue by smartinsightsfromdata** [jrowen/rhandsontable#7]
I use the following code (modified from the examples) in the rstudio viewer:
```R
rhandsontable(MAT, width = 300, height = 150) %>%
  hot_cols( fixedColumnsLeft = 1) %>%
  hot_rows( fixedRowsTop = 1)
```
I would expect to see e.g. the left-most column fixed when scrolling, but the left column appears only highlighted. Same for top row.

On the other hand when I publish it on a web page is behaves as expected (I haven't got around to try it with knitr).

**Comment by jrowen** [comment]
I'm not seeing this with the latest packages as referenced in #3.  Can you confirm that it's still a problem?

**Comment by jrowen** [comment]
Closing because I can't re-produce.  Please re-open if the problem re-emerges.
