### ISSUE TITLE
Rowspan/colspan

### ISSUE THREAD

**Issue by Rustastra** [jrowen/rhandsontable#70]
Hi, thank you very much for such a useful tool! 
I was wondering if there is a functionality to use colspan/rowspan to merge some cells into one? 

Thanks a lot!

**Comment by jrowen** [comment]
I think the pro version of handsontable might support these features.

On February 26, 2016, at 12:15 PM, Rustastra <notifications@github.com> wrote:

Hi, thank you very much for such a useful tool! 
I was wondering if there is a functionality to use colspan/rowspan to merge some cells into one? 

Thanks a lot!

**Comment by Rustastra** [comment]
Thank you!

**Comment by mnazarov** [comment]
FYI, it is possible now with:
```r
library(rhandsontable)
rhandsontable(mtcars[1:6, ]) %>% 
    hot_table(mergeCells = list(
            list(row = 0, col = 1, rowspan = 2, colspan = 2),
            list(row = 2, col = 3, rowspan = 1, colspan = 4)
        ))
```
