### ISSUE TITLE
Rows misaligned

### ISSUE THREAD

**Issue by Rustastra** [jrowen/rhandsontable#71]
Hi, I have seen this issue being discussed in handsontable.js, but couldn't get clarity on the solution.
The problem is that when using fixed columns, rows get misaligned. Is there a way to fix it?
Many thanks! 
![misal](https://cloud.githubusercontent.com/assets/6806509/13568617/62f4a0c8-e45a-11e5-9759-fe6da4204602.PNG)

**Comment by jrowen** [comment]
If you can you share a minimally reproducible example, I'll take a look.
Thanks.

**Comment by Rustastra** [comment]
Here is an example. If you scroll left and down or down and left, rows get misaligned. In my app, the misalignment is worse than what you see with this one, but still it happens even here. Thanks a lot!

Attaching txt as I somehow cannot attach archives. Thanks!
[ui.txt](https://github.com/jrowen/rhandsontable/files/163070/ui.txt)

[server.txt](https://github.com/jrowen/rhandsontable/files/163066/server.txt)

**Comment by Rustastra** [comment]
Also this example experiences problems with scrolling in chrome (but not in ie)

**Comment by jrowen** [comment]
Using the dev version of the library, I'm not running into this issue wtih the example below.
```
library(rhandsontable)
library(shiny)

server <- function(input, output) {
  output$mytable <- renderRHandsontable({
    rhandsontable(mtcars) %>%
      hot_cols(fixedColumnsLeft = 1) %>%
      hot_rows(fixedRowsTop = 1)
  })
}

ui <- fluidPage(
  fluidRow(rHandsontableOutput("mytable", width = "300px", height = "200px"))
)

shinyApp(ui = ui, server = server)
```

**Comment by jrowen** [comment]
This might also be of interest: https://github.com/handsontable/handsontable/issues/2218

**Comment by Rustastra** [comment]
So I found that if I remove checkboxes from a fixed column, the table gets displayed just fine.
Also, if a larger font is used in the fixed column, it causes problems

**Comment by jrowen** [comment]
I've run across some font problems as well (see https://github.com/handsontable/handsontable/issues/3320).  Checkboxes are working fine on the example page (http://jrowen.github.io/rhandsontable/), so this is difficult to debug.  Can you distill the issue into a simple example?  From there, I can dig into things a bit more.

**Comment by Rustastra** [comment]
None of the examples there has checkboxes in the fixed columns :) I will try to write an example code. But so far what was the most useful is making sure all borders and fonts are of the same size

**Comment by jrowen** [comment]
You can also play around with the table setting [here](http://jsfiddle.net/jrowen/fw3bbhax/).

**Comment by jrowen** [comment]
I think this now fixed.  Please re-open if you're still running into issues.  Thanks.
