### ISSUE TITLE
Currency Formatting

### ISSUE THREAD

**Issue by hsy9045** [jrowen/rhandsontable#73]
Hello, is it possible to format numeric columns in different currency denominations other than US dollar? (In my case it would be euro). I'd imagine it is something in `hot_col(colname, format = "$0,0")`, but I couldn't make it work.. 
Thank you for this great package.

**Comment by jrowen** [comment]
It looks like I need to add the [numerial.js](http://numeraljs.com/) languages scripts to the library to support different locales (and add a `language` parameter to `hot_col`).  I'll make an update shortly and let you know when it's available for testing.  Thanks for reporting.

**Comment by hsy9045** [comment]
Thank you. Looking forward to the update version!

**Comment by jrowen** [comment]
I made some updates to the dev version, please take a look if you have time and let me know if things are now working as expected.  Thanks again for reporting.
```
DF = data.frame(val = 1:10, 
                bool = TRUE, 
                big = LETTERS[1:10],
                small = factor(letters[1:10]),
                dt = seq(from = Sys.Date(), by = "days", length.out = 10),
                stringsAsFactors = FALSE)

rhandsontable(DF) %>%
  hot_col("val", format = "0.00 $", language = "de")
```

**Comment by hsy9045** [comment]
Hi jrowen, thanks for the update. I tried the dev version out and it works just as expected!

**Comment by hsy9045** [comment]
Hello, I updated the package today to the latest dev version. I can't seem to make the language parameter work again :( The example above renders empty to me. 

Here is my sessionInfo()
```
R version 3.3.1 (2016-06-21)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rhandsontable_0.3.3.1

loaded via a namespace (and not attached):
[1] htmlwidgets_0.7 magrittr_1.5    htmltools_0.3.5 tools_3.3.1     yaml_2.1.13     Rcpp_0.12.7     jsonlite_1.1    digest_0.6.10  
```

**Comment by jrowen** [comment]
Handsontable updated the formatting library.  You can find a current example at http://jrowen.github.io/rhandsontable/#specify_locale.

**Comment by hsy9045** [comment]
Ah, thanks for the prompt response and great documentation.
