### ISSUE TITLE
Ctrl+C copy feature in RHandsOnTable won't work inside a BSModal window in Shiny

### ISSUE THREAD

**Issue by willglanville** [jrowen/rhandsontable#75]
Trying to use RHandsontable as a data input within a BSModal (from shinyBS) in Shiny.

Table renders ok, but I'm unable to copy and paste within the table.

Here is a simple example...

    library(shiny)
    library(rhandsontable)
    library(shinyBS)

    ui = shinyUI(fluidPage(

      mainPanel(

        fluidRow(
          bsModal("myModal", 
                  "Modal Title", 
                  "launchmodalbutton", 
                  rHandsontableOutput("tableInModal") 
          ),
          actionButton("launchmodalbutton","Launch Modal")
        )

      )

    ))

    server = function(input, output) {

      output$tableInModal <- renderRHandsontable({

        DF = data.frame(values = 1:10, secondColumn = 21:30)

        rhandsontable(DF)%>%
          hot_col(col=c("values","secondColumn"),copyable=TRUE)

      })

    }

    shinyApp(ui = ui, server = server)

Any ideas?

Thanks in advance.

**Comment by willglanville** [comment]
Closing as sounds like this isn't an issue with the package. 

http://stackoverflow.com/questions/16021043/enable-copy-paste-option-in-window-showmodaldialog

**Comment by jrowen** [comment]
I can reproduce this issue found the following interesting links:
- [Bootstrap Modal incompatibilities](https://github.com/handsontable/handsontable/issues/1618)
- [jsfiddle working example](http://jsfiddle.net/5Zv8h/4/embedded/result/)

**Comment by julesair** [comment]
I have the same issue here. Is there any workaround?
