### ISSUE TITLE
Customizing context menu to delete rows and trigger an action

### ISSUE THREAD

**Issue by debsush** [jrowen/rhandsontable#76]
Hi,

I would like my context menu to have the option to delete rows but not insert rows.  Is it doable?

Can I have the delete rows option in my context menu for a read only table?

When someone deletes a row in rhandsontable, will the row in the underlying data table/data frame also get deleted.  If no, what event can the program use to trigger a separate logic to also change the underlying data table/frame?

**Comment by jrowen** [comment]
To customize the context menu, you'll need to disable all the options in 'hot_context_menu' and then specify your own 'customOpts' (see [here](https://github.com/jrowen/rhandsontable/blob/master/R/rhandsontable.R#L238-318) and [here](http://jrowen.github.io/rhandsontable/#customizing) for ideas).

Take a look at the [shiny examples](http://jrowen.github.io/rhandsontable/#shiny) to better understand how you can keep the table in sync with an underlying data.frame.

**Comment by debsush** [comment]
The shiny dashboard example does not open.  It shows a 404 Error

**Comment by debsush** [comment]
Thank you.

**Comment by jrowen** [comment]
I may have hit the hourly limit for the month, but it should work if you
run it locally.

**Comment by debsush** [comment]
Thank you. This works and would appreciate your help on this last bit.

In the datafile example, the new updated instance of the htmlwidget gets written into the dataframe only when save button is clicked. I would like the action to take place when the remove row option is selected by the user. I am assuming I will use a call back like below but I do not thing the callback will be attached to hot_col

rhandsontable(cars, readOnly = TRUE, selectCallback = TRUE) %>%
  hot_rows(callback= "function (instance, row) {
           Shiny.onInputChange("rowremoveflag", row);
           }
observe({
input$rowremoveflag
if (!is.null(values[["hot"]])) {
cars<<-values[["hot"]]
}
})

Can you please help me so that on choosing the delete rows, the R script gets triggered to write the new values of hot onto the data frame. I do not want to add a new additional step for the user by having a "Save" button

**Comment by debsush** [comment]
I also tried the below but it did not yield the result

    output$hot = renderRHandsontable({
      DF = data.frame(val = 1:10,
                      bool = TRUE,
                      big = LETTERS[1:10],
                      small = factor(letters[1:10]),
                      dt = seq(from = Sys.Date(), by = "days", length.out = 10),
                      stringsAsFactors = FALSE)
      
      rhandsontable(DF, search = TRUE, width = 550, height = 300) %>%
        hot_context_menu(
          customOpts = list(
            remove_row = list(name = "Remove Row",
                              callback = htmlwidgets::JS(
                                "function () {                                  
                                  var ht = $('.hot-contain-div').handsontable('getInstance');
                                      ht.alter('remove_row');
                                      ht.render();
                                      e.preventDefault();
                                    Shiny.onInputChange("rowremoveflag", row);
                             }"))))
    })

**Comment by debsush** [comment]
I got it to work like below but it only removes the last row not the selected row. Wonder what am I missing

    output$hot = renderRHandsontable({
  DF = data.frame(val = 1:10,
                  bool = TRUE,
                  big = LETTERS[1:10],
                  small = factor(letters[1:10]),
                  dt = seq(from = Sys.Date(), by = "days", length.out = 10),
                  stringsAsFactors = FALSE)

  rhandsontable(DF, search = TRUE, width = 550, height = 300) %>%
    hot_context_menu(
      customOpts = list(
        remove_row = list(name = "Remove Row",
                          callback = htmlwidgets::JS(
                            "function () {
                                  this.alter('remove_row');
                                  this.render();
                                 Shiny.onInputChange("rowremoveflag", row);
                         }"))))
})

  values = reactiveValues()
  setHot = function(x) values[["hot"]] = x
  

  observe({
  input$rowremoveflag
    cars<<-values[["hot"]]
  })

**Comment by jrowen** [comment]
The example below will allow you to completely override the context menu.  See the source `hot_context_menu` source for more options.
```
hot = rhandsontable(DF)
hot$x$contextMenu = list(items = c("row_above", "row_below"))
hot
```

Table change events are caught by shiny, so there's no need to use a save button to capture updates.  Check out some of the other examples for more details.

**Comment by debsush** [comment]
Thank you.  Excellent
