### ISSUE TITLE
sorting doesnt work

### ISSUE THREAD

**Issue by xhudik** [jrowen/rhandsontable#80]
Hi, it seems sorting facilities dosnt work. I was trying to follow: http://jrowen.github.io/rhandsontable/#sorting
See:
```
n= sample(seq(1:1000),size=10)
DF = data.frame(val1 = n, val2=n, stringsAsFactors = FALSE)
rhandsontable(DF, rowHeaders = NULL) %>%
     hot_cols( columnSorting=TRUE)
```
columns are not sorted:
_Val1 Val2
81	981
921	921
876	876
801	801
739	739
735	735
563	563
489	489
374	374
306	306_

Not sure, am I missing something here?

thanks!

**Comment by jrowen** [comment]
Your example should enable row sorting by clicking on the column name in
the table.  You'll need to sort your data.frame before passing it to the
widget if you want it sorted from the start.

**Comment by xhudik** [comment]
thanks  jrowen  for the fast answer!

good - so columnSorting=TRUE enable to click on the column name in order to sort the column
