### ISSUE TITLE
date field in description

### ISSUE THREAD

**Issue by WMBEdmands** [jrowen/rhandsontable#83]
very minor but i wish to cite your package and I am getting the error:  
In citation("rhandsontable") :
no date field in DESCRIPTION file of package 'rhandsontable'
Thanks for the good work.

**Comment by jrowen** [comment]
I think this might be a bug in R (see [here](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16550)).  It appears that a `Packaged` field [should be added by CRAN](http://www.hep.by/gnu/r-patched/r-exts/R-exts_4.html).  I'm not really sure how to resolve this and am open to suggestions.

**Comment by jrowen** [comment]
This shouldn't be an issue if installing from CRAN (see [here](https://github.com/hadley/devtools/issues/1327) for more details).
