### ISSUE TITLE
Ghost data in table

### ISSUE THREAD

**Issue by sbihorel** [jrowen/rhandsontable#85]
Hi,

I have some problems with what appears to be ghost data when using rhansontable in a Shiny app. in the following code, the intent is to store the content of the edited rhandsontable in a reactiveValues object slot upon a button click (note that the code is actually a simplified version of a much more complex app which requires other settings to be stored upon this button click). The reactiveValues  slot is dependent upon the selection made in a selectInput field.

Let's assume that the user make some edits in the table and change the selection in the selectInput field WITHOUT clicking the Save button. The change in this selection field apparently resets the content of the rhandsontable, which is what I would anticipate. However, if the user clicks on the Save button, the edits made prior to the apparent reset are restored and saved, suggesting that sort of their persistence somewhere.

Is this a bug or am I misunderstanding the basic workings of rhandsontables? In the later case, is there a fix.

Thanks for your input
```

require(shiny)
require(rhandsontable)

server <- function(input, output, session){
  
  tArray <- reactiveValues()
  
  output$table <- renderRHandsontable({
    
    if (!is.null(tArray[[input$select]])){
      rhandsontable(
        data = tArray[[input$select]],
        rowHeaders = NULL
      )
    } else {
      rhandsontable(
        data = data.frame('Variable' = rep('', 15),
          'Expression' = rep('', 15),
          stringsAsFactors = FALSE),
        rowHeaders = NULL)
    }
    
  })
  
  observeEvent(
    input$saveBtn,
    {
# browser()
      if (!is.null(input$table))
        tArray[[input$select]] <- hot_to_r(input$table)
    }
  )

}

ui <- fluidPage(
  selectInput(inputId = 'select',
    label = 'Select a slot',
    choices = letters[1:3]),
  
  rHandsontableOutput('table'),
  
  actionButton('saveBtn', 'Save')
)

shinyApp(ui = ui, server = server)


```

**Comment by sbihorel** [comment]
After the rhandsontable calls, the output shown in the UI is updated, but it it looks like the input$table is not.

**Comment by jrowen** [comment]
I'm unable to run your example.  Could you please double-check the code?  Thanks.

**Comment by sbihorel** [comment]
There were 2 superfluous parentheses at the end of the code. I have updated the code in my 1st post. It is running on my machine

>sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rhandsontable_0.3.1 shiny_0.13.2       

loaded via a namespace (and not attached):
 [1] htmlwidgets_0.6 magrittr_1.5    R6_2.1.2        htmltools_0.3.5 tools_3.3.0     yaml_2.1.13    
 [7] Rcpp_0.12.5     jsonlite_0.9.20 digest_0.6.9    xtable_1.8-2    httpuv_1.3.3    mime_0.4

**Comment by jrowen** [comment]
I can now run the code, but I'm unable to reproduce the situation you mention.  If you can share the specific steps I need to follow, I'll take another look.

I'd also suggest adding some `print` calls to the app to see what is being saved and what is being loaded.  This might help trace what's happening behind the scenes.

**Comment by sbihorel** [comment]
One example of sequence that reveal the problem:
1- open the app
2- keep the selection in the selectInput to "a"
3- make any edits you want in the rhandsontable
4- change the selection in the selectInput to "b": observe that the content of the rhandsontable appears to be erased
5- click on the save button: observe that the edits made at step 3 are now not only visible in the rhandsontable and were saved into the "b" slot of the tArray reactiveValues object, while one would expect to same a blank table.

I am not quite sure where it would make the more sense to add print calls to help debugging, but when I was trying to look under the hood on this code, I used a browser call inside the observeEvent associated with the Save button. I have added it as a comment in the code. 

-

**Comment by jrowen** [comment]
I think you also want to set the reactive value to an empty table when you
first initialize the table.  See the example at the link below.

https://github.com/jrowen/rhandsontable/tree/master/inst/examples/rhandsontable_datafile

**Comment by sbihorel** [comment]
Hi,

I have modified the code following the example you suggested but this does not change the result. The steps I previously described still result in incorrect data being saved.
```

require(shiny)
require(rhandsontable)

server <- function(input, output, session){
  
  tArray <- reactiveValues()
  
  output$table <- renderRHandsontable({
    
    if (!is.null(tArray[[input$select]])){
      DF <- tArray[[input$select]]
    } else {
      DF <- data.frame('Variable' = rep('', 15),
        'Expression' = rep('', 15),
        stringsAsFactors = FALSE)
    }
    
    tArray[[input$select]] <- DF
    
    rhandsontable(
      data = DF,
      rowHeaders = NULL
    )
    
  })
  
  observeEvent(
    input$saveBtn,
    {
      browser()
      if (!is.null(input$table))
        tArray[[input$select]] <- hot_to_r(input$table)
    }

```

If I execute the code above, go through the steps described above (at step3, I enter "a" in the 1st three rows of the variable column), upon clicking on the Save button, the browser() call kicks in and one can easily see that the content of input$table$data was not updated even through the table render in the application was:

> Browse[1]> str(input$table$data)
> List of 15
>  $ :List of 2
>   ..$ : chr "a"
>   ..$ : chr ""
>  $ :List of 2
>   ..$ : chr "a"
>   ..$ : chr ""
>  $ :List of 2
>   ..$ : chr "a"
>   ..$ : chr ""
>  $ :List of 2
>   ..$ : chr ""
>   ..$ : chr ""
>  $ :List of 2
>   ..$ : chr ""
>   ..$ : chr ""
>  $ :List of 2
>   ..$ : chr ""
>   ..$ : chr ""
>  $ :List of 2
>   ..$ : chr ""
>   ..$ : chr ""
>  $ :List of 2
>   ..$ : chr ""
>   ..$ : chr ""
>  $ :List of 2
>   ..$ : chr ""
>   ..$ : chr ""
>  $ :List of 2
>   ..$ : chr ""
>   ..$ : chr ""
>  $ :List of 2
>   ..$ : chr ""
>   ..$ : chr ""
>  $ :List of 2
>   ..$ : chr ""
>   ..$ : chr ""
>  $ :List of 2
>   ..$ : chr ""
>   ..$ : chr ""
>  $ :List of 2
>   ..$ : chr ""
>   ..$ : chr ""
>  $ :List of 2
>   ..$ : chr ""
>   ..$ : chr ""

**Comment by jrowen** [comment]
The table is a "live" shiny widget, so every time you update it, the data is stored.  Add the code below to your app and you'll see this occur.
```
observeEvent(
    input$table,
    {
      print("Table change")
    }
)
```
The widget functions as both an input and an output, which is likely behind this issue.  Even though you're resetting the output, the input version of the widget appears to be caching the data.  There's something going on under the hood with shiny that I don't quite have a handle on yet.  Maybe @jcheng5 has a suggestion.

**Comment by jrowen** [comment]
Here's an approach without a save button, which might work better.
```
require(shiny)
require(rhandsontable)

server <- function(input, output, session){
  
  tArray <- reactiveValues()
  
  output$table <- renderRHandsontable({
    
    if (!is.null(tArray[[input$select]])){
      DF <- tArray[[input$select]]
    } else {
      DF <- data.frame('Variable' = rep('', 15),
                       'Expression' = rep('', 15),
                       stringsAsFactors = FALSE)
    }
    
    tArray[[input$select]] <- DF
    
    rhandsontable(
      data = DF,
      rowHeaders = NULL
    )
    
  })
  
  observeEvent(
    input$table,
    {
      print("Table change")
      if (!is.null(input$table))
        tArray[[input$select]] <- hot_to_r(input$table)
    }
  )
}

ui <- fluidPage(
  selectInput(inputId = 'select',
              label = 'Select a slot',
              choices = letters[1:3]),
  
  rHandsontableOutput('table')
)

shinyApp(ui = ui, server = server)
```

**Comment by sbihorel** [comment]
Hi,


Thanks for the revised code. I will have to assess how this works within
the more complex app I am developing.

Following up on your other email, I was wondering if there is a way in
GitHub to send public or private messages to Joe Cheng. I apologize for
this newbie question, but I have started to use Github only recently...
I guess I could always post on the Shiny discuss group if there is no
messaging capabilities within Github.

Thanks

**Comment by jrowen** [comment]
Sometimes it's listed in a user's profile.

**Comment by jrowen** [comment]
I made some updates to the dev version related to shiny input handling and would be curious to know if they fix the issue you're experiencing.

**Comment by sbihorel** [comment]
Thanks a lot!

Your latest dev version fixed the problem that used to happen when executing the code included in my very first post.

DO you have an estimated date for an official release in CRAN?

**Comment by jrowen** [comment]
This should be on CRAN shortly. Please re-open if you're still running into issues.  Thanks.

**Comment by sbihorel** [comment]
Hi,

Version 0.3.3 released on Aug 26 does not seem to include the fix available in the development code. Is this correct?

**Comment by jrowen** [comment]
That's correct.  There are some fixes in the development version that
haven't been released to CRAN yet.

**Comment by sbihorel** [comment]
Hi,

Do you know when you will push this fix to a stable version?

Thanks

**Comment by jrowen** [comment]
A new release went out today.
