### ISSUE TITLE
Control width of rownames column

### ISSUE THREAD

**Issue by bklingen** [jrowen/rhandsontable#86]
Is there a way to control the width of the very first column of the table that holds the rownames (when rowHeaders is not NULL). When providing costum rownames, they may not fit into the default column width and get cut off. Interestingly, for colnames, the width adjusts automatically if longer names are provided.
Here is a very short reproducible example to  show what I mean. The first column with the rownames is not wide enough to display the labels, while the long column header is not a problem:

rhandsontable(data.frame("Long Column Header" = rnorm(3)), rowHeaders=c("Long Label 1", "Label 2", "Another long Label"))

Using hot_cols() with colWidths=  doesn't help either, as it can't  access the first  column with the labels.

**Comment by bklingen** [comment]
Great! Looking forward to it.
Thank you!

Bernhard

**Comment by bklingen** [comment]
Works like a charm now. Thank you.

**Comment by KiprasKancys** [comment]
How about rownames alignment? There is no way to align to left?

**Comment by jrowen** [comment]
I don't think this is an option with handsontable (http://docs.handsontable.com/0.31.0/demo-alignment.html).  You might be able to create some custom css control the alignment, though.

**Comment by yosch123** [comment]
Is there any way to manually set the size of some columns and have the other columns sized automatically?

**Comment by yosch123** [comment]
Thanks! I didn't realize I could do that.
