### ISSUE TITLE
Strange rendering in shiny with custom column headers

### ISSUE THREAD

**Issue by bklingen** [jrowen/rhandsontable#87]
I would like to provide custom column headers to a rhandsontable in an shiny app. See the app below. The problem: Specifying a column header that has a space. For instance, when typing "Two Lines" into the column header box in the shiny app below, the rhandsontable displayed in the sidebar panel gains another row which shouldn't be there. Here is the screenshot from the app below:

![image](https://cloud.githubusercontent.com/assets/4784206/16579150/ac541224-429e-11e6-863d-9eb467b3dc66.png)

Using stretchH="all" somehow solves the problem, but I don't want to stretch all columns. Maybe there is a workaround with fixedColumnsLeft, but in any case, the rendering in the default version seems odd. If one increases the width of the first column manually, the table renders fine again.

![image](https://cloud.githubusercontent.com/assets/4784206/16579191/dd21aaba-429e-11e6-80dd-7c939d885e93.png)

Thanks!

Here is the code for the shiny app:

```{r}
library(shiny)
library(rhandsontable)
library(stringr)

myApp <- list(
ui = fluidPage(
       sidebarLayout(
         sidebarPanel(
           textInput("colnames", "Enter Column Names (separated by comma)", 
                     value="", placeholder = "A, B"),
           h5(tags$b("Enter counts for 2 x 2 contingency table:")),
           rHandsontableOutput("hot")
         ), #end sidebarPanel
         mainPanel(
         ) #end mainpanel
      ) #sidebarlayout
),
server = function(input, output, session) {
output$hot <- renderRHandsontable({
  if (is.null(input$hot)) init <- matrix(0,ncol=2,nrow=2)
  else init <- hot_to_r(input$hot)
  mytab <- rhandsontable(init, 
             colHeaders=str_trim(unlist(strsplit(input$colnames,","))), 
             rowHeaders=c("One", "Two")) %>% 
           hot_cols(manualColumnResize=TRUE)
})
}
)

runApp(myApp)
```

**Comment by jrowen** [comment]
I'm unable to reproduce this with the dev version of the library.  Could you try it out?
```
devtools::install_github("jrowen/rhandsontable")
```

**Comment by bklingen** [comment]
I did and still got the same behavior. Could you run the above shiny code in R Studio? (I had a typo in ```library(stringer)``` which was supposed to read ```library(stringr)```, which is now corrected.) 
This behavior does not occur when not running in shiny. I.e., 

```{r}
rhandsontable(matrix(0,2,2), colHeaders=c("Two Lines", "Not Two Lines"), rowHeaders=c("One", "Two"))
```
gives the desired output.

**Comment by jrowen** [comment]
I think this is a bug with handsontable, whereby the first column width is staying fixed while the column names is wrapped.  The row name column is not refreshing after the column name row resizes.  A quick fix would be to use `hot_cols` to set `colWidths` based on the new name.  I'll have to think about a more permanent fix.

**Comment by bklingen** [comment]
using ```colWidths``` inside ```hot_cols``` works fine
