### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by Rustastra** [jrowen/rhandsontable#88]
Hello,

I am trying to display the number with 5 digits. It does show 5 digits, but the last one is always zero. 
hot_col("Spot", format = "0,0[.]00000")

Can't figure out what to do about this.
Thanks!

**Comment by jrowen** [comment]
Take a look at the documentation for http://numeraljs.com.  

Note that handsontable recently switched to http://numbrojs.com for number formatting, but rhandsontable hasn't been upgraded to that version yet

**Comment by Rustastra** [comment]
Even if I don't format the column, the number gets truncated. Also when I check the reactive value that stores the hot_to_r table, the numbers have 4 digits. Do you think it might be an issue with hot_to_r?
Thank you!

**Comment by jrowen** [comment]
I think jsonlite::toJSON defaults to 4 digits.

**Comment by Rustastra** [comment]
Is there a way around it?

**Comment by jrowen** [comment]
I can look into adding a parameter for digits.

**Comment by Rustastra** [comment]
What worked is just to specify htmlrenderer, and do numeric validation manually:
rhandsontable(rv$xx,height=450,width=1000) %>%
                    hot_table(highlightCol = TRUE, highlightRow = TRUE,contextMenu = FALSE)%>%
                    hot_col(14,renderer = htmlwidgets::JS("safeHtmlRenderer"))


observeEvent(input$hedges,{
              #  validate
          })

**Comment by stla** [comment]
Thank you @Rustastra this is what I was looking for.  I always got two digits, even after setting `digits=14`, but` %>% hot_cols(renderer=htmlwidgets::JS("safeHtmlRenderer"))` is fine. 
@jrowen This deserves to be documented.

**Comment by sumeda85** [comment]
I have the same problem. My original data have up to 6 digits =, but it rhandsontable shows up to 4 digits. 
What should I write inside 

observeEvent(input$hedges,{
# validate
})

**Comment by wlandau-lilly** [comment]
I am using `rhandsontable` 0.3.4 on R 3.4.0 (Red Hat). For me, numerics are only displayed to 2 digits past the decimal, and any new data I enter is rounded to the nearest hundredth.

```r
DF = data.frame(val = as.numeric(1:10))
rhandsontable(DF, digits = 6)
```

**Comment by lauratrann** [comment]
Was this ever addressed? Using format = '000+0' seems to fail to provide me with an exponential.

**Comment by jrowen** [comment]
Does the information at http://jrowen.github.io/rhandsontable/#formatting help?  The numeral.js JavaScript library is used for formatting.

**Comment by lauratrann** [comment]
Looked into that, but it didn't help in explaining why I couldn't do exponential formatting. It's odd, as I can force the other formats to work, but when input the style for exponentials, I simply get it stuck in decimal form.

**Comment by jrowen** [comment]
Did you try '0.00e+0'?  There are more examples at http://numeraljs.com.

**Comment by lauratrann** [comment]
Yes. I had already looked into the numeraljs formatting style. 
This is my code snippet with the formatting.  : 
      g <<- rhandsontable(values$data , readOnly = TRUE) %>%
        hot_cols(colWidths = 100, format = '0.00e+0') 
However this is the resulting table I receive
![snippet](https://user-images.githubusercontent.com/16411505/29946327-bd75f24a-8e59-11e7-8b58-930a5d9cec9b.PNG)

**Comment by stla** [comment]
``handsontable` does not use `numeral.js`, but `numbro.js`: <http://numbrojs.com/format.html>

**Comment by jrowen** [comment]
You are exactly right.  They made a change recently, but I failed to update the documentation.  Thanks for pointing this out.

**Comment by lauratrann** [comment]
numbrojs doesn't appear to have documentation for formatting a number as an exponent.

**Comment by jrowen** [comment]
I noticed that as well, but there appears to be a rewrite underway, which
could enable exponential formatting (see
https://github.com/BenjaminVanRyseghem/numbro/pull/305 and the reference to
BigNumber).

As an interim fix, you could write a custom renderer that formats numbers
as exponential.

**Comment by BenjaminVanRyseghem** [comment]
I add a todo on 2.0.0 to force exponential rendering (to me BigNumber support was more for number manipulating)
