### ISSUE TITLE
A comment on the design

### ISSUE THREAD

**Issue by smartinsightsfromdata** [jrowen/rhandsontable#9]
@jrowen I just run a trace between client and server in shiny to see what is exchanged.

I can see that the table data gets back and forth between client and server.  I guess there are pos and cons with each approach.  On the other hand I was surprised to see that even just selecting a cell with the mouse (without writing anything) was generating the data to be sent to the server.

Do you plan (long term maybe?) to study an optimisation of this?

E.g. you are familiar with trestletech approach (and its pitfall)...

**Comment by jrowen** [comment]
I'd forgotten about the select callback and added a param, `selectCallback`, that disables it by default.  

Passing only changes makes it challenging to support all handsontable functionality and would require a lot more server and client-side logic in shiny to keep things in sync and handle errors.  That being said, it would be possible to add a param that dictates whether the full dataset and/or only changes are passed to the server with the afterChange event.  Choosing to pass only changes would likely require disabling row/col adds and deletes.  This could also lead to the widget becoming out-of-sync with the server (`shinyTable` includes additional logic to keep thing in sync).

Optimization is certainly be in scope, so please continue to share suggestions.  At some point it would be interesting to test the performance using a large dataset.

**Comment by jrowen** [comment]
BTW, I appreciate all of the feedback and would be happy to add you as a package contributor.  If you agree, either send me your info or create a pr with the addition.  Thanks again.

**Comment by smartinsightsfromdata** [comment]
@jrowen I will be honoured to be a contributor.  I'll send a PR shortly.
I will be happy to do some testing with larger tables, as well as some testing with a remote server with shiny.
Incidentally, to work with shiny server (and using a remote server: I use a digital ocean droplet for testing) has been an eye opener: you can really see the impact of the handshake between client and server.

A minor thing (learned thanks to the folks involved in htmlwidgets) is that there is a difference between sending a json serialisation of a data frame to the client  in “long” form, i.e. an array of named vectors (more efficient),  or row first, i.e. in  “wide” form as an array of objects each of which includes all names and values (more time consuming over the network).  

Actually I meant to comment on the row/col add and deletes (and in general on the right-click menu).
- row/col add and delete make sense: a) if they make sense in a specific use case; b) if the application logic supports it.  For example, if I want to develop a simple budgeting app with shiny, I could let the user decide on which items to  budget asking to add them using this feature. But this would probably be a specific "moment" in the application flow: from then on row/col would be fixed (e.g. to simplify program logic and give consistency between different steps in the flow). 
- This leads to the menu.  It would be good to be able to select the features that go on it, either directly (through a list?) or indirectly (i.e. depending on the selected features: I may not want to add row/col but I may want save to csv).

**Comment by jrowen** [comment]
Let me know what you think of this approach.

**Comment by jrowen** [comment]
#12 is an interesting case for processing changes instead of loading the whole table.

**Comment by jrowen** [comment]
Thanks for the feedback.  Please keep it coming.
