### ISSUE TITLE
make Only part of the column read-only

### ISSUE THREAD

**Issue by Atan1988** [jrowen/rhandsontable#90]
Hi Jonathan,

    Is there a way for me to make part of the column read-only?
    I have a table contains Vehicle type and price to be charged, and I want  last couple rows to allow user to enter vehicle types not listed, and they can put a flexible price. 

Thanks,
Allen

**Comment by jrowen** [comment]
You could probably make a [custom renderer to make partial columns readonly](http://docs.handsontable.com/0.26.0/demo-read-only.html).

You can use the [minSpareRows parameter to add empty rows to the table](https://docs.handsontable.com/0.26.0/demo-pre-populating.html), but shiny support hasn't been implemented.

**Comment by Atan1988** [comment]
Thank you for the quick reply! My understanding of JS is next to nothing, but it feels interesting to learn. 
However, I am not able to figure out where to put the renderer.  
Would you please help me with the code below?
`
DF <- data.frame(Car = c(rep("Nissan", 2), "Chrysler", "Volvo"),
                 Year = seq(2012, 2015, 1), 
                 "Chassis Color" = c("black", "blue", "yellow", "white"),
                 "Bumper color" = c("black", "blue", "black", "grey"))

rhandsontable(DF, 
              width = 800, height = 450, rowHeaders = FALSE) %>%
  hot_cols(colWidths = c(200, 200, 200, 200)) %>%
  hot_col(4, renderer = "
    function(instance, td, row, col, prop, value, cellProperties) {
      var cellProperties = {}

      if (row === 2 && col === 4) {
          cellProperties.readOnly = true;
      }
      Handsontable.renderers.TextRenderer.apply(this, arguments);
      return td, cellProperties;
    }") `

Thank you very much!

Allen

**Comment by jrowen** [comment]
This example might help: http://jrowen.github.io/rhandsontable/#conditional_formatting

**Comment by Atan1988** [comment]
Cool. That example makes sense, and I was able to make it work.

**Comment by unitroot** [comment]
@Atan1988 I know it's been a long time, but is there any chance you still have that code and might share it here, I am stuck on the same issue. 

I solved it with a function that can be applied to a column.

``` r
hot_block_range <- function(hot, row, col, readOnly = TRUE) {
  if (length(col) > 1) stop("hot_block_range can only be applied to one column!")
  if (is.character(col)) col = which(hot$x$colHeaders == col)
  
  for (i in seq_len(length(row))) {
  cell = list(row = row[i] - 1, col = col - 1)
  
  if (!is.null(readOnly)) cell$readOnly = readOnly
  
  hot$x$cell = c(hot$x$cell, list(cell))
  }
  hot
}
```

However, I would rather have it in the renderer - easier to maintain and less issues with future package versions.

**Comment by Atan1988** [comment]
@unitroot 
sorry for the late reply, this is a working example, in case you still need it or someone else might stumble across this thread:
`library(rhandsontable)
DF <- data.frame(Car = c(rep("Nissan", 2), "Chrysler", "Volvo"),
                 Year = seq(2012, 2015, 1),
                 "Chassis Color" = c("black", "blue", "yellow", "white"),
                 "Bumper color" = c("black", "blue", "black", "grey"))

rhandsontable(DF,   width = 800, height = 450, rowHeaders = FALSE) %>%
  hot_cols(colWidths = c(200, 200, 200, 200)) %>%
  hot_cols(renderer = "
function(instance, td, row, col, prop, value, cellProperties) {
   Handsontable.renderers.NumericRenderer.apply(this, arguments);
             if (row === 2) {
              td.style.background = 'lightgrey';
              cellProperties.readOnly = true;
             } 
}") 
`

**Comment by unitroot** [comment]
Thanks, @Atan1988, glad you still had it :)
