### ISSUE TITLE
Incorrect rendering of the updated output in rHandsontable object (hot_to_r)

### ISSUE THREAD

**Issue by demydd** [jrowen/rhandsontable#91]
I have found an issue concerning the updated data output.
The script is as follwos:

    library(shiny)
    library(shinyapps)
    library(rhandsontable)

    ## CLIENT SIDE
    ui <- shinyUI(pageWithSidebar(
    headerPanel("Test of rHandsontable output - hot_to_r function"),
    sidebarPanel(
      actionButton("goButton", "test rhandsontable")

    ),
     mainPanel(
        rHandsontableOutput("all_updates")
       ,verbatimTextOutput('df_output')
     )
   ))

    ## SERVER SIDE
    server <- shinyServer(function(input, output) {

    observeEvent(input$goButton,{
      df <- data.frame ( x=1:10
                        ,y=1:10
                        ,z=factor(c("X","P"))
                        ,merge_xy="merger"
                       )
      df[,4] <- paste(df[,1],"+",df[,2])
      output$all_updates <- renderRHandsontable({
      
       rhandsontable(df, selectCallback = TRUE, height = 300) %>%
        hot_table(highlightCol = TRUE, highlightRow = TRUE) %>%
        hot_rows(rowHeights = 18)
      })
  
    })
  
    observeEvent(input$all_updates,{
    
      zzz <- hot_to_r(input$all_updates)
      zzz[,4] <- paste(zzz[,1],'+',zzz[,2],'+',zzz[,3]) 
      #the output of the modified dataframe
      print(zzz)
      
        output$all_updates <-renderRHandsontable({
        
          rhandsontable(zzz, selectCallback = TRUE, height = 300) %>%
            hot_table(highlightCol = TRUE, highlightRow = TRUE) %>%
            hot_rows(rowHeights = 18)
        
        })
      
      print(hot_to_r(input$all_updates))
    
      output$df_output <- renderPrint(
        print(hot_to_r(input$all_updates))
      )
    
    })
  
    output$all_updates <- renderRHandsontable({
      df <- data.frame ( x=integer(10)
                         ,y=integer(10)
                         ,z=factor(c("X","P"))
                       ,merge_xy="merger"
                        )
    
      rhandsontable(df, selectCallback = TRUE, height = 300) %>%
        hot_table(highlightCol = TRUE, highlightRow = TRUE) %>%
        hot_rows(rowHeights = 18)
    })
  
  })

  shinyApp(ui=ui,server=server)  

The issue is that the function **hot_to_r** return dataset from rHandsontable with one-step delay.  

You can experiment with changes to the column Z:   
after any changes in the column the output of the table has been updated immediately but the output of 'hot_to_r' function generates the snapshot of the previous version of the table (without latest changes).

I have placed the same question to [here](http://stackoverflow.com/questions/38370197/incorrect-rendering-of-the-updated-output-in-rhandsontable-object-hot-to-r)

**Comment by jrowen** [comment]
I made some updates to the dev version related to shiny input handling and would be curious to know if they fix the issue you're experiencing.

**Comment by demydd** [comment]
@jrowen thanks for your answers   :-)
considering the answer 1 - I have some ideas how to hadle such a drawback.
considering the answer 2 - i will try to test your amendments within a couple of days.

**Comment by demydd** [comment]
@jrowen 
I have tested your updated dev version.
It looks like just a thing I am  in need of :-)

I  would appreciate if you put the answer to my question at stackoverflow.com [see here](http://stackoverflow.com/questions/38370197/incorrect-rendering-of-the-updated-output-in-rhandsontable-object-hot-to-r). That would be very kind of you :-)

**Comment by JDH1988** [comment]
I'm experiencing the exact same issue! I would like to here if there's a solution for this!

**Comment by jrowen** [comment]
Please try out the latest dev version and let me know if you are still experiencing problems.

**Comment by RCesarSilva** [comment]
@jrowen I've also updated to version 0.3.2. and found that my tables crash my shiny app when trying to use hot_to_r for reading user inputs. The error was something on the lines of "input value is not an integer and NA values are not supported" (sorry for the vague description) which was curious since only integers were allowed in the table. After installing the development version the shiny app does not crash, however, the user inputs are not recorded, i.e., only zero values are recorded. 
Hope this helps.

**Comment by jrowen** [comment]
I believe this is fixed in the latest dev version, 0.3.2.2, and I'd appreciate it if you could install and provide feedback.  Thanks.

**Comment by RCesarSilva** [comment]
@jrowen I did install it and it seems to have done the trick. Thanks :) 
On another note, the input seems a bit slow. Is this something that can be sped up?

**Comment by jrowen** [comment]
Thanks for testing.  If you can file another issue, with a minimal example,
related to the input speed, I'll take a look.

**Comment by jrowen** [comment]
This should now be fixed.  Thanks.
