### ISSUE TITLE
Using renderer overrides the 'format'

### ISSUE THREAD

**Issue by daniel-matthews** [jrowen/rhandsontable#92]
Hi,

I have a table and I'm aiming to format one of the columns green. When this is applied the number formatting no longer works. Im not using the pipes as I have conditional statements in the function that builds the handsometable. 

```
Htable <- rhandsontable(x, rowHeaders = NULL)

Htable <-  hot_col(Htable , "Proposed Change", format = "$0,0.00",
                               renderer = "function (instance, td, row, col, prop, value, cellProperties) {
                               Handsontable.renderers.TextRenderer.apply(this, arguments);
                               td.style.background = 'lightgreen';}")
```

Thanks for your help.

**Comment by jrowen** [comment]
You need to call the format function in your custom renderer.  See
customRenderer in
https://github.com/jrowen/rhandsontable/blob/master/inst/htmlwidgets/rhandsontable.js
.

**Comment by tromika** [comment]
hello,

Same here. I don't get it from the customRenderer function so could you pls share a sample snippet?

Thanks in advance!

**Comment by jrowen** [comment]
You want to take a look at
```
Handsontable.renderers.getRenderer(type)(instance, TD, row, col, prop, value, cellProperties);
```
which relies on the [base handsontable renderers](https://github.com/handsontable/handsontable/tree/master/src/renderers) to call the formatting functions.

**Comment by jrowen** [comment]
Let me know if you're still running into trouble.  Thanks.

**Comment by rajesh1288** [comment]
> You want to take a look at
> 
> ```
> Handsontable.renderers.getRenderer(type)(instance, TD, row, col, prop, value, cellProperties);
> ```
> 
> which relies on the [base handsontable renderers](https://github.com/handsontable/handsontable/tree/master/src/renderers) to call the formatting functions.

I have the similar problem Im getting this piece of code as undefined. Could you please help me how to use this in brief?

Iam writing a custom renderer I want to reuse the same formatting which applied in columns of settings.
