### ISSUE TITLE
Conditional Formatting based on the values of another column

### ISSUE THREAD

**Issue by Atan1988** [jrowen/rhandsontable#93]
Hi Jonathan,

      Motivated by the conditional format example here:
      https://cran.r-project.org/web/packages/rhandsontable/vignettes/intro_rhandsontable.html
      I wonder whether there is a way to modify the code "td.offset(x,y)" to conditional format based on another column: 
      renderer = "
           function (instance, td, row, col, prop, value, cellProperties) {
             Handsontable.renderers.TextRenderer.apply(this, arguments);
             if (**td.offset(x, y).**value < -0.75) {
                 td.style.background = 'pink';
             } 
           }" 
      

Thanks,
Allen

**Comment by jrowen** [comment]
This example likely has the logic you need:
http://docs.handsontable.com/0.26.0/demo-conditional-formatting.html

**Comment by Atan1988** [comment]
Thank you for the reply! However, I am not able to make it work. 
Here is an example, I tried to change the first column's readonly status based on the value of the third column. I think I am probably just not understanding the concept behind the example.  It would be great if you can help me figure out how to make the below code work. 

Thanks!
Allen

DF <- data.frame(Item = c("A", "B", "C"),
                 value = c(1, 2, 3),
                 chk = c(TRUE, FALSE, TRUE))

rhandsontable(DF, 
              selectCallback = F,rowHeaders=NULL,
              strict=F, readOnly=T, useTypes=T, 
              height = 150)%>%
  hot_context_menu(allowRowEdit = FALSE, allowColEdit = FALSE)%>%
  hot_cols(colWidths= c(100, 100, 100)) %>%
  hot_col(col = 1, halign = 'htCenter', readOnly=T,
          renderer= "function(instance, td, row, col, prop, value, cellProperties) {
                            if (instance.getData()[row][2] === true) {
                               cellProperties.readOnly = false;
                            } else {
                               cellProperties.readOnly = true;
                            };
                          Handsontable.renderers.textRenderer.apply(this, arguments);
                        }")

**Comment by jrowen** [comment]
Are you still having trouble with this?

**Comment by Atan1988** [comment]
I haven't figured it out yet, as I got involved in some other projects.

**Comment by hsy9045** [comment]
Hi, I came across this thread when I had the same question. Thanks for sharing the insights! This solved my problem. The example from @Atan1988 is almost correct except for one little thing: the "t" in textRenderer should be capitalized. i.e. this works:

```R
DF <- data.frame(Item = c("A", "B", "C"),
                 value = c(1, 2, 3),
                 chk = c(TRUE, FALSE, TRUE))

rhandsontable(DF, 
              selectCallback = F,rowHeaders=NULL,
              strict=F, readOnly=T, useTypes=T, 
              height = 150)%>%
  hot_context_menu(allowRowEdit = FALSE, allowColEdit = FALSE)%>%
  hot_cols(colWidths= c(100, 100, 100)) %>%
  hot_col(col = 1, halign = 'htCenter', readOnly=T,
          renderer= "function(instance, td, row, col, prop, value, cellProperties) {
if (instance.getData()[row][2] === true) {
cellProperties.readOnly = false;
} else {
cellProperties.readOnly = true;
};
Handsontable.renderers.TextRenderer.apply(this, arguments);
}")
```

**Comment by Atan1988** [comment]
This is great! Thank you for finding out the issue with the code, @hsy9045.  I swear that I literally went crazy trying to debug the code couple month back.
