### ISSUE TITLE
Themes for rhandsontable

### ISSUE THREAD

**Issue by MySchizoBuddy** [jrowen/rhandsontable#94]
Is there a way to theme this so it doesn't look like an excel spreadsheet. But rather looks like a normal table.

**Comment by jrowen** [comment]
You can [edit the css behind the table](https://docs.handsontable.com/0.26.1/tutorial-styling.html) to create any type of look you'd like.

**Comment by jrowen** [comment]
Please feel free to submit a PR if you put together some theme options.  Once handsontable includes theme support, we'll also add that functionality to this library.  Thanks.
