### ISSUE TITLE
How to get an instance of rhansontable

### ISSUE THREAD

**Issue by debsush** [jrowen/rhandsontable#97]
Hi,

I have created a rhandsontable using your package as follows:

  output$fex_tech4 <- rhandsontable::renderRHandsontable({    

```
return(rhandsontable(values$fTechList4,height=150) %>>%
         hot_table(stretchH="all",overflow="visible",readOnly = TRUE,readOnly = TRUE) %>>%
         hot_context_menu(allowRowEdit = FALSE, allowColEdit = FALSE,
                          customOpts = list(
                            deselectrow = list(name = "Remove Row",
                                               callback = htmlwidgets::JS(
                                                 "function (instance) {
                                                 if (this.countRows()>0) {
                                                 this.alter('remove_row', this.getSelected()[0]);
                                                 this.render();
                                                 Shiny.onInputChange('fex_tech4trigger', Math.random());
                                                 }
                                         }")))))
})
```

Now at a later stage, I would like to access an instance of this rhandsontable using javascript and make some alterations to it.  I am currently unable to retrieve an instance of that rhansontable created above.
I tried the following in my javascript but it did not work

```
                                                              var $container = $("#fex_eco4");
                                                              var instance = $container.handsontable("getInstance");
                                                              var data = instance.getData();  
                                                              alert(data);
```

This gave a result undefined.

Appreciate your guidance on this.
Regards
SD

**Comment by jrowen** [comment]
Take a look at
https://github.com/jrowen/rhandsontable/blob/master/inst/htmlwidgets/rhandsontable.js
for some ideas on how to access the table.

If that doesn't help, you'll find a lot of documentation and many examples
at http://docs.handsontable.com/0.26.1/tutorial-quick-start.html.

**Comment by debsush** [comment]
Hi,

I have reviewed the reference materials.  Thanks for that.  However, nothing seems to be working in my effort to extract the handsontable instance when the table is created using  Rhandsontable.

Below works when the handontable is created in pure JS environment

```
$('#example').handsontable({
    data: data,
    minSpareRows: 1,
      search: true,
    colHeaders: true,
    contextMenu: true
  });


var OTl =  $('#example').handsontable('getInstance');
console.log(OTl.getData()); //Object
```

But when I write the below to getinstance of a handontable created using rhandsontable, I get the result as undefined

```
server.R
output$example <- rhandsontable::renderRHandsontable({
return(rhandsontable(data,height=150) %>>%
         hot_table(stretchH="all",overflow="visible",readOnly = TRUE,readOnly = TRUE) %>>%
         hot_context_menu(allowRowEdit = FALSE, allowColEdit = FALSE)
         )
})

javascript.JS
 var OTl =  $('#example').handsontable('getInstance');
console.log(OTl.getData()); //undefined
```

I am now at my wits end.  Please let me know if you have ever tried anything like this.

Regards
SD

**Comment by jrowen** [comment]
The table will be part of a htmlwidget instance, so I think you first need
to find the widget and then look for the table.  The Chrome
console/debugger can be very helpful here.

**Comment by debsush** [comment]
When I tried 
 var tabl = document.getElementById("fex_fund4");
 alert(tabl.innerHTML);

I get the following

<div class="ht_master handsontable" style="position: relative;"><div class="wtHolder" style="position: relative; width: 100%; height: 150px;"><div class="wtHider" style="width: 1920px; height: 51px;"><div class="wtSpreader" style="position: relative; top: 0px; left: 0px;"><table class="htCore"><colgroup><col class="rowHeader"><col style="width: 197px;"><col style="width: 268px;"><col style="width: 803px;"><col style="width: 302px;"></colgroup><thead><tr><th class="" style="height: 25px;"><div class="relative"><span class="colHeader cornerHeader">&nbsp;</span></div></th><th class=""><div class="relative"><span class="colHeader">Code</span></div></th><th class=""><div class="relative"><span class="colHeader">Category</span></div></th><th class=""><div class="relative"><span class="colHeader">Title</span></div></th><th class=""><div class="relative"><span class="colHeader">Frequency</span></div></th></tr></thead><tbody><tr><th class=""><div class="relative"><span class="rowHeader">1</spa...e="height: 1px; width: 1px; display: none; background-color: rgb(137, 175, 249);"></div><div class="wtBorder area corner" style="height: 5px; width: 5px; border: 2px solid rgb(255, 255, 255); display: none; background-color: rgb(137, 175, 249);"></div></div><div style="position: absolute; top: 0px; left: 0px;"><div class="wtBorder current" style="height: 2px; width: 2px; display: none; background-color: rgb(82, 146, 247);"></div><div class="wtBorder current" style="height: 2px; width: 2px; display: none; background-color: rgb(82, 146, 247);"></div><div class="wtBorder current" style="height: 2px; width: 2px; display: none; background-color: rgb(82, 146, 247);"></div><div class="wtBorder current" style="height: 2px; width: 2px; display: none; background-color: rgb(82, 146, 247);"></div><div class="wtBorder current corner" style="height: 5px; width: 5px; border: 2px solid rgb(255, 255, 255); display: none; background-color: rgb(82, 146, 247);"></div></div></div></div></div></div></div>

Wonder what should be my next steps.  Do I extract the class ht_master handsontable?

**Comment by jrowen** [comment]
Did you figure this out?

**Comment by debsush** [comment]
No i dud not.  I ended up building everything in javascript.

**Comment by jrowen** [comment]
Please re-open if you still have questions.
