### ISSUE TITLE
Getting last selected row/column when copy-pasting the data

### ISSUE THREAD

**Issue by Rustastra** [jrowen/rhandsontable#99]
Hello, 

I am using _selected event to capture $r,$r2,$c,$c2. However, these are the selections that the user is making. Is it possible to capture the automatically selected cell range?
So e.g. I am pasting data size 3x2 copied from Excel into the rhandsontable, I click, say, cell B2 and insert the array. Eventually I will have a range B2:C4 selected, but r2/c2 parameters still refer me to B2.
Thanks a lot!

**Comment by jrowen** [comment]
It is possible to add additional event hooks to the widget via the rhandsontable.js file.  You can find the handsontable options [here](http://docs.handsontable.com/0.26.1/Hooks.html#event:afterAutofillApplyValues).  Feel free to submit a PR or provide suggestions.
